### ISSUE TITLE
EntitiesDb : condition checking of elapsedTime is better to use >= instead of ==

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1146]
_From [OTS.Nexus](https://code.google.com/u/OTS.Nexus/) on August 21, 2013 01:07:36_

In both methods of the EntitiesDb class, the elapsedTime variable might be incremented beyond the Config.PERSISTENCE_CHECK_DURATION depending on the constant ThreadHelper.WAIT_DURATION, so it might be safer to use >= instead of == for comparison.

(in case the constant might change in future)

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1147_

**Comment by shiluka** [comment]
Hi,
I would like to work on this issue

**Comment by kanghj** [comment]
I have sent you an invite to join TEAMMATES an a contributor. I will assign this issue to you after you have accepted it.

**Comment by shiluka** [comment]
@kanghj ,
Thanks for the invitation. I accepted it.

**Comment by shiluka** [comment]
starting issue
