### ISSUE TITLE
Unable to Login Under Safari Private Browsing Mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1149]
_From [JiangYao...@gmail.com](https://code.google.com/u/102215434865598743482/) on August 21, 2013 20:15:04_

Unable to Login Under Safari Private Browsing Mode

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1150_

**Comment by MrFool** [comment]
I can confirm that I have just logged in with Safari using a private window.
