### ISSUE TITLE
Request.html does not  have a link back to Features.html

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1151]
_From [KAGEN...@gmail.com](https://code.google.com/u/106767547685865768379/) on August 22, 2013 21:09:41_

I understand that the Request for an Account page is part of the feature page. 
However, I feel that the user should be able to return to the features page by pressing the features tab by pressing the tab. Instead of using the browser back function

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1152_

**Comment by damithc** [comment]
How to reproduce: 
Go to http://teammatesv4.appspot.com/request.html
The 'Feature' tab is not clickable, but it should be.

**Comment by Siddhant085** [comment]
can I be assigned the issue?

**Comment by LowWeiLin** [comment]
@Siddhant085 You can try other issues that are not labeled forFirstTimers, usually doing just one of those should familiarize you with the workflow.

**Comment by suhas355** [comment]
Hi,

I have completed the orientation A-D successfully. can you please assign this issue to me.

Thanks
Suhas

**Comment by Maroooon** [comment]
Hey Guys,

I have completed the orientations tasks and also posted the required links and snaps to the teammates-contributors Google group. Can I be assigned this issue?

In fact I have already fixed it.  Should I further proceed with making the pull request?

Regards,
Shubham

**Comment by LowWeiLin** [comment]
@suhas355 Can you post the link on google groups where you completed orientation tasks A-D? I can't identify which one is it.
@Maroooon I sent an invitation to the contributors team. 

Whoever is not assigned can look for another issue =)

**Comment by suhas355** [comment]
Hi LowWeiLin.

   Please have a look into below link of my googlegroup chat

Thanks
Suhas

https://groups.google.com/forum/#!searchin/teammates-contributors/suhas/teammates-contributors/7JgP4uNWaYs/9HErkzM94PQJ

**Comment by LowWeiLin** [comment]
@suhas355 Please follow the contributor orientation guide here and complete phase A-D first:
https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true

You can also find instructions for gsoc applicants here:
https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true

**Comment by suhas355** [comment]
Hi LowWeiLin.
    I have followed the above links and my Dev setup is ready and I have already deployed the same to google app engine . Could you please let me know if I am missing anything

Thanks
Suhas

**Comment by LowWeiLin** [comment]
Phase D: tinker with the code
Fork our repo at GitHub
Create a branch names ‘tinker’
In that branch, do a small change to the code that makes a visible change to TEAMMATES UI. Preferably, your change should improve the UI in some way, or at least not make it worse.
Deploy the changed version to your staging server.
Push your changes to your fork.
<b>Post in the teammates-contributors Google group
a) the link to your app 
b) link to your fork 
c) a screenshot of the change you did (as seen on the UI)</b> (Also mention what changes you made.)

**Comment by suhas355** [comment]
Hi LowWeiLin,

   As you suggested, finished all the steps. Could you please have a look.
https://groups.google.com/forum/#!searchin/teammates-contributors/suhas/teammates-contributors/7JgP4uNWaYs/9HErkzM94PQJ

Thanks
Suhas K S

**Comment by weaveranoop** [comment]
Hi LowWeiLin,
I have completed the orientation tasks. I am now looking for fixing some issues and contributing to Teammates. Could you please assign me to this issue?

Regards,
Anoop Shukla

**Comment by weaveranoop** [comment]
Hi LowWeiLin,
I have completed the orientation tasks. I am now looking for fixing some issues and contributing to Teammates. I have already fixed this issue. Could you please assign me to this issue?

Regards,
Anoop Shukla

**Comment by LowWeiLin** [comment]
@weaveranoop This issue is already assigned. Please look for another one.

**Comment by LowWeiLin** [comment]
@weaveranoop please pick an unassigned issue

**Comment by weaveranoop** [comment]
Hi Low WeiLin,
I had commented on one of the issues that I was notified as unassigned.
Please look:
https://github.com/TEAMMATES/repo/issues/738

Can I please proceed with this?
Thanks.

Anoop Shukla
Phone:(+91)9660894920
LinkedIn <http://www.linkedin.com/pub/anoop-shukla/4a/6a4/109>

*Birla Institute of Technology & Science,* Pilani
