### ISSUE TITLE
Tooltip for some visibility options when creating feedback session question does not show

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1316]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on December 12, 2013 12:09:21_

Somehow these tooltips:
VISIBILITY_OPTION_RECIPIENT
VISIBILITY_OPTION_GIVER_TEAM_MEMBERS
VISIBILITY_OPTION_RECIPIENT_TEAM_MEMBERS

don't show up on the page even though the code for them is there.

The other two tooltips:
VISIBILITY_OPTION_OTHER_STUDENTS
VISIBILITY_OPTION_INSTRUCTORS

do appear properly on the page.

The code for all five tooltips seems identical so I'm not sure what happened.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1317_

**Comment by wkurniawan07** [comment]
No longer happening.
