### ISSUE TITLE
instructorStudentRecords: session name should be more noticeable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1389]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on December 24, 2013 09:57:24_

In terms of information hierarchy, session name is at a higher level and should stand out more. e.g. use dark blue background?

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1390_

**Comment by ngzhian** [comment]
By session name do you mean this? (just want to make sure because this issue is pretty old, things might have changed)
![s](https://cloud.githubusercontent.com/assets/1749303/8631953/ca629f68-2753-11e5-9b43-3901bcd3946a.PNG)

**Comment by damithc** [comment]
Looks like it got fixed along the way. Closing.
