### ISSUE TITLE
Respondents can specify their own 'other' answer to MCQ questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1422]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on January 03, 2014 21:33:03_

The groundwork (storage etc) is actually already in the code, but need to provide for it in the UI and pass it in to the back-end properly.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1423_

**Comment by taniach** [comment]
I would like to take this issue :)

**Comment by damithc** [comment]
No need to get assigned Tania. Just submit a pull request when it is done.

**Comment by taniach** [comment]
Here are some screenshots with the 'other' option implemented.

![issue1422_instructor](https://cloud.githubusercontent.com/assets/7547452/6982881/0bc781c8-da4a-11e4-8299-aaa3ed7d10bb.jpg)

The textbox is disabled if the 'other' radio button is not selected.

![issue1422_student1](https://cloud.githubusercontent.com/assets/7547452/6982880/0bc76968-da4a-11e4-827e-bc1f967512ef.jpg)
![issue1422_student2](https://cloud.githubusercontent.com/assets/7547452/6982882/0bc9c8de-da4a-11e4-87eb-7853b0d2792f.jpg)

If a student enters an answer in the textbox and chooses another answer, the text he entered remains but the textbox gets disabled.
 
![issue1422_student3](https://cloud.githubusercontent.com/assets/7547452/6982883/0bcaee30-da4a-11e4-8a2f-d82fc74de686.jpg)

**Comment by damithc** [comment]
The UI looks fine Tania.

**Comment by damithc** [comment]
Any progress on this?

**Comment by taniach** [comment]
I am working on FeedbackMcqQuestionDetails.java now. Plan to do the testing this weekend.

**Comment by damithc** [comment]
Try to finish soon. We cannot review PRs during the next couple of weeks
due to exams.

**Comment by taniach** [comment]
I have a question: In FeedbackMcqQuestionDetails.java, I want to use the following statement to check whether the other option is selected.

HttpRequestHelper.getValueFromParamMap(requestParameters,Const.ParamsNames.FEEDBACK_QUESTION_MCQOTHEROPTION)

May I know in which file or class I can set this value? Right now I can only retrieve it but not set it. Thanks.

**Comment by LowWeiLin** [comment]
These are the request parameters when the page is requested(GET/POST/etc). Most likely you want to add an input field to a form to set the value.

**Comment by taniach** [comment]
Do I need to edit any file for saving the 'other option' answer in the backend? I have added an additional fragment in the HTML if the 'other option' is enabled by an instructor. The HTML input form uses the same variable as the other pre-specified options i.e. value="${mcqChoiceValue}" . However, if the student chooses the 'other' button and types his own answer, it does not get saved.

**Comment by taniach** [comment]
Finished this issue
