### ISSUE TITLE
Bug in AppPage.verifyHtml causing non-equal htmls to pass

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1468]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on January 09, 2014 15:52:46_

I encountered a strange bug where verifyHtml would "confirm" that two htmls are equal even though the expected html is missing some parts. 

I attached the html that caused this. running actual.html against expected.html will pass the test (it shouldn't as expected.html is missing the parts shown in missing part.png).

Adding a random line at the point where the missing part is supposed to appear will cause the test to fail. In expected-fail.html I added the line THISWILLFAILTHETEST at the point where the missign parts is supposed to be and the test now properly fails.

**Attachment:** [actual.html expected.html expected-fail.html missing part.png](http://code.google.com/p/teammatespes/issues/detail?id=1469)

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1469_

**Comment by wkurniawan07** [comment]
No longer happening, verified with the two HTMLs said to be giving false positive.
