### ISSUE TITLE
instructorSessionsPage: give a link to the 'session types' section

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1486]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 10, 2014 18:45:37_

We can give a link to the 'session types' section of the help page. The link can be near the 'session type' selection box.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1487_

**Comment by tharakamd** [comment]
I've completed the orientation task, and here is the post I made on the google group
https://groups.google.com/forum/#!topic/teammates-contributors/x-CWroejzGQ

Can I be assigned to fix this issue ?

**Comment by tharakamd** [comment]
I went to the session page of instructor, and just after the session type selection box, there's alredy a link to the session section of the help page. Then where do I have to place the link,
I've attached a screenshot of the page (the existing link is marked by a red square)
![capture](https://cloud.githubusercontent.com/assets/8156185/6577994/85f4909e-c767-11e4-889f-208b6368627b.PNG)

**Comment by damithc** [comment]
Looks like this was fixed at some point, possibly covered under a duplicate issue. Closing.

**Comment by tharakamd** [comment]
You mean, I have to select another issue to fix

**Comment by damithc** [comment]
Yes, this one is fixed already.
