### ISSUE TITLE
mashup.jsp: make session instructions multi-line 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1498]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 13, 2014 18:33:38_

Otherwise, we can't see how the UI show multi-line instructions

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1499_

**Comment by MrFool** [comment]
Do assign me this issue as my first issue if it's still open.

Introduction can be found at -

https://groups.google.com/forum/#!topic/teammates-contributors/7lYDEGG6R24

**Comment by damithc** [comment]
@MrFool you are no longer required to get issues assigned. You can go ahead and submit pull requests.
