### ISSUE TITLE
studentEvalResults: the link to the description of the point calculation points to the now defunct spec.html

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1554]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 25, 2014 19:38:02_

We might have to put that documentation in a separate page.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1555_

**Comment by EgbeEugene** [comment]
please are u referring to this in studentEvalResults.jsp ?

 The actual calculation is a bit complex and the finer details can be found 
        <a href="/dev/spec.html#supplementaryrequirements-pointcalculationscheme">here</a>.

**Comment by EgbeEugene** [comment]
i meant   The actual calculation is a bit complex and the finer details can be found 
        <a href="/dev/spec.html#supplementaryrequirements-pointcalculationscheme">here</a>.

**Comment by damithc** [comment]
The problematic phrase is actually in instructorHelp.html#faq7a
The link should point to https://docs.google.com/document/d/1hjQQHYM3YId0EUSrGnJWG5AeFpDD_G7xg_d--7jg3vU/pub?embedded=true#h.n5u2xs6z9y0g

**Comment by damithc** [comment]
That makes the fix much easier. I'm allocating this for first timers.

**Comment by kanghj** [comment]
@EgbeEugene, would you like to do this issue?

**Comment by EgbeEugene** [comment]
yes i will be grateful if i am upportuned
