### ISSUE TITLE
UI has no common headers for <head></head> part

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1658]
_From [Gigi...@gmail.com](https://code.google.com/u/108486287164240412575/) on March 02, 2014 10:27:50_

What can be improved on the system? What can be added to the system? Add the common header(s) for <head></head> part. 
Otherwise, if frontend programmer wants to add lines in all UI head's part, there are 40+ files need to edit.

By using this enhancement, we can edit the whole UI headers by only editing one file. E.g. imagine we need to add a js file for the whole UI Please specify: 1) Exact page to implement/improve feature 40+ UI files with <head> 2) The details of the feature Use one template engine to build a header, then other pages just simply include the header.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1660_

**Comment by MrFool** [comment]
This is done during our JSTL migration
