### ISSUE TITLE
InstructorFeedbackPreviewAsStudentAction: Add a message to the Assumption.fail()

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1695]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 07, 2014 22:28:49_

Adding a message to describe which parameter was null can help in debugging.

This is the line in concern.
if (courseId == null || feedbackSessionName == null	|| paramStudentEmail == null) {
			Assumption.fail();
		}

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1697_

**Comment by bamboo3250** [comment]
Hi,

I completed step A to D in the Orientation Task List. https://groups.google.com/forum/#!topic/teammates-contributors/_dZr7_gCXA4

Could you assign this issue to me? Thank you.

Regards,
Khanh

**Comment by bamboo3250** [comment]
The problem has already been solved. Please close it.

Regards,
Khanh

**Comment by rcyq** [comment]
Ok thanks for informing.
