### ISSUE TITLE
NUMSCALE submission on firefox: no feedback for badly formatted response

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1715]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on March 14, 2014 14:16:53_

Badly formatted numbers are accepted (firefox 12) such as "1.1.1" or "1.-3" and although the system does not save it, it says that "All responses submitted succesfully!".

The user should receive a feedback about it in the status message.

This does not happen in IE and Chrome as they support the HTML5 number input box which does the validation for us.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1718_

**Comment by LowWeiLin** [comment]
No longer applicable
