### ISSUE TITLE
Add intro to mashup.jsp

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1743]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 23, 2014 08:55:31_

The page in concern is /dev/mashup.jsp

Add this at the top:

"This page contains a combination of all pages of the TEAMMATES app. It is used for manually inspecting the TEAMMATES UI for visual defects. To load this page, you need to run the test MashupPageUiTest.java."

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1746_

**Comment by zulrich91** [comment]
Please can i work on this issue ?

**Comment by kanghj** [comment]
Hi @zulrich91, I am having some trouble locating your post in the google groups for the completion of the orientation tasks. Can you post the link to it here?

**Comment by zulrich91** [comment]
Here are the links to the post and the other links that appear in the post.

https://groups.google.com/forum/?hl=en#!topic/teammates-contributors/Rc3LZ0h6KKc
http://4-18-dot-teammates-ulrich.appspot.com/
https://github.com/zulrich91/repo/tree/tinker
https://github.com/zulrich91/repo/

**Comment by zulrich91** [comment]
Invitation Accepted !!! Working now on the issue.

**Comment by zulrich91** [comment]
Just solved issue #1743

**Comment by kanghj** [comment]
Hi @zulrich91, have you made a pull request for this issue?

**Comment by zulrich91** [comment]
Hi Kang,
Please why should i make a pull request ? I don' t understand .


On Mon, Mar 16, 2015 at 12:11 PM, Kang Hong Jin <notifications@github.com>
wrote:

> Hi @zulrich91 <https://github.com/zulrich91>, have you made a pull
> request for this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/issues/1743#issuecomment-81585814>.
>



-- 
ulrich tchuenkam

**Comment by zulrich91** [comment]
Restarting issue .

**Comment by zulrich91** [comment]
I have done a new pull request for this issue , but immediately i edit the mashup.jsp file , an viewing the status of the repository it tells me that i have deleted the file /WEB-INF/classes/.gitignore. Meanwhile i have deleted this file. This is the same problem i had the first time i did a pull request for this issue

**Comment by kanghj** [comment]
You can omit the file from your commit. Before you commit, you can use 'git status' to check what files will be committed. If you see that an unwanted file is included, then remove it using 'git reset HEAD <file>'.

**Comment by zulrich91** [comment]
Ok, thanks Jin .

On Sat, Apr 11, 2015 at 2:00 PM, Kang Hong Jin <notifications@github.com>
wrote:

> You can omit the file from your commit. Before you commit, you can use
> 'git status' to check what files will be committed. If you see that an
> unwanted file is included, then remove it using 'git reset HEAD '.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/issues/1743#issuecomment-91839528>.
>



-- 
ulrich tchuenkam

**Comment by ign3sc3nc3** [comment]
Hi all, I'm working on this as my first issue
