### ISSUE TITLE
SettingUp.md: add instructions on how to login as a student

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1745]
Here is the outline:

First, login as an instructor and add some students.
Then, login as admin and search for the student. The search results will give you the 'join link' for that student. Logout from the instructor account and use that 'join link' to login. Remember to use 'http://localhost:8888' as the host instead of the one given in the join link.
That should allow you to access dev server as a student.

Alternatively, run the test cases first. That creates several student accounts in the datastore. Use one of them to login as a student.

**Comment by damithc** [comment]
@drunken-saint give this a try. @kanghj please be the reviewer for this issue.

**Comment by drunken-saint** [comment]
ok .

**Comment by drunken-saint** [comment]
I have a confusion . Is this issue asking to give instructions to the student users who use the software or is it instructing the developers on how create a student account to get a demo?
I think it is the latter one but I wanted to confirm , just in case .

**Comment by kanghj** [comment]
It is about instructing developers how to create student accounts on the dev server during development.

**Comment by drunken-saint** [comment]
got it .
![screenshot 34](https://cloud.githubusercontent.com/assets/7551036/5828534/7f947212-a12b-11e4-992e-dcd97de62f52.png)

I have made the changes . I am attaching the screenshot link above. Look for the point no. 8 at the bottom for the added instruction . Is it okay to commit the change now ?

**Comment by kanghj** [comment]
The instructions look correct but there appears to be some inconsistent phrasing and punctuation compared to the rest of the document. For example, punctuation marks should appear immediately after the end of a token. 

If you wish to, you can commit and make a pull request for further discussion.

**Comment by drunken-saint** [comment]
my repo is failing 46 tests and skipping 100+ tests .Any suggestiojns for troubleshooting ? I have checked all the scope of errors .
Should I start a new thread on the google group about this?

**Comment by kanghj** [comment]
Which tests are failing and what do the stacktraces look like? You can try looking through the [troubleshooting guide](https://docs.google.com/document/d/1_p7WOGryOStPfTGA_ZifE1kVlskb1zfd3HZwc4lE4QQ/pub?embedded=true#h.ex2tkw3n8rkf).

Your changes in this issue should not cause any tests to fail, so it should be a configuration error.
