### ISSUE TITLE
instructorFeedbackComments: Preserve line breaks in comments.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1768]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on April 02, 2014 23:49:50_

Currently, line breaks are lost when displaying comments.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1771_

**Comment by MrFool** [comment]
Seems that this has been done before.

![screen shot 2015-06-26 at 3 50 49 pm](https://cloud.githubusercontent.com/assets/6291947/8373004/26a2d782-1c1b-11e5-9bf6-fef0f725b3e3.png)
![screen shot 2015-06-26 at 3 50 39 pm](https://cloud.githubusercontent.com/assets/6291947/8373005/299ea1aa-1c1b-11e5-881f-aeab90e99c29.png)

Line breaks are being preserved as per the screenshots.
