### ISSUE TITLE
Implement link tests for student home page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1769]
_From [suprajab...@gmail.com](https://code.google.com/u/102256539854505211554/) on April 03, 2014 10:59:14_

Write tests to check the links in StudentHome. Implement the To-do flags in StudentHomePageUITest.Java

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1772_

**Comment by MrFool** [comment]
I believe this has been done as in

![screen shot 2015-06-26 at 3 22 39 pm](https://cloud.githubusercontent.com/assets/6291947/8372595/390c37d2-1c17-11e5-99a5-eedf4f2a1365.png)
![screen shot 2015-06-26 at 3 22 34 pm](https://cloud.githubusercontent.com/assets/6291947/8372594/38fce23c-1c17-11e5-845b-524a1a9498f6.png)
![screen shot 2015-06-26 at 3 22 28 pm](https://cloud.githubusercontent.com/assets/6291947/8372593/38fcc644-1c17-11e5-89ad-2875b981232e.png)

if it's not correct we can reopen this again
