### ISSUE TITLE
PageData::getTimeZoneOptionsAsHtml needs a space before selected=\"selected\"

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1780]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on April 15, 2014 22:19:05_

It should be " selected=\"selected\"
not "selected=\"selected\"

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1783_

**Comment by Siddhant085** [comment]
can I be assigned the Issue?

**Comment by damithc** [comment]
@LowWeiLin for your action please

**Comment by Siddhant085** [comment]
working on it.
