### ISSUE TITLE
instructorEvals: give an option to disable 'not sure' option

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1811]
Requested by a user

**Comment by wkurniawan07** [comment]
Quite an old issue, but still workable nonetheless. Will something like this (and all the related back-end works) suffice?
![1811_1](https://cloud.githubusercontent.com/assets/7261051/6914675/8248b5d4-d7bf-11e4-9e7e-884571e4f607.png)

**Comment by damithc** [comment]
May be `[  ] hide 'Not Sure' option` ?

**Comment by wkurniawan07** [comment]
It's a simple front-end change, but I opted for the one I wrote above because it's more intuitive to users, especially first timers who may not be aware that there is "Not Sure" as an option. It's ticked by default.

**Comment by damithc** [comment]
You have a point. Rephrase as `Allow response giver to select 'Not Sure' as the answer`
