### ISSUE TITLE
rename '#frameBodyWrapper' to '#mainContent' in all pages

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/repo#2059]

**Comment by LowWeiLin** [comment]
#frameBodyWrapper is still used in some javascript code. We need to check if they are working properly.

**Comment by chanjunweimy** [comment]
Hello, is this issue still open? :)

**Comment by LowWeiLin** [comment]
Search the project for "frameBodyWrapper" to check? It probably is still unresolved.

**Comment by wkurniawan07** [comment]
@MrFool here you go

**Comment by MrFool** [comment]
Nice thanks, I'll investigate this after we standardise first, we'll need to KIV this, currently it's still being used in JS and some other places as well so we want to keep "#frameBodyWrapper" for the time being to not break anything.

**Comment by franklingu** [comment]
the main page that is still referring to this id is most likely the compilation page for all other pages

**Comment by MrFool** [comment]
I realise #3719 and #3746 should be part of this issue, I will close the other 2 and proceed to finish them up in this issue - hopefully by tomorrow

**Comment by MrFool** [comment]
I'll do this when I'm back on Monday, JSTL green and checking the two reported bugs were more important so spent my time there instead.
