### ISSUE TITLE
Comment in UI test that it uses variables in the html pages 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2128]
Perhaps we should add a comment in the relevant UI test when a certain *.html page contains variables such as `{$test.student1}`. Otherwise, they could get overwritten when we modify the html page. Or perhaps we can add a check for it? e.g. `verifyContains("{$test.student}", raw_html_content)`

**Comment by wkurniawan07** [comment]
This should not be relevant anymore. With God mode we are sure that the placeholders stay as placeholders.
