### ISSUE TITLE
InstructorCourseEdit: missing space in status message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2202]
... successfully.An email ...

**Comment by MrFool** [comment]
This seems to already be fixed.

![screen shot 2015-04-23 at 10 36 47 pm](https://cloud.githubusercontent.com/assets/6291947/7299554/434c58ca-ea09-11e4-9058-ea434ca436e0.png)

Maybe we can close this to make the issues page less cluttered
