### ISSUE TITLE
fix the verifyHtmlMainContent in testContent method of UITests

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/repo#2213]
right now all the UITests are using verifyHtmlMainContent, which does not check head/header/footer for the page.

we should fix the way to do verifyHtml:
right now the proposed one: do one verifyHtml in testContent, verifyHtmlMainContent after that if verify html source is needed

**Comment by MrFool** [comment]
This has been done and is being merged into master in another issue / PR
