### ISSUE TITLE
studentFeedbackSubmitPage: label position shifts to right when resolution less than 768 x XXXX 

### ISSUE THREAD

**Issue by subhodip7** [TEAMMATES/repo#2238]
![studentfeedbacksubmit-7](https://cloud.githubusercontent.com/assets/4266544/3562456/29b2fec0-09f2-11e4-832a-f9ea55995fa3.png)

**Comment by ARSPRodrigo** [comment]
This happens because of the media queries (@ media (min-width:768px)) used in css (bootstrap.min) styling. It relates to the responsiveness of the project.

**Comment by damithc** [comment]
@ashrayjain any comments about this?

**Comment by ashrayjain** [comment]
@damithc This was fixed as part of the previous issue.
