### ISSUE TITLE
instructorHeader.jsp has redundant branches

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#2265]
In the header.jsp page, the function that truncates the googleId is called regardless of the actual length. The function handles the length of the googleId and truncates appropriately. So the check in the jsp page is redundant and can be removed

**Comment by Siddhant085** [comment]
can I be work on the Issue?

**Comment by bamboo3250** [comment]
Hi,

I completed the Orientation Task List (from A to D). https://groups.google.com/forum/#!topic/teammates-contributors/_dZr7_gCXA4

Could you assign this issus to me?

Regards,
Khanh

**Comment by EgbeEugene** [comment]
please can i work on this issue?

**Comment by kanghj** [comment]
@EgbeEugene, you need to look for another unassigned issue. Use https://github.com/TEAMMATES/repo/issues?q=is%3Aopen+label%3AforFirstTimers+no%3Aassignee
