### ISSUE TITLE
Remove {*} used in place of dates in test HTML pages

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#227]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on June 29, 2012 14:43:12_

Using regex matching to bypass dates in Ui tests weakens tests.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=228_

**Comment by thyageshm** [comment]
@damithc sir I guess this one is no longer needed? #4404 and other subsequent issues handle this.

**Comment by damithc** [comment]
Yes. closing.
