### ISSUE TITLE
Rename header in InstructorStudentsListPage to "Student List"

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#2292]
As title suggests and then fix related test cases

**Comment by suhas355** [comment]
Hi Sir,
    As per the instructions i have completed the orientation tasks A-D and posted the details on google group as well. Can you Please assign the task and instruct further guidelines.

Thanks
Suhas KS

**Comment by thyageshm** [comment]
hi! please try a "forFirstTimers" issue first before others. you can the get the list here: https://github.com/TEAMMATES/repo/issues?q=is%3Aopen+is%3Aissue+label%3AforFirstTimers

**Comment by visithamanujaya** [comment]
hi 
can i try this
i have already completed the orientation task
here is my link for my status
https://groups.google.com/forum/m/#!topic/teammates-contributors/gcRNXx4ei98

**Comment by thyageshm** [comment]
hi @visithamanujaya, is this going to be your first issue? if yes please choose one with the 'forFirstTimers' tag
