### ISSUE TITLE
Rename Barney Stinson in sample data

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2318]
There is a pattern in naming students in the sample course (to ease debugging)
This guy's name should have initials H.I e.g. Hugh Ivanov

**Comment by julian1990** [comment]
@LowWeiLin Can you assign this issue to me?
I'll find out ALL Barney Stinson(include barney.c.tmms@gmail.tmt) and rename him as Hugh Ivanov(include hugh.c.tmms@gmail.tmt).
I'll make sure of dev green before I commit my code.

**Comment by julian1990** [comment]
start issue
