### ISSUE TITLE
Add more FAQs to instructor help

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2336]
Is it compulsory for students to use Google accounts?
Student can submit feedback and view results without Google accounts. TEAMMATES send unique URL for each of those. But it is more convenient for them if they use Google accounts.

What if my course doesn’t have teams?
They can use a dummy value for the ‘Team’ column.

Is there a size limit for a course?
No. But courses bigger than 100 students need to divide the course into sections so that TEAMMATES know how to paginate reports when the entire report is too big to show in one go.

**Comment by vamshi-s** [comment]
I need to add this content in instructorHelp.html page. 
<li>
                                    <a href="#faq12">Is it compulsory for students to use Google accounts?</a>
 </li>
<li>
                                    <a href="#faq13">What if my course doesn’t have teams?</a>
  </li>
<li>
                                    <a href="#faq14">Is there a size limit for a course?</a>
</li>

@LowWeiLin  can you assign this task to me ?

**Comment by NisalaNiroshana** [comment]
Hi LowWeiLin ,
I have completed the orientation tasks successfully. Can you assign this issue to me ? 

Thanks

**Comment by NisalaNiroshana** [comment]
Hi LowWeiLin,
I have fixed the issue and sent you the pull request.
https://github.com/TEAMMATES/repo/pull/3067

Thanks

**Comment by LowWeiLin** [comment]
@NisalaNiroshana Please only fix this one, each person should ideally only do one issue labelled "forFirstTimers" also, follow the development process here: https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md

**Comment by NisalaNiroshana** [comment]
Hi LowWeiLin,

Thanks for the information. I have missed that doc. I have created the pull request again and sent it to you.
https://github.com/TEAMMATES/repo/pull/3069
Thanks

**Comment by tharakamd** [comment]
I've completed the orientation task, and here is the post I made on the google group
https://groups.google.com/forum/#!topic/teammates-contributors/x-CWroejzGQ

Can I be assigned to fix this issue ?

**Comment by LowWeiLin** [comment]
@tharakamd This issue has already been assigned. Please look for another issue.
