### ISSUE TITLE
Inconsistent link text in instructor help page

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2338]
"Tips for using the system"

This is inconsistent with the actual heading. ("Tips for conducting 'team peer evaluation' sessions")

**Comment by vamshi-s** [comment]
I need to modify this line in instructorHelp.html page. 
<li>
            <a href="#tips">Tips for using the system </a>
</li>

to
<li>
            <a href="#tips">Tips for conducting 'team peer evaluation' sessions </a>
</li>

@LowWeiLin  Can you assign this task to me ?

**Comment by NisalaNiroshana** [comment]
Hi LowWeiLin ,
I have completed the orientation tasks successfully. Can you assign this issue to me ?

Thanks

**Comment by NisalaNiroshana** [comment]
Hi LowWeiLin,

I have fixed this issue and sent you the pull request.
https://github.com/TEAMMATES/repo/pull/3068
Thanks

**Comment by suhas355** [comment]
@LowWeiLin  Can I be assigned with this bug?
P.S - Google group Discussion URL: https://groups.google.com/forum/#!searchin/teammates-contributors/suhas/teammates-contributors/7JgP4uNWaYs/9HErkzM94PQJ

Thanks
Suhas

**Comment by suhas355** [comment]
starting issue..

**Comment by suhas355** [comment]
@LowWeiLin I followed the methods to fix a bug. And pushed it into forked repository with branch Issue2338 and have raised a pull request. Please let me know if any changes are required.

Thanks
Suhas
