### ISSUE TITLE
Typo in process.md page stroy --> story

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#2391]
For t.Enhancement under Type, 'story' has been spelled as 'stroy'.

**Comment by tharakamd** [comment]
Can I be assigned to fix this issue

I've completed the orientation task, and here is the post I made on the google group
https://groups.google.com/forum/#!topic/teammates-contributors/x-CWroejzGQ

**Comment by tharakamd** [comment]
I started working on the issue, can anyone tell me how to add a label to the  issue

**Comment by ARSPRodrigo** [comment]
Tharaka,

I think this issue is already fixed.

**Comment by thyageshm** [comment]
@ARSPRodrigo it has not been fixed yet. @tharakamd  please continue and fix the issue
