### ISSUE TITLE
Cannot edit visibility of feedback response comments

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2430]
I can edit visibility when I add the comment to a feedback response. But I don't seem to be able to edit visibility afterwards.

**Comment by damithc** [comment]
Raised the priority

**Comment by wkurniawan07** [comment]
Does this still happen?

**Comment by wkurniawan07** [comment]
I can't seem to replicate this. Can somebody else confirm that this issue is no longer there?

**Comment by damithc** [comment]
Seems to be ok now. closing.
