### ISSUE TITLE
Show student name in the 'add comment' form

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2432]
This helps when the commentor wants to use the student's name in the comment.  Currently, I have to scroll up to see the student's name when I'm commenting on a response that has a few more responses above it.

**Comment by taniach** [comment]
Shall I take this issue?

**Comment by taniach** [comment]
Shall we display the name as a placeholder or plain text so that it can be selected for copy-paste?

**Comment by damithc** [comment]
Plain text is better.

**Comment by taniach** [comment]
![add_comment_preview](https://cloud.githubusercontent.com/assets/7547452/6650111/4988fb36-ca3c-11e4-9e3c-808d2da1681b.jpg)

Is this ok?

**Comment by damithc** [comment]
It is fine, but I need this more when giving comments for feedback
responses.

**Comment by taniach** [comment]
Ok, I will add it there too.

**Comment by taniach** [comment]
![add_comment_preview2](https://cloud.githubusercontent.com/assets/7547452/6650570/4d859a2e-ca54-11e4-8f5e-449b91111840.jpg)

I have added the giver and recipient names for feedback response comments. Is this ok?

**Comment by damithc** [comment]
Looks fine to me Tania.
