### ISSUE TITLE
Results published email sent even if the option is unticked.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2547]
It seems when I publish a session manually, the email is sent to everyone even though the session setting says 'published' emails are not to be sent out.

**Comment by karan173** [comment]
I have found the bug. Can i be assigned this issue?

**Comment by kanghj** [comment]
@karan173, you can go ahead and make a pull request for it. As you have already completed most of the tasks in the instructions for GSoC applicants, we no longer promise to review your work.

**Comment by karan173** [comment]
@kanghj Thanks for clarifying. Will do so!
