### ISSUE TITLE
Allow rotation of profile picture

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2610]
when editing/uploading a profile picture, it will be useful to have this feature.

**Comment by ashrayjain** [comment]
The plugin we are currently using for cropping the images (JCrop) has a known issue when the images are rotated. Fixing it involves editing the library itself as outlined here. http://stackoverflow.com/questions/20062754/make-jcrop-tracker-not-rotate-when-cropping-a-rotated-image

Instead, I would like to propose using another great library I have used in the past. https://github.com/matiasgagliano/guillotine
It supports rotating as well as cropping out of the box.

What do you guys think?

**Comment by LowWeiLin** [comment]
Not sure if it is the best way/library, but if we want to change the library, it should be done as separate issue first.
@thyageshm What do you think?

**Comment by thyageshm** [comment]
Yup, I think we should change the library in a separate issue and then attend to this issue. Also, ashray can you make 100% sure that we have to change the lib? Please check the existing doc on the choice of lib. If you still need to change, update the doc on available options and explain why this particular one.

**Comment by ashrayjain** [comment]
Yea, i read the docs here https://docs.google.com/document/d/1TGVkdu6JlOFX_2dJoeZu1avkiKj8ZqFcpBREJhKK78c/pub?embedded=true

I understand how the current system works, i.e. JCrop sends the crop info to the server, which then crops and saves it. The new library will actually be very similar to how JCrop works. The cropping will still be done server side.

As i mentioned, we may decide to stay with the same lib, but that lib has known issues with rotation. So to support rotation, we will need to hack on the library and fix the issues ourselves.

**Comment by naveebantrothu** [comment]
Guys did any one fixed Rotation issue with Jcrop , i want help from you guys

**Comment by kanghj** [comment]
@naveebantrothu, we stopped using JCrop
