### ISSUE TITLE
studentCommentsView page should be sorted 'recent on top'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2679]
It makes more sense to show most recent on top?

**Comment by karan173** [comment]
@damithc Do you mean the studentCommentsPage? Aren't the comments in it already sorted most recent on top.

**Comment by damithc** [comment]
I meant the page where students view comments. Is it sorted already?

**Comment by karan173** [comment]
Yeah the comments are already sorted.  java.util.Collections.sort(comments); is called in getCommentsForStudent() function in CommentsLogic.java which sorts the comments.

**Comment by damithc** [comment]
They don't appear to be sorted. I'm referring to the 'comments' tab of a
student. In particular, comments given for sessions are groped by session
(which is fine) but the sessions don't appear to be sorted in any order.

**Comment by karan173** [comment]
Yeah. I checked the code again. Can you confirm if my understanding is correct? 
So for each course, first there is a "Comments for students" section. The comments in this section are sorted.
Next comments for each Feedback Session are displayed one by one. Within each Feedback Session, there can be multiple Questions. Each question can further have multiple associated comments. 
So for each course, the hierarchy goes like this - Session > Questions > Comments. 
So how do you want the sorting to occur?

**Comment by damithc** [comment]
I would like the latest comments to be at the top of the page (to reduce
the need for scrolling).
May be this order?
Comments for students, ordered in reverse chronological order of comment
creation time
Comments for sessions, ordered in reverse chronological order of the
sessions

**Comment by karan173** [comment]
Thanks for your clarifications @damithc. Please assign this issue to me.
