### ISSUE TITLE
Add JS validation for MCQ/MSQ for number of options in instructorFeedbackEditPage

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2765]
Currently, there is a server side check to ensure at least 2 options for MCQ/MSQ.
We can add in client side JS validation to prevent the user from having less than 2 options (by preventing deletion of options if there are two or less options).
This will also ensure the UI remains consistent and not have times where there are no options showing.

**Comment by MrFool** [comment]
still in the process of fixing test cases, just one moment

**Comment by MrFool** [comment]
should be ok now
