### ISSUE TITLE
instructor>students tab : format the 'enroll' button differently

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2774]
The current one is colored very differently from the background and stands out a bit too much.

**Comment by JosephineKwa** [comment]
I would like to work on this issue :)

**Comment by damithc** [comment]
Too easy for you :-p Let's wait for @LowWeiLin to assign a slightly harder one for you.

**Comment by ARSPRodrigo** [comment]
@LowWeiLin 
Hi,

Can you assign me this issue. Because I'm interested in UI part.

**Comment by ARSPRodrigo** [comment]
@LowWeiLin
Hi,

Can you assign me this issue. Because I'm interested in UI part.

**Comment by bamboo3250** [comment]
Hi, 

Can you assign this issue to me?
Thank,

Khanh
