### ISSUE TITLE
InstructorHomePageUiTest fails (order of courses different)

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2782]
line `159         homePage.verifyHtmlAjax("/InstructorHomeHTMLWithHelperView.html");`
The courses order seems to be different

**Comment by LowWeiLin** [comment]
There already is a sort order enforced in instructorHomePage. By default, this is the creation date of the course, which is possibly not in any predictable order during testing.

**Comment by damithc** [comment]
Why not in predictable order. Can we make it predictable?

**Comment by LowWeiLin** [comment]
It seems this might be due to the test json files not having a creation date variable for the courses. Will look into that.

**Comment by damithc** [comment]
As @ackoroa mentioned, similar thing happens for the student home page ui test too.

**Comment by LowWeiLin** [comment]
For the student home page, it is due to the page sorting the table by JS after the page loads. Should be able to fix that. Still trying to fix/find the cause for instructor home page.
