### ISSUE TITLE
instructorResultDownload: constant sum summary section --> comma in student name splits into columns

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2785]
The student name in that section is split into multiple columns if the name contains a comma.

**Comment by vamshi-s** [comment]
@damithc  I am interested to look into this issue. Please can you provide me some more information.?

**Comment by LowWeiLin** [comment]
This is related to the downloading of results in csv format. It seems that the student name is not sanitized, leading to a split in column when a student name contains a comma.

**Comment by tharakamd** [comment]
I've completed one issue already, can you assign me to solve this issue
