### ISSUE TITLE
Typo: Double dot's in status message "The course has been added.."

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2791]
This is the message we give after successful creation of a course.

The course has been added.. Click here to add students to the course or click here to add other instructors.
If you don't see the course in the list below, please refresh the page after a few moments.

**Comment by LowWeiLin** [comment]
@Siddhant085 Could you try this one? The tests will likely need to be changed.

**Comment by Siddhant085** [comment]
Ya sure LowWeiLin. Assign the issue to me.

**Comment by Siddhant085** [comment]
I found and changed the grammatical error are their an tests relating to that because I couldn't find anything when I ran all tests for the project.

**Comment by Siddhant085** [comment]
I managed to fix the issue and as I progress I can feel myself getting more used to your code. Are there any more issues you would like to suggest? What shoud I do next?
