### ISSUE TITLE
html sanitized team name is stored in database

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2801]
html sanitization should only be done when displaying as html.
Need to find out what other fields are handled this way as well.

**Comment by bamboo3250** [comment]
Regarding the inconsistency of sanitization, I suggest we should keep raw data in all kinds of Entity objects and Attribute objects along the execution and only sanitize them before displaying in jsp files. 

In particular, I will create a function named toSanitizedVersion() for all classes need it. This function will create and return a new object having sanitized data of the original. Besides this function, we should not apply sanitizeForHtml() for any field of the class.

@damithc if you are okay with this, I will do thorough clean throughout the project.

**Comment by damithc** [comment]
@bamboo3250 can you do some more research and document your findings in https://docs.google.com/document/d/1Vd0r4ehTGeWvFjgH5eiGgzaNSRkorcSMPsjw_53PTpA/edit ?
I want to see what are the purposes of sanitizing (e.g. for security, for display, etc.), alternative approaches of doing it, which approach we choose and why. There may be third party libraries that can do it too.

**Comment by bamboo3250** [comment]
@damithc sure, I'll do more research regarding the sanitization. Could you grant me the permission to see and edit that document?

**Comment by damithc** [comment]
done.
