### ISSUE TITLE
Remove unused css in enableJS.jsp

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#2803]
In enableJS.jsp, from lines 6 to 29, there are some unused css that have been commented out.

**Comment by github-tn** [comment]
start issue

**Comment by ruchirsharma1993** [comment]
Hi, as per the specification given i have removed the comment in enableJS.jsp. Handling a issue for the first time, kindly inform if there is any problem with the same. 
Thanks

**Comment by ruchirsharma1993** [comment]
Thanks for assigning the task sir. As per instructions i have started working over the issue
