### ISSUE TITLE
modify tests to case-match the 'expected' file names to actual file names

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2824]
If the file names in the code is not an exact case-match to the actual file name, the test can throw a 'file not found' exception on Linux

**Comment by damithc** [comment]
@ZiXian92 can you try this one?

**Comment by ZiXian92** [comment]
Ok.

**Comment by ZiXian92** [comment]
Pull request created.

**Comment by ZiXian92** [comment]
Tore down the branch and pushed it out again after reverting to the latest commit with the final fix. However, I am unable to unstage changes in commits before the final fix as they contain changes to test.properties which were required for me to run the tests. Not sure if this is ok to make a pull request. There will be 4 commits with the final 2 commits being the changes to the test code itself.

**Comment by damithc** [comment]
You were supposed to make a copy of `test.properties.template` and rename the copy to `test.properties`, not rename the original file.
There are some temp files created by selenium webdriver that should not be added to the repo.
If the current branch is too messy, try creating a new branch and rebasing the specifc commits you need to that new branch.

**Comment by ZiXian92** [comment]
Ok. I will refork the repo and try again. Currently, the fork got too messy for me to tidy up.

**Comment by ZiXian92** [comment]
I have pushed out the changes to my fork and when I pulled and merged from the main repo, there were some changes. Should I push out the merge to my fork before creating pull request?

**Comment by damithc** [comment]
Yes, this may be helpful https://help.github.com/articles/syncing-a-fork/
