### ISSUE TITLE
Instructor Session page: reminder dropdown button is not disabled for instructor who does not have permission for it

### ISSUE THREAD

**Issue by rcyq** [TEAMMATES/repo#2848]
As per title.

Dropdown button of reminder is not disabled for instructor who does not have the permission to perform it. However, upon clicking on the button, the instructor is not able to sent the email.

Most probably it is just a Ui glitch.

![image](https://cloud.githubusercontent.com/assets/6453214/5642671/965bf25c-9688-11e4-8cef-2a334932b28b.png)

**Comment by damithc** [comment]
@ackoroa any thoughts?

**Comment by ackoroa** [comment]
Where is the permission checked? Even for the original Remind button only whether or not the session is opened is checked to determin whether it is disabled (see PageData.kava line 809 and line 858, getInstructorFeedbackSessionActions method)

**Comment by damithc** [comment]
Can discuss further when @franklingu is back. He is the one in charge of access control.

**Comment by franklingu** [comment]
it seems the code in page that generates remind link is not checking for accessibility but the remind action is checking can_modify_session privilege. the html generated in pagedata->getInstructorFeedbackSessionActions should be updated.
this is just my understanding of the existing code. cannot remember the reason for this but most likely it is a bug with my existing code

**Comment by franklingu** [comment]
should I take this one? or @ackoroa you want to fix it?

**Comment by damithc** [comment]
Go ahead and fix it @franklingu .

**Comment by franklingu** [comment]
the example shown in the picture is the error case? can you provide the details for replicating the bug? the disabled attribute for remind link group is not following the same policy--want to confirm which one is correct based on the bahaviour
