### ISSUE TITLE
Place 'please remember to log in' message on top of mashup page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2854]
mashup.jsp page doesn't work if the user is not logged in (as admin?)

**Comment by ruchirsharma1993** [comment]
Hi, 
Can you assign this issue to me ?
Thanks

**Comment by LowWeiLin** [comment]
@ruchirsharma1993 Please complete the orientation tasks A-D first. They can be found here: https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true

**Comment by ruchirsharma1993** [comment]
Hello Sir,
As per the instructions i have completed the orientation tasks A-D and posted the details on google group as well. Please assign the task and instruct further guidelines.

Thanks

**Comment by supunharsha** [comment]
Hi,
Can you assign this issue to me

**Comment by LowWeiLin** [comment]
@supunharsha Could you give a link to the google groups thread where you posted your completed orientation tasks A-D?

**Comment by supunharsha** [comment]
You can see my thread at:-

https://groups.google.com/forum/#!topic/teammates-contributors/3j3a969dLFM

**Comment by ruchirsharma1993** [comment]
Sir,
As I was UNASSIGNED for this Issue, should i work over this now or not ?

Thanks

**Comment by LowWeiLin** [comment]
@ruchirsharma1993 No need for you to work on this. Each person only needs to do one issue labelled "forFirstTimers" to get familiar with the workflow. You can look for more difficult issues to fix.

**Comment by LowWeiLin** [comment]
@supunharsha I have sent you an invitation to the contributors team. Will assign you after you accept.

**Comment by supunharsha** [comment]
Hi

I have accepted the invitation and i am ready to go.

**Comment by supunharsha** [comment]
starting the issue.
