### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing on dev server due to profile picture links

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2860]
Here is an example:
![image](https://cloud.githubusercontent.com/assets/1673303/5694287/0b9ef27e-9988-11e4-8671-f0f66a260099.png)

**Comment by damithc** [comment]
@thyageshm any ideas?

**Comment by kanghj** [comment]
We usually put a wildcard in place of the student email. In this case, it seems like I missed this out in a previous issue. I will fix this asap.

**Comment by thyageshm** [comment]
Yes, I believe the email over there is encrypted and so will be different when run on live/dev server (depending on the key that is provided), and hence it should kept as the wild card character.
