### ISSUE TITLE
Archiving doesn't work for older courses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2863]
I get a success message but the course still appear under active courses. This is probably because some older Instructor objects don't have the `isArchived` attribute.

**Comment by damithc** [comment]
This tech report may be relevant. If it doesn't cover the current situation, we should enhance the report to cover it (for future reference).
https://docs.google.com/document/d/1syHy4BPrM7TkCP7PJYvYZmt7rkRROWqYvBh8w_ZJt1w/pub?embedded=true

**Comment by kanghj** [comment]
Can I have more details about the course to be archived, such as the date that the course was created? I've created courses on earlier versions when the Instructor object didn't have the <code>isArchived</code> attribute and it works correctly when I archived them on master, so the problem might be somewhere else.

**Comment by damithc** [comment]
There is no way to find when the course was created, but must have been at least one year ago. 
This is what I see in the console
![image](https://cloud.githubusercontent.com/assets/1673303/5694578/3e45aa94-99a4-11e4-9fdd-fcea7c7cec2a.png)
Interestingly, there is another instructor in the same course which shows up like this
![image](https://cloud.githubusercontent.com/assets/1673303/5694579/6e5b344c-99a4-11e4-9603-17c6e61f12f3.png)
Neither can be archived.
This is what a new instructor object looks like
![image](https://cloud.githubusercontent.com/assets/1673303/5694583/e937eee4-99a4-11e4-88f6-75f70eeae023.png)

**Comment by damithc** [comment]
Found something else. I tried archiving the second one, and now that object looks like the first object too. i.e. missing fields are present but shown as uneditable.

**Comment by damithc** [comment]
if the attribute is missing (which means it is a legacy object), create a new object and delete the old one?

**Comment by thyageshm** [comment]
sir, when we archive it "should" update the instructor object to take the new attributes as well. I would just like to ask whether the archiving problem is happening in the home page or the courses page

**Comment by damithc** [comment]
However, a quick google search says there is no need to create a new object. simply updating the existing object is supposed to be enough.

**Comment by damithc** [comment]
@thyageshm in both pages. Yes, it is supposed to update, but seems only new objects get updated.

**Comment by damithc** [comment]
@kanghj the older version you tried may not be old enough. May be create a new temp version in which the attribute is missing and see if you can reproduce the problem?

**Comment by kanghj** [comment]
Ok, I will try that now

**Comment by kanghj** [comment]
Even in the temp version with the attribute missing, the instructor object is correctly updated on archiving.

**Comment by damithc** [comment]
Did you try on a staging server?

**Comment by kanghj** [comment]
Yes, archiving works correctly on the staging server as well. Here are instructor objects before and after I clicked on archive
![noattr](https://cloud.githubusercontent.com/assets/2216119/5694862/240fec88-99b9-11e4-9dc0-17dbefd36435.PNG)
![withnewattr](https://cloud.githubusercontent.com/assets/2216119/5694863/26b28a7c-99b9-11e4-81fd-cbb1e0ab878f.PNG)

**Comment by kanghj** [comment]
Ok, after I have removed the registration key attribute from the instructor, archiving stops working. I will   investigate this and fix this as soon as I can.

**Comment by damithc** [comment]
Good job spotting that. :+1:

**Comment by kanghj** [comment]
This issue also affects editing other instructor attributes from instructorCourseEditPage. At the moment, I am still not sure why not having a registration key would prevent the other attributes from getting saved. However, I think a quick fix would be to generate a registration key for the instructor and set it if it is null. Is this ok?

**Comment by LowWeiLin** [comment]
For the other attributes, I could modify the migration script i am writing for #1711 to generate registration keys if necessary.

**Comment by damithc** [comment]
keys are autogenerated and tied to object identity so adding key fields
might have complications such as the one we are facing.
Yes, can add the field if it is null. Can also add it to the migration
script. I don't think the two solutions will conflict.

**Comment by damithc** [comment]
Actually, the registration key doesn't seem to be auto-generated, so I'm not sure why it has a special behavior.
