### ISSUE TITLE
studentHelp.html: mention that students need not 'join'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2867]
For step 1, we can add the following:
Note that joining a course is optional. If you do not join, you can still submit feedback and view feedback responses using links sent to you by TEAMMATES. If you join, you get access to extra features such as the ability to see all your feedback sessions in a single home page.

**Comment by karan173** [comment]
@damithc Can I be assigned this issue?

**Comment by karan173** [comment]
starting issue
