### ISSUE TITLE
instructor: session edit: Add one more blank row to new rubric questions 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2873]
Currently we have one row with sample values. We can add one more blank row to make it look more like a typical rubric question.
![image](https://cloud.githubusercontent.com/assets/1673303/5714695/6fc53904-9b07-11e4-9a2c-0bb37c00f7cb.png)

**Comment by JosephineKwa** [comment]
Prof @damithc  I would like to work on this issue! :)
