### ISSUE TITLE
join email without link

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2878]
One student received this email (no link).
```
Subject: TEAMMATES: Invitation to join course [Course: xyz][Feedback Session: Practice Evaluation]
 
Hello abc,
Please join the course to participate in future sessions held by the course. 
*The above link is unique to you. Please do not share it with others. 
If you encounter any problems when using the system, you can email TEAMMATES support team at teammates@comp.nus.edu.sg
Regards, 
TEAMMATES Team.
```

**Comment by damithc** [comment]
@kanghj can you look into this?

**Comment by kanghj** [comment]
Ok, I will look into this

**Comment by damithc** [comment]
I think this happens when the 'send opening reminder' is unticked. TEAMMATES seem to send an email anyway, but it doesn't contain any useful links.

**Comment by damithc** [comment]
I think we'd better tick that option by default and disable editing for it. The opening reminder is necessary because now we allow using TEAMMATES without joining.

**Comment by damithc** [comment]
And change the sending logic to send opening reminders irrespective of the option value, to cater for legacy sessions that has this option disabled.
