### ISSUE TITLE
update settingup.md for java 8 and eclipse luna

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2886]
Most new contributors are likely to have java 8 and eclipse luna by default. We need to update the documentation to help them set up correctly.

**Comment by damithc** [comment]
@LowWeiLin could you install Java 8, switch to Luna, and update the documentation accordingly? We are going to have many new contributors from next week.

**Comment by LowWeiLin** [comment]
I have setup(upgraded) the project to eclipse luna, but I can't get it to run properly with java 8. It seems that java 7 is recommended by appengine. It mentions it might be possible to use java 8 by passing in java 7 flags, but I think sticking with java 7 would be easier in that case...
https://cloud.google.com/appengine/docs/java/gettingstarted/setup

The only differences in using eclipse luna are some download links. Will update the docs soon.


*For upgrading from existing setup of TEAMMATES, install the below and point eclipse to the previous workspace

Download and install Eclipse 4.4 (Luna)
Choose the version "Eclipse IDE for Java EE Developers"
https://projects.eclipse.org/releases/luna

Install Google Plugin for Eclipse 4.4 (Luna)
Follow instructions here: (Only install GooglePlugin for Eclipse, no need to select other plugins)
https://developers.google.com/eclipse/docs/install-eclipse-4.4

Install TestNG
http://testng.org/doc/eclipse.html

**Comment by damithc** [comment]
Yes, let's advise to install Java 7 even if they have Java 8 installed.
Another issue is if eclipse is configured to use Java 8 (but using java 7
for our project), can we deploy? I remember there was an issue where one of
our new contributors had to set Eclipse to use Java 7 to deploy.

**Comment by LowWeiLin** [comment]
I think java 7 needs to be used for both project properties and also under eclipse's window > preferences.
