### ISSUE TITLE
instructor copy sessions: annotate the original course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2894]
In the modal window, we can annotate the course from which the session is copied. The annotation can be in a different color. Such an annotation can minimize user errors of trying to copy the session to the same course but using the same name.
e.g. 
[CS2103] Software Engineering _{session currently in this course}_

**Comment by arvind-kalyan** [comment]
Shall I try this?

**Comment by arvind-kalyan** [comment]
Sir, Just to be clear if I understood it correctly, in the modal window upon clicking "**Copy from previous feedback sessions**" button, if a user selects a course **X** from **Create in course** drop-down list, we have to put an annotation in all the rows of **X** where a previous feedback session exists. Is it correct?

**Comment by damithc** [comment]
Sorry I wasn't clear before. This applies to the 'copy' feature you get when you go to the 'edit' option of a session. That feature is used to copy a session to multiple courses.

![image](https://cloud.githubusercontent.com/assets/1673303/6453657/4d585230-c17b-11e4-9e12-ac24cf99c9ca.png)

**Comment by arvind-kalyan** [comment]
Sir, I have attached a screenshot. It's working correctly. But it comes in two lines. For long course names / course ids, this will be a problem. I have set the font size to **2** here. Should I increase the size of the modal window?

![2894_1](https://cloud.githubusercontent.com/assets/5078299/6455698/bdc63f62-c17d-11e4-9f79-8f0b9bd993ba.png)

In the pic below, font size is **1**

![2894_2](https://cloud.githubusercontent.com/assets/5078299/6455756/88896670-c17e-11e4-91ee-8afab6ecb12b.png)

**Comment by damithc** [comment]
I'm ok with slightly wider modal window and slightly smaller text for the annotation.

**Comment by arvind-kalyan** [comment]
Increasing width would would require overriding the properties of bootstrap "modal" class and thereby using a custom class only for this particular modal window. In my opinion, font size < 1 would make it too small to read. Should I change that?

**Comment by damithc** [comment]
How about adding a line break so that the annotation appears right below the course name?. That way, it is closer to the check box and hard to miss. Make the text size smaller than regular, but not too small.

**Comment by arvind-kalyan** [comment]
Okay. So I'll put a line break and also, the font size = 1.

**Comment by thyageshm** [comment]
@arvind-kalyan, sorry if I am saying this very late (and you can choose to ignore it as well, we can open a separate issue), but could we try placing like an asterisk(*) at the end of the session name and provide a key at the bottom of the modal saying:   "* Sessions from this course"

This maybe a more robust solution as length of sessions will no longer matter much, and the indication is more subtle

@damithc what do you think sir?

**Comment by arvind-kalyan** [comment]
@thyageshm Hello, yeah, no problem with me. We can do it here itself.. No need of a separate issue. :)
But the problem with putting it as an asterisk could be that, if suppose the instructor was very busy, he might not see the entire course name. he might just look at the course ID (given in [ ] ), and select the course. In this case he won't notice the asterisk at the end of the course name  (if it's a long name, say). Another option could be to put the asterisk after the check-box before [ course_ID ].

**Comment by LowWeiLin** [comment]
How about making the [Course ID] a different colour if the issue is that the asterisk is not visible?

**Comment by arvind-kalyan** [comment]
In that case, we'll have to explain what a colored [Course ID] means, and also mention "Sessions from this course". We could just put the asterisk near [Course ID], right?

**Comment by LowWeiLin** [comment]
Sure, you can try different solutions and use what you think is the best solution.

**Comment by damithc** [comment]
The annotation is supposed to appear as a separate line below the course
name, so the length of the course name is no longer an issue. May be Arvind
can post a screenshot of the latest version?

**Comment by arvind-kalyan** [comment]
Here it is. 

![2894_latest](https://cloud.githubusercontent.com/assets/5078299/6485964/8c278fb6-c2ad-11e4-834e-0e5ae7f32868.png)

**Comment by damithc** [comment]
May be make the course ID red as well, to show that the annotation belongs
to the line above and not the one below?

**Comment by arvind-kalyan** [comment]
Okay.

**Comment by arvind-kalyan** [comment]
@damithc sir, Is this ok?

![2894_3](https://cloud.githubusercontent.com/assets/5078299/6486487/64fe392c-c2b1-11e4-8d78-ba3297534a05.png)

**Comment by damithc** [comment]
Yup, looks good.
