### ISSUE TITLE
instructor help page: select the radio buttons in the rubric question sample

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2899]
The radio button can be shown as selected.
![image](https://cloud.githubusercontent.com/assets/1673303/5792932/d23d0b36-9f6a-11e4-80e6-8292f88d3a51.png)

**Comment by manvijain** [comment]
Hi, I would like to work on this issue to get acquainted with the workflow. Can it be assigned to me?

**Comment by manvijain** [comment]
starting issue

**Comment by manvijain** [comment]
I changed the required HTML code and tested against the dev server. There are 2 test cases failing which were failing even before I made changes. I created a pull request with the name of this issue. Is that okay?
