### ISSUE TITLE
Instructor: Add a confirmation dialog to 'delete student' button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2902]
This action is irreversible. We should get a confirmation first.

**Comment by thyageshm** [comment]
sir I would believe this one can be labelled as d.easy as we are doing something similar for deletion of sessions in instructorFeedbacksPage. This code is short and easily transferable.

**Comment by thyageshm** [comment]
Oh just to confirm, which page are we talking about here? cos the instructorStudentList page already has the confirmation for deletion of students

**Comment by damithc** [comment]
I don't remember the exact page. Probably the search results page? Should check all places where a student can be deleted. 
The bar is quite low on the `d.moderate`. If it requires changes in multiple places including tests, we can consider it as `d.moderate`

**Comment by thyageshm** [comment]
ok

**Comment by halfdreamer** [comment]
hi,
I have just gone through instructor pages.instructorStudentList page and InstructorCourseStudentDetailsPage already have confirmation dialog before deleting a student.But InstructorSearchPage require similar dialog..shall i try this ?

**Comment by LowWeiLin** [comment]
@halfdreamer Go ahead and tackle the issue. =)

**Comment by halfdreamer** [comment]
Student delete confirmation in InstructorSearchPage is already specified,its just that  toggleDeleteStudentConfirmation() is not defined in this context.Adding the definition to instructorSearch.js fixes the issue....please correct me if am wrong...i have added the screen shots...
![error](https://cloud.githubusercontent.com/assets/1180133/6529453/dc672bb0-c44e-11e4-821f-16b89c7827cf.png)
![fix](https://cloud.githubusercontent.com/assets/1180133/6529451/da106dd6-c44e-11e4-81c7-4b60fe4aac80.png)
