### ISSUE TITLE
Rubric question results csv: give choice number as a separate column

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2905]
If we give it in the same column, it's harder to post process the data, especially in cases where the value is a number. e.g. see screenshot
![image](https://cloud.githubusercontent.com/assets/1673303/5832266/2314edf8-a17d-11e4-8252-63096f41919d.png)

**Comment by github-tn** [comment]
take the first row as example, "4" means the content of "choice 2"? So we take the choice number as a separate column, what is the header for column "choice content"?

**Comment by damithc** [comment]
The two columns can be 'Choice value' and 'Choice index'? @LowWeiLin what do you think?

**Comment by LowWeiLin** [comment]
Yes, that sounds good. However, "Choice number" might be simpler to understand than "Choice index"?

**Comment by damithc** [comment]
Yes, 'choice number' is better.

**Comment by github-tn** [comment]
Can I take this issue?

**Comment by LowWeiLin** [comment]
Sure

**Comment by github-tn** [comment]
for no response, what choice number shall we use?
