### ISSUE TITLE
Student profile: 'Email' --> 'Long term contact email'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2906]
Change 'Email' --> 'Long term contact email'

![image](https://cloud.githubusercontent.com/assets/1673303/5833688/a90ea38c-a190-11e4-8c0b-8a1d66461336.png)

**Comment by thyageshm** [comment]
sir shall I review this one?

**Comment by damithc** [comment]
Sure Thyagesh.

**Comment by ARSPRodrigo** [comment]
Sir,
Can I look into this issue?

**Comment by ARSPRodrigo** [comment]
Hi,

I'll look into it.

On Sun, Mar 8, 2015 at 12:05 PM, Low WeiLin <notifications@github.com>
wrote:

> Assigned #2906 <https://github.com/TEAMMATES/repo/issues/2906> to
> @ARSPRodrigo <https://github.com/ARSPRodrigo>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/issues/2906#event-248112090>.
>



-- 
*Prasanna Rodrigo,*
*Computer Engineering Undergraduate,*
*Department of Computer Engineering,*

*University of Peradeniya.**+94 720764791*
*::Linkedin <http://lk.linkedin.com/in/prasannarodrigo>*

**Comment by ARSPRodrigo** [comment]
Hi Low,

Can you assign me to issue #3059 also?

On Sun, Mar 8, 2015 at 12:06 PM, Prasanna Rodrigo <rodrigo.rajitha@gmail.com
> wrote:

> Hi,
>
> I'll look into it.
>
> On Sun, Mar 8, 2015 at 12:05 PM, Low WeiLin <notifications@github.com>
> wrote:
>
>> Assigned #2906 <https://github.com/TEAMMATES/repo/issues/2906> to
>> @ARSPRodrigo <https://github.com/ARSPRodrigo>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TEAMMATES/repo/issues/2906#event-248112090>.
>>
>
>
>
> --
> *Prasanna Rodrigo,*
> *Computer Engineering Undergraduate,*
> *Department of Computer Engineering,*
>
> *University of Peradeniya.**+94 720764791 <%2B94%20720764791>*
> *::Linkedin <http://lk.linkedin.com/in/prasannarodrigo>*
>



-- 
*Prasanna Rodrigo,*
*Computer Engineering Undergraduate,*
*Department of Computer Engineering,*

*University of Peradeniya.**+94 720764791*
*::Linkedin <http://lk.linkedin.com/in/prasannarodrigo>*
