### ISSUE TITLE
InstructorHomePageUiTest fails on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2923]
Fails at line 161
`homePage.verifyHtmlAjax("/InstructorHomeHTMLWithHelperView.html");`

**Comment by damithc** [comment]
passes on the live server though

**Comment by damithc** [comment]
Anybody else has this problem?

**Comment by LowWeiLin** [comment]
This might be different from the original failure/issue, but is somewhat related.

@franklingu I think you can fix this here.

---

The following tests/lines fail after #2848 was merged
InstructorHomePageUiTest is failing at line 161
![image](https://cloud.githubusercontent.com/assets/3910365/6082599/967651a0-ae5d-11e4-85a2-f030f869cecc.png)

And AdminHomePageUiTest at line 148
![image](https://cloud.githubusercontent.com/assets/3910365/6082559/56036392-ae5d-11e4-8f41-51ba61e9fbe6.png)

**Comment by damithc** [comment]
This not fixed yet?

**Comment by franklingu** [comment]
Not yet. I am manually changing the file. Too many unrelated changes are
introduced otherwise

**Comment by franklingu** [comment]
this is fixed in prev commits right?

**Comment by wkurniawan07** [comment]
Pull request for fix is up. I also put some explanation on the origins of this issue there :smiley:
