### ISSUE TITLE
InstructorFeedbackResultsPageUiTest fails on the staging server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2925]
fails at line 362 `resultsPage.addFeedbackResponseComment("test comment 2");`
The add comment button is clicked but the new comment form is not open. The test can pass if I manually click the button again within a few seconds. So it looks like a timing issue.
![image](https://cloud.githubusercontent.com/assets/1673303/5886742/ada18ba2-a3e9-11e4-9abd-6865d71973f2.png)

**Comment by wkurniawan07** [comment]
@damithc I believe this is the same issue as #3188? If so, then it is solved already.

**Comment by damithc** [comment]
Looks like a duplicate. Closing.
