### ISSUE TITLE
instructor session publish confirmation dialog: evaluation --> session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2929]
Rephrase: evaluation --> session
![image](https://cloud.githubusercontent.com/assets/1673303/5891882/4d68676c-a4e6-11e4-81ef-f175cdf641df.png)

**Comment by ARSPRodrigo** [comment]
Is this happen when an instructor is going to publish a feedback session?

**Comment by damithc** [comment]
yes

**Comment by drunken-saint** [comment]
I would like to give this a try . Please assign it to me :)

**Comment by kanghj** [comment]
@drunken-saint, by this point, you are at task 6 of the [Instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true). You can still work on this issue and when you are done, make a pull request, but we don't promise to review your pull requests during the application period.

**Comment by drunken-saint** [comment]
Okay @kanghj  . I'try to resolve this issue before the application period starts . 
I've made the changes in the /js/instructor.js now . I am attaching the screenshot and will update again after modifying the test files . I had one more query : Should I make the change for the unpublish button also or should there a seperate issue be created for this ? @damithc 
![screenshot 77](https://cloud.githubusercontent.com/assets/7551036/6565704/1d5d95d8-c6d8-11e4-882a-70efd54e3ebd.png)

**Comment by drunken-saint** [comment]
No changes were need in the test files . Issue2929 is dev green . I've created the pull request . 
I've not been officially assigned this issue yet . Please do so @damithc  @kanghj  .

**Comment by kanghj** [comment]
@drunken-saint, since you have reached task 6 in the instructions for GSoC applicants, we no longer officially assign issues to you. You can continue to make pull requests for the issues. :) Try to look for harder issues from now on.

**Comment by drunken-saint** [comment]
OK . So , does this mean I shouldn't go for the issues with forContributors label , right ? 
And , I am creating another issue for the unpublish confirmation dialog too .However, I won't be dealing with it as you asked me to try the harder ones, it might help a new contributor get familiar with the 
code . Cheers :)
