### ISSUE TITLE
settingUp.md : grammatical inconsistency/typo present

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#2931]
In the topic "Setting up the dev server" ,point no. 6 ,"login" should be replaced with "log in".

**Comment by Siddhant085** [comment]
I am a first timer and I made the above change committed it and created the pull request it got merged with the master branch. Now what should I do to update in the main project

**Comment by damithc** [comment]
For a first timer, the best place to start is the Contributor Orientation Guide :-) 
https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true

**Comment by Siddhant085** [comment]
I did everything mentioned in the Contribution Orientation Guide and was suggested to start solving issues. So I solved the issue but I am confused how to merge it with the main project

**Comment by LowWeiLin** [comment]
@Siddhant085 Hi, you will have to wait for the pull request to be reviewed, before the reviewer merges it into the master branch.
The process can be found here: https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md 

Also, do try to get the tests to pass, you will need to ensure that they pass for more involved issues.

**Comment by Siddhant085** [comment]
I am sorry for not getting the issue assigned to me before attempting to solve it. I solved the test cases and now I am getting only 4 failures.
