### ISSUE TITLE
Allow creating entities with specific modified or created dates

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#2939]
For entities containing created dates or modified dates, there should be a constructor that accepts specific dates. 

For example, in StudentProfile, there should be a constructor to create a StudentProfile while specifying the modifiedDate, and also another constructor to create a StudentProfile without specifying the date. For the constructor that does not accept a specific date as input, it will pass the current date while calling the other constructor.

**Comment by damithc** [comment]
This can be done on a 'as needed' basis. closing for now.
