### ISSUE TITLE
Some comments don't follow the visibility of the question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2949]
some comments seem to have some visibility options unticked, although the default should be all ticked. I'm not sure the problem happened when I added the comment or when I edited it.

**Comment by damithc** [comment]
@franklingu can you have a look at this. We need a quick fix because this concerns privacy

**Comment by franklingu** [comment]
Okay. Got that

**Comment by franklingu** [comment]
yes. the visibility options are not rendered after ajax returned from server. when edit the comment without reloading, all those visibility options are considered "unchecked"

**Comment by damithc** [comment]
Can fix quickly?

**Comment by franklingu** [comment]
but the "instruction" is telling the user to reload first. if reload the page first and then edit, then it will be fine. should not be hard to fix even without applying the hack. not sure if can finish before friday though

**Comment by damithc** [comment]
I never saw that instruction. Others are unlikely to see it either. Try to
fix, if not by Friday, over the weekend at least.

**Comment by franklingu** [comment]
actually i will be having FB hackathon this weekend. But i will try my best :P
