### ISSUE TITLE
instructor: can delete a specific response

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2950]
Sometimes students submit useless responses. e.g. Answering questions with "nill" replies when they were supposed to submit responses only if they had something to say. These responses pollute the reports. It is good if the instructor can delete such responses

**Comment by Siddhant085** [comment]
Can I work on this issue?

**Comment by LowWeiLin** [comment]
@damithc is this issue still valid? Instructors can "delete" by moderating a student's responses.

**Comment by damithc** [comment]
I see. In that case, we don't need this. Perhaps add a 'moderate' link in all result views? @kanghj Could you add a separate issue for that?
