### ISSUE TITLE
instructorFeedbacksPage - rename 'Course' --> 'Course ID'

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2955]
The dropdown when adding a session contains course ids, but the label is "Course"
Renaming the label/including the course names in the dropdown might make it clearer.

Other places in teammates may have this issue as well.

![image](https://cloud.githubusercontent.com/assets/3910365/6036373/4ba2edb2-ac7f-11e4-9800-507fbcde8e80.png)

**Comment by arvind-kalyan** [comment]
Hello, Can I give this a try?

**Comment by arvind-kalyan** [comment]
starting issue
