### ISSUE TITLE
InstructorFeedbackResultsPage: Incorrect function logic

### ISSUE THREAD

**Issue by rcyq** [TEAMMATES/repo#2956]
The function, verifyAllResultsPanelBodyVisibility, below does not obtain the DOM elements correctly.
".panel-heading+.panel-body" is invalid and the retrieved webElement colection is always empty.
Therefore, the loop will always be skipped. Thus, the function always return true.

I discovered this when I was running InstructorFeedbackResultPageUiTest where my Javascript was running slower and the verification of the collapsed/expanded panels always fail.

```
public boolean verifyAllResultsPanelBodyVisibility(boolean visible){
        for(WebElement e : browser.driver.findElements(By.cssSelector(".panel-heading+.panel-body"))){
            if(e.isDisplayed() != visible){
                return false;
            }
        }
        return true;
    }

**Comment by damithc** [comment]
@rcyq can fix?

**Comment by rcyq** [comment]
Ok I wiil attempt this issue
