### ISSUE TITLE
InstructorFeedbackResultsPage responseCommentTable: some names are missing for checkboxes

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/repo#2962]
e.g. 

```<input type=".." class="..." value="...">```
but the name is missing for at least inputs in last 2 trs.

**Comment by damithc** [comment]
title not very clear :-p

**Comment by damithc** [comment]
@franklingu can you describe this issue a bit more?

**Comment by franklingu** [comment]
it is in the code. although values are set but some checkboxes do not have names, which is not good and potentially harmful--I am not sure if this is affecting how the system is behaving now or not

**Comment by damithc** [comment]
May be edit the issue description to explain what this issue is about? Post some sample code if needed. Any developer should be able to understand what the issue is about by reading the issue description.

**Comment by franklingu** [comment]
this issue does not cause any trouble for the system for now. however, it is a potential harm in case some time later we do not use hidden inputs but checkboxes later directly
