### ISSUE TITLE
studentFeedbackSubmitSave takes too long

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2975]
This seem to have room for improvement

**Comment by LowWeiLin** [comment]
For each question on the page, the (same) StudentAttributes and InstructorAttributes of the current user are read from the database. For questions to team members, the team members are also read from database for every question that needs it.

We could change the code to read once and pass the required data as parameters.

I think this (reading data repeatedly) is a fairly common problem across all the actions/pages, and we might want to look into a system to cache data (action/logic/db level?) such that the same data is only read once per request.

**Comment by damithc** [comment]
Yes, we need mass reading methods.
In my case, I had only one question in my session and I was supposed to
give feedback to all students (250). I typed one response and saved it,
which took a long time.

**Comment by LowWeiLin** [comment]
Oh, sorry i was looking at FeedbackSubmissionEditPageAction.
The save action seems to be even slower. Looking into it.

**Comment by LowWeiLin** [comment]
The problem seems to be that for every possible response, the (same) feedback question attributes is being read from db.
