### ISSUE TITLE
Some tutors see all students while some see only students in the section

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2981]
These two tutors have similar settings. When submitting responses for students, one can see all students while the other sees only students in his section.
![image](https://cloud.githubusercontent.com/assets/1673303/6146472/0a37f7f6-b228-11e4-861c-baa5987d8caf.png)

![image](https://cloud.githubusercontent.com/assets/1673303/6146512/7cc253b6-b228-11e4-93fd-23c407cbd04c.png)

**Comment by franklingu** [comment]
what is the recipient for the question? is it like team, team members, self or team members and self? cause like instructors, students, or "NONE" as general will disable checking of access

**Comment by damithc** [comment]
Recipient: Students of the course
Giver: Instructors

**Comment by franklingu** [comment]
if the recipients are students of the course, the access control feature
will not function currently

```java
boolean needCheckPrivilege = !(question.recipientType ==
FeedbackParticipantType.NONE ||
                                    question.recipientType ==
FeedbackParticipantType.INSTRUCTORS ||
                                            question.recipientType ==
FeedbackParticipantType.STUDENTS);
```




Gu Junchao
Major in Computer Engineering, National University of Singapore
Primary Email: *franklingujunchao@gmail.com <franklingujunchao@gmail.com>*
NUS Email: *A0105750@nus.edu.sg <A0105750@nus.edu.sg>*
