### ISSUE TITLE
instructorCourseEditPage when saving instructors, edit.js will auto check off all course-level priviliges, give people an illusion that courseLevel settings are not saved in the database

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/repo#2984]

**Comment by franklingu** [comment]
@damithc , this is the issue I was talking about in the email. basically the javascript in that page is unticking all checkboxes when it comes to costom because of a bug--the normal behavior should be that only when switch to custom from another role then we uncheck them--so as you pointed, some instructors are given the wrong priviliges before, the course level settings are there but shown to Chirs as everything in course level is unchecked. by edit the settings again, user priviliges will be updated to all unchecked.

**Comment by damithc** [comment]
Ok, at least we know what the problem is. Lets fix quickly.
