### ISSUE TITLE
only emails of the 'not submitted' students shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2987]
![image](https://cloud.githubusercontent.com/assets/1673303/6197842/1ea38172-b428-11e4-851c-e6a8d4c57540.png)

**Comment by damithc** [comment]
@rcyq could you look into this?

**Comment by rcyq** [comment]
Ok I will look into this.
Just to clarify, do I need to cater for instructors as well? For example, not submitted instructors.

**Comment by damithc** [comment]
Yes. Including instructors.

**Comment by damithc** [comment]
How come in this session it is emails only? In other sessions it is showing
team and name.

**Comment by rcyq** [comment]
May I check with you which view is showing the screenshot above?
I have checked all jsp files for instructors, Team & Student Name columns will always be shown.

**Comment by damithc** [comment]
Check the results of the 'CE code review' session in CS2103

**Comment by damithc** [comment]
Any updates? It is strange that some sessions show emails only while others show names and team.

**Comment by rcyq** [comment]
The issue is discovered in the ajax call when feedback result is too large.
Currently, displaying of team name and student name columns are done in jsp.
However, when feedback result is too large, the data returned by the ajax call is not being processed correctly.

**Comment by damithc** [comment]
Needs fixing soon. The feature is more important for large classes than small ones. @imouto1994 is there a way to avoid duplication here?

**Comment by rcyq** [comment]
I am able to do a quick fix by preprocessing the emails before printing them out.

**Comment by damithc** [comment]
Let's wait 1 day to see if Bui can suggest a better way.

**Comment by imouto1994** [comment]
To avoid duplication, we can change the original AJAX request into AJAX request for JSP of the results page and extract data from it. 
To avoid redundant call for unneccesary data apart from the response rate, we can use the one of the original requests with some modifications. 
I can work on it if you need it fixed soon :)

**Comment by damithc** [comment]
Bui, you can have a go at it since you have some experience with similar
work before. It's good enough if we have a fix a couple of days after CNY
holidays.
