### ISSUE TITLE
student view of contribution question results: use a darker blue for panel heading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2996]
We use dark blue for things worthy of more attention. This one should be the default dark blue.
![image](https://cloud.githubusercontent.com/assets/1673303/6210786/01143d94-b60e-11e4-8bf6-cf2c45a0568a.png)

**Comment by arvind-kalyan** [comment]
Hello, do you mean to say that we should modify the heading  (here "Comparison of work distribution") to a darker blue color?

**Comment by damithc** [comment]
Yes, the same dark blue we use in other places.

**Comment by arvind-kalyan** [comment]
Okay. Can I try this one?

**Comment by damithc** [comment]
Sure Arvind. @kanghj can you review this one too?

**Comment by arvind-kalyan** [comment]
Thank-you sir!

**Comment by arvind-kalyan** [comment]
I have a small confusion. Do I have to change the color of text (here "Comparison of work distribution" ) to default dark blue or change the color of the panel to the default blue and the heading text color to white (like the pic below)?
![example](https://cloud.githubusercontent.com/assets/5078299/6265855/b842638c-b858-11e4-88f0-9372670ddf9f.PNG)

**Comment by damithc** [comment]
Like the pic :+1:

**Comment by arvind-kalyan** [comment]
The encircled in the pic below should be default dark blue, correct?
![studentfeedbackresults](https://cloud.githubusercontent.com/assets/5078299/6286938/09bb9d34-b933-11e4-9420-d76bfc5372ff.JPG)
