### ISSUE TITLE
adding an SMS updates/alerts feature

### ISSUE THREAD

**Issue by dg711** [TEAMMATES/repo#2998]
a feature to send  SMS  updates to the users regarding regarding deadline events and other related Alert messages.For example , Students who haven't submitted their submitted their feedbacks can be alerted about that on the deadline day .
There can be far more uses of this feature .
This can be achieved using Plivo SMS API on Google App Engine . To know about it : https://www.plivo.com/sms-api/

**Comment by visithamanujaya** [comment]
I like to work on this

**Comment by Chandrakant4993** [comment]
Can I Solve This issue

**Comment by damithc** [comment]
Not a priority for us at the moment. Moving to zero priority. We'll not do this until the priority is raised again.
