### ISSUE TITLE
Regenerate all html files in God mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3006]
@thyageshm if we regenerate all html files under god mode, would it prevent future god mode runs creating unrelated diffs?

**Comment by thyageshm** [comment]
Mostly yes, the only issue will be the spacing in the page. If anyone edits a browser test page manually, there will be an unrelated diff for that page the next time godmode is run. Other than that if we all use only godmode to fix browser tests, there will be no unrelated diffs

**Comment by damithc** [comment]
I don't mind using God mode for all fixes if it is easy to use and changes
only the intended parts.

**Comment by thyageshm** [comment]
Sir, if the contributors, look at AppPage -> processPageSourceForGodMode(content) method and understand it, I believe it should be safe for them to use. The problem arises when, lets say, there is a new date format that we intend to use, then godmode has to be updated to handle it (OR they manually change it.) But in the current situation, godmode covers all cases

**Comment by damithc** [comment]
For now, shall we migrate all html files to be godmode compatible. That
will at least reduce unnecessary changes in the fixes done by core
developers. Those are the one that contain big changes anyway. After that,
let's work toward making godmode the default.

**Comment by thyageshm** [comment]
ok! I would really like to request @LowWeiLin  to run the entire suite with godmode on ;-)

**Comment by LowWeiLin** [comment]
I can do that, but this may cause conflicts with the currently pending pull requests.

**Comment by damithc** [comment]
We can wait till some of the more invasive pull requests are merged. Do it when you think it is a good time.

**Comment by thyageshm** [comment]
Also @LowWeiLin please wait for the pull requests associated with #2431 as I have made a small change to Godmode on that one inline with this request.

**Comment by damithc** [comment]
Avoid doing unrelated things in a single pull request. If you notice a
minor improvement you want to do, you can do it as a separate pull request
(if multiple commits) or in the master itself (if it is a single commit).

**Comment by thyageshm** [comment]
Haha sure sir, but I needed that one to fix the browser tests in that issue. I guess I will undo the changes once I am done fixing the tests and then put it back in a separate issue

**Comment by thyageshm** [comment]
ok how about I take ownership of this issue, add the extra bit into Godmode and then change the ownership to WeiLin?

**Comment by damithc** [comment]
Sure.

**Comment by thyageshm** [comment]
I have pushed the changes I wanted to make @LowWeiLin

**Comment by LowWeiLin** [comment]
@thyageshm Do I still wait for #2431?

**Comment by thyageshm** [comment]
@LowWeiLin I guess not, I have added the feature to all the necessary pages, but fixing the tests is a big headache haha. actually I was going to ask if you could help me sometime tomorrow. If I could meet you at NUS or smth

**Comment by thyageshm** [comment]
just the results page :-P
