### ISSUE TITLE
FeedbackRubricQuestionUiTest failing on line 71

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3008]
The line <code>instructorResultsPage.verifyHtmlMainContent("/instructorFeedbackResultsPageRubricQuestionView.html");</code> is currently failing on master, due to some changes at the bottom of the instructor's results page.

**Comment by damithc** [comment]
@imouto1994 could this be due to the recent #3005 ?

**Comment by imouto1994** [comment]
Yes, I do not know that results page is also tested in other test files!
Will update it asap ! :)

**Comment by damithc** [comment]
If the segment of the html file causing the failure is not relevant to the failing test, may be we can use a `{*}` there?

**Comment by imouto1994** [comment]
Yes, but it may be removed in the future if someone use 'God Mode' when he makes some changes which requires to update this test case

**Comment by damithc** [comment]
If Godmode replaced a `{*}` with text, it should be easy to spot and revert manually, until Godmode is clever enough to respect `{*}`.

**Comment by imouto1994** [comment]
Ok, then I will replace this segment with `{*}` :)
