### ISSUE TITLE
instructor response comments: wrong user type shown in visibility options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3025]
There is some mismatch here
![image](https://cloud.githubusercontent.com/assets/1673303/6424704/de9bf34e-bf3e-11e4-8ec8-753c9fccd756.png)

![image](https://cloud.githubusercontent.com/assets/1673303/6424701/c26a42f2-bf3e-11e4-9bcc-20d45da083bc.png)

**Comment by damithc** [comment]
@kai33 FYI as well

**Comment by damithc** [comment]
Here's the situation after reloading the page. Something is really messed up. :-1: 
![image](https://cloud.githubusercontent.com/assets/1673303/6424756/28126b2e-bf40-11e4-9ba6-559ee7ecf0e2.png)

**Comment by damithc** [comment]
Note that I edited the comment without reloading the page.

**Comment by franklingu** [comment]
so the second is when adding a new comment, or add the comment and edit the added comment without reloading? the third one is after reloading?

**Comment by kai33** [comment]
oh, miss the row for 'other students' in feedbackResponseComments.js

**Comment by kai33** [comment]
after add the row for 'other students' in feedbackResponseComments.js,
it will be complete (total 6 rows, now only 5).
![screen shot 2014-07-09 at 4 45 38 pm](https://cloud.githubusercontent.com/assets/3591355/6424945/9a18350a-bf4a-11e4-82ff-eba1602c7f98.png)

**Comment by franklingu** [comment]
OK. did not know there were 6 of them. but I think here is talking about 2 mismatches?

**Comment by kai33** [comment]
yes, the mismatch is no 'other students' row

**Comment by franklingu** [comment]
"but I think here is talking about 2 mismatches?" more explanation? @damithc

**Comment by damithc** [comment]
Yes, two issues.
After editing the comment, the visibilities shown are incorrect. Some rows
missing.
After reloading the page (after the edit), it appears that visibilities
have not been saved. I remember this was reported before and supposed to
have been fixed.

**Comment by franklingu** [comment]
for first issue, yes, other students row is indeed missing. it was a bug with previous fix.
for second issue, cannot replicate it.

**Comment by kai33** [comment]
re-produce by:
1. in insFeedbackResultPage, add a comment (dont refresh)
2. edit this comment's visibility and submit
3. refresh, can see its visibility gone.

**Comment by kai33** [comment]
Root cause:
after add a new response comment, the added form misses 2 hidden inputs for visibility options. 
<input type="hidden" name="showresponsecommentsto" value="yyyyyy">
<input type="hidden" name="showresponsegiverto" value="xxxxxx">

The fix can be:
add these 2 inputs,
and also need to register the checkbox's checked event for relative visibility options

**Comment by franklingu** [comment]
so this is related to #2962 in the end?

**Comment by franklingu** [comment]
I see now. those two hidden fields are the decisive ones in the end. :(

**Comment by franklingu** [comment]
OK. the register of event handler to checkboxes are not done after new comment is created.
