### ISSUE TITLE
instructor view responses: show 'no response' panels in 'low importance' colors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3026]
Use light blue for panel heading and gray for text?
![image](https://cloud.githubusercontent.com/assets/1673303/6424761/c2ef1962-bf40-11e4-8901-994a9da5d10c.png)

**Comment by JosephineKwa** [comment]
I would like to work on this issue

**Comment by damithc** [comment]
Not hard enough for you @JosephineKwa . I've suggested #3028 for you.

**Comment by wkurniawan07** [comment]
I'd like to be assigned for this. I can define a new set of CSS classes (say, panel-no-response, panel-no-response>panel-heading, ...) and equip them to the panels in question.

**Comment by wkurniawan07** [comment]
Submitted pull request: #3176
The changes made are illustrated there.
Looking forward to the review/merge! :D
