### ISSUE TITLE
Typo in devman.html

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/repo#3027]
Under the Design, UI section, in Request Flow:
 
7) ...creates a ShowPageResult object by encolosing the PageData object...
"encolosing" should be enclosing.

8) ControllerServlert "sends" the result....
"ControllerServlert" should be "ControllerServlet".

"Things to note" part, there is a sentence that says "Server processes the request separately (creates a ShowPageResult object but and a PageData object) and returns the 'courses' page." 
I think it should be "but no PageData object" instead.

**Comment by halfdreamer** [comment]
i can correct these errorrs..please assign it to me...

**Comment by LowWeiLin** [comment]
@halfdreamer Good to see you have managed to get most of the tests passing(hopefully all of them). Go ahead and address this issue and create a pull request for it.
