### ISSUE TITLE
instructor session results, 'by question view': add the ability to view the profile photo

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3028]
Currently, in other views (e.g. 'by giver'), the profile photo can be viewed by hovering over the name.

**Comment by damithc** [comment]
@JosephineKwa can you give this one a try?
@thyageshm can you review?

**Comment by JosephineKwa** [comment]
Ok sure! I'll try this one out.

**Comment by thyageshm** [comment]
sure sir
