### ISSUE TITLE
AllAccessControlUiTest failing at line 303

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3029]
As per title

@thyageshm related to #3012?

![image](https://cloud.githubusercontent.com/assets/3910365/6426301/ec778dca-bf8e-11e4-852c-5a321e510d92.png)

**Comment by thyageshm** [comment]
will send in a fix tonight

**Comment by thyageshm** [comment]
fixed and merged to master. all browser tests ran and passed
