### ISSUE TITLE
AdminHomePageUiTest failing due to ajax-loader gif

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3030]
The test doesn't pass even if run again multiple times.

Maybe we can add a wait while testing or ignore these in verifyHtml?

![image](https://cloud.githubusercontent.com/assets/3910365/6426314/7c4de750-bf8f-11e4-8b6a-507aa3126f0f.png)

**Comment by wkurniawan07** [comment]
I know this issue has been assigned, but can I jump the queue and solve this? I have to admit, this has been getting on my nerves.

**Comment by damithc** [comment]
Go ahead @wkurniawan07 
@ymoctavia can review.
