### ISSUE TITLE
Change misleading comment in test.template.properties

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3037]
On line 40, it says

<code># The values given below will work for the dev server.</code>

When in fact, the default values need to be changed for GodModeTest to pass.

**Comment by julian1990** [comment]
Hi, HJ, Can you assign this issue to me?
Actually I complete the Phase A-D, and met this problem when I ran test suit.
@LowWeiLin has already told me solution:
'go to test.properties and change ALL the accounts by appending to the back of it e.g. alice.tmms -> alice.tmms.asd'
After doing this step, I have passed all test cases already.

**Comment by kanghj** [comment]
Hi, you will have to accept the github invitation from @LowWeiLin first.

**Comment by julian1990** [comment]
@kanghj Ah, I see. I'll try to contact @LowWeiLin in my teammates-contributors thread again.

**Comment by LowWeiLin** [comment]
@julian1990 The invitation has already been sent. Just waiting for you to accept.

**Comment by julian1990** [comment]
@LowWeiLin Oops, I'm really sorry. I made a mistake. I have checked another e-mail address:-( ...
@kanghj SInce I've accepted the invitation, Can you assign this issue to me?

**Comment by julian1990** [comment]
starting issue
