### ISSUE TITLE
Can see response comments in instrSearch & instrFeedbackResultsPage but not in instrCommentsPage

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/repo#3045]
the access control in
InstructorFeedbackResponseCommentsLoadAction &
InstructorSearchPageAction is not sync

**Comment by wkurniawan07** [comment]
Does this still happen?

**Comment by kai33** [comment]
looks like access logic has been changed,
now:
1. I can see comments from instructor in TeammatesV4 site (15 Aug), of page instructorFeedbackResultsPage.
2. but I cannot see this comment in instructorCommentsPage and instructorSearchPage.

**Comment by damithc** [comment]
Is it a bug that needs fixing before we release?

**Comment by kai33** [comment]
it should be fixed. currently it only affects role Tutor

**Comment by damithc** [comment]
Who's the most suitable person to take this issue? @wkurniawan07 @taniach @bamboo3250 @JosephineKwa or someone else?

**Comment by kanghj** [comment]
The teammatesv4 site should still be using the old version of the jsp (before migrating to jstl), so it's possible that now this behaviour is different on master. Using an instructor with role tutor, I am able to see response comments on the results page, comments page and search page.

**Comment by damithc** [comment]
That's right, the version visible to public is the jsp version released around June. You can try the new version from 5-50-dot-teammatesv4...

**Comment by kai33** [comment]
my access settings in teammatesv4:
1. access-level: custom
2. general: uncheck all
3. section: can view my tutorial group's responses and response comments.
4. sessions table: can view target session's responses and comments.

**Comment by wkurniawan07** [comment]
I used @kai33's configuration and the said issue doesn't occur anymore. @kanghj can you also confirm?

**Comment by kai33** [comment]
just tried out and have a look in the access control logic, it looks good now.
