### ISSUE TITLE
prompt alert message when a user abandons an incomplete form 

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#3051]
For eg. , If a user is the middle of inputting the details for the new session creation or course creation , he/she should be alerted of the incomplete form on the current webpage when they request another webpage or reload the same webpage .

**Comment by damithc** [comment]
If the user loads another page by mistake, he/she can go back to the previous form using the back button? Is there a scenario where that wouldn't work?

**Comment by drunken-saint** [comment]
No , I didn't find any scenario where it wouldn't work . Its just that, I have seen other websites using such feature . Anyways ,the issue can be closed now . I would report incase I come across such scenarios in the future .

**Comment by damithc** [comment]
OK, i'll close it for now. We can reopen if there is a change in circumstances. Thanks for posting the issue and following it up @drunken-saint
