### ISSUE TITLE
adminAccountManagement.css isn't referenced in adminAccountManagement.jsp.

### ISSUE THREAD

**Issue by karan173** [TEAMMATES/repo#3052]
The file adminAccountManagement.css isn't referenced in adminAccountManagement.jsp. Also see [link](https://groups.google.com/forum/#!topic/teammates-contributors/kVHhpDI-fAs)

**Comment by damithc** [comment]
@ymoctavia for your verification.

**Comment by ymoctavia** [comment]
Yes, it is not referenced in the jsp page. We can delete it.

**Comment by karan173** [comment]
Can I be assigned this issue?

**Comment by karan173** [comment]
starting issue
