### ISSUE TITLE
instructor session unpublish confirmation dialog: evaluation --> session

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#3077]
Since the instructor session publish confirmation dialogs' message has been changed to  evaluation --> session in the issue #2929, the messsage in the unpublish version should also be changed .

**Comment by wkurniawan07** [comment]
can I give this a shot?

**Comment by kanghj** [comment]
Yes, go ahead. I will send you the invitation, you have to accept it before I can assign you this issue.

**Comment by wkurniawan07** [comment]
starting issue! sorry I just finally managed to find the time to work now ^_^

**Comment by wkurniawan07** [comment]
fixed it. the tweak is rather simple though, just modifying one word in \src\main\webapp\js\instructor.js.

Screenshot of change:
![changess](https://cloud.githubusercontent.com/assets/7261051/6645136/e1dfb7be-c9f4-11e4-9750-b7b0b2063126.png)

Dev green also reached:
![devgreen](https://cloud.githubusercontent.com/assets/7261051/6645142/f32364f8-c9f4-11e4-93b4-e7f733838fbd.png)

And here's the pull request: #3113
Looking forward to the review/merge!
