### ISSUE TITLE
studentFeedbackSubmissionEdit : No form validation occurs on submit action 

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#3083]
A student can submit blank answers in their feedback submission . There is a requirement for a  validate function to be added to the javascript to check for that .

**Comment by kanghj** [comment]
Can you provide more information about this? What do you mean by no form validation occurs?

**Comment by LowWeiLin** [comment]
Blank answers are allowed.

**Comment by drunken-saint** [comment]
Ok. Didn't know about that .
