### ISSUE TITLE
studentCourseDetailsPage : the hyperlinks don't lead any profile

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#3084]
studentCourseDetailsPage : the hyperlinks don't lead any profile . they just lead to a new blank browser window . If that feature hasn't been added yet , then we should use some other style/font for displaying the names of the students' teammates and also the instructor profile

**Comment by damithc** [comment]
Could you post a screenshot of the link you clicked and the browser window?

**Comment by drunken-saint** [comment]
![Uploading Screenshot (78).png . . .]()

**Comment by drunken-saint** [comment]
![screenshot 78](https://cloud.githubusercontent.com/assets/7551036/6595970/9bea4aac-c815-11e4-862a-b2e5016090b8.png)

**Comment by LowWeiLin** [comment]
The current action is a mailto to the student's email. It seems fine to me.
@damithc Should it be changed to point to the student's profile?

**Comment by damithc** [comment]
OK for now. At the moment, students cannot view profiles of other students.
