### ISSUE TITLE
Instructor: Add a courseId in the message shown in the confirmation dialog of 'delete student' button

### ISSUE THREAD

**Issue by rcyq** [TEAMMATES/repo#3089]
In instructorCourseDetails.js, the message in the confirmation dialog of 'delete student' button is with the format:

```
"Are you sure you want to remove " + studentName + " from " + "the course?"
```
The message should be formatted in the same way as the confirmation dialog in the other js files (instructorSearch.js and instructorStudentList.js)

```
"Are you sure you want to remove " + studentName + " from " + "the course " + courseId + "?"

**Comment by yuqingw** [comment]
Hi can I be assigned to fix this?

**Comment by LowWeiLin** [comment]
@yuqingw Sent you an invitation to the contributors team.

**Comment by yuqingw** [comment]
@LowWeiLin Thanks! I've accepted the invitation

**Comment by yuqingw** [comment]
Starting issue

**Comment by zulrich91** [comment]
I want to work on this issue .

**Comment by kanghj** [comment]
@zulrich91, this has already been assigned. Look for another issue.

**Comment by zulrich91** [comment]
Ok , thank you for replying emmediately .

**Comment by zulrich91** [comment]
Meanwhile i already went ahead and solved the isssue already , just waiting
for approval.
But nevertheless i will look for an unassigned issue !!!


On Fri, Mar 13, 2015 at 3:38 PM, Kang Hong Jin <notifications@github.com>
wrote:

> @zulrich91 <https://github.com/zulrich91>, this has already been
> assigned. Look for another issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/issues/3089#issuecomment-79000520>.
>



-- 
ulrich tchuenkam
