### ISSUE TITLE
Duplicated definitions of '#navbar li a' and '#navbar li a:hover' in teammates.css

### ISSUE THREAD

**Issue by tangzijian** [TEAMMATES/repo#3093]
Can I be assigned to this issue for first time contributors?
Issue screen shot:
![screen shot 2015-03-11 at 9 40 58 pm](https://cloud.githubusercontent.com/assets/4153394/6597414/7ebf8c0e-c837-11e4-9927-2b7ac795082d.png)

**Comment by tangzijian** [comment]
Can I be assigned to fix this issue?

**Comment by LowWeiLin** [comment]
Hi, you need to accept the invitation to the contributor team.

**Comment by tangzijian** [comment]
Hi, WeiLin,
Do I have the right to push to committer repo? Or push the fix to my own fork?

**Comment by damithc** [comment]
What change do you propose? The `text-decoration` attribute is not the same.

**Comment by LowWeiLin** [comment]
You need to work on your fork and pull request from there.

**Comment by damithc** [comment]
Ok, got what you meant.
