### ISSUE TITLE
Add severe log in Action.java

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3100]
Place a log: log.severe("TEAMMATES accessed using old join link")
in branch where legacy REG key is being used.

Related to #3011, #3081

**Comment by jarvis57** [comment]
hi, I completed the orientation tasks A-D. Can I be assigned to this issue?

**Comment by vamshi-s** [comment]
@LowWeiLin Please can you assign this task to me. I already worked on the earlier issue #3011 , but it is been under review.

**Comment by jarvis57** [comment]
starting issue.
