### ISSUE TITLE
Write a linux script for runtests enabling users to run the tests from linux terminal 

### ISSUE THREAD

**Issue by atishay100495** [TEAMMATES/repo#3104]

**Comment by atishay100495** [comment]
I've already finished working on the issue. Going to create a pull request.

**Comment by atishay100495** [comment]
I've created a pull request for the issue. Please review and push the changes to master.
The steps to run the script are as follows:
1. Carry out all the steps mentioned in the wiki for settingUp.
2. Make sure your teammates server is running.
3. If the script is not already an executable, change its permission by : chmod +x runtests.sh
4. Run the command: ./runtests.sh Google_App_Engine_Path Teammates_Repo_Path (the procedure is similar to runtests.bat)

**Comment by kai33** [comment]
Thank u for your contribution, it's really useful! : )
