### ISSUE TITLE
[Testing] Xpaths should be written in separate file using other reg ex instead of id.

### ISSUE THREAD

**Issue by suhas355** [TEAMMATES/repo#3109]
1. In order to reduce redundancy, It would be easy to write All xpaths in a common csv
in ex:  SendEmailNotificationButton, //*[@id=\"frameBodyWrapper\"]/div[5]/div[1]/div/a

and use it in page action and hence Xpath layer will be isolated from the Pageaction(logic) layer

2. Since in Xpath Id might change it would be good if use class and relative pointers such as siblings instead of absolute path

**Comment by damithc** [comment]
Currently, this information is captured in the respective `*Page` class. We'll stick with that approach for now. Can reopen later if that approach gets too cumbersome.
