### ISSUE TITLE
Cannot click MCQ options when there are more than 10 team members

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3110]
There is a course with more than 10 team members. An MCQ question requires evaluating all team members. Options cannot be clicked for the 11th member onwards. Tried both Chrome and IE.
![image](https://cloud.githubusercontent.com/assets/1673303/6632950/4b76ce4a-c97a-11e4-89e2-9e0d528ce98b.png)

**Comment by damithc** [comment]
@LowWeiLin @kanghj could you look into this? It affects an ongoing session.

**Comment by LowWeiLin** [comment]
Related to #2958. Looking into it now.

**Comment by damithc** [comment]
Yes, that seems to be the cause. Rolled back to V5.37 for the time being.

**Comment by damithc** [comment]
If it is not easy to fix quickly, we can revert the offending commit.

**Comment by LowWeiLin** [comment]
I submitted a pull request that fixes it already.
