### ISSUE TITLE
 feedbackSubmissionEdit.js: Check and change jQuery selectors using partial match to exact match

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3112]
For example, <code>var dropdown = $("[name^='responsetext-" + qnNum + "-" + k + "']");</code>

If we have an element responsetext-1-10', it will be matched by both 'responsetext-1-1' and 'responsetext-1-10'. This may cause unexpected effects when we bind a callback function to the selector, such as in #3110.

**Comment by supunharsha** [comment]
Hi,
Can i start working on this issue?

**Comment by bamboo3250** [comment]
It seems that the assignee dropped this issue. Can I work on it?

**Comment by kanghj** [comment]
Yes, I think you can since @supunharsha has not responded for some time. You can submit a pull request when you are done, but if @supunharsha comes back and complete his pull request earlier than you, then I will just merge his.
