### ISSUE TITLE
Instructor Unable to comment on all students in a given course.

### ISSUE THREAD

**Issue by vamshi-s** [TEAMMATES/repo#3115]
@damithc 
Please Check this image for Error Message. 

![error1](https://cloud.githubusercontent.com/assets/11355301/6649872/2a4805ec-ca1d-11e4-811a-5475ceff1466.png)
![error2](https://cloud.githubusercontent.com/assets/11355301/6649871/2a46e23e-ca1d-11e4-9046-755d36d13c76.png)

**Comment by LowWeiLin** [comment]
@kai33

**Comment by kai33** [comment]
Thank u for submitting this issue, it's really helpful & useful for us : )

**Comment by vamshi-s** [comment]
@LowWeiLin @kai33  I was interested to work  on this issue. But its done :)
