### ISSUE TITLE
process.md: Remove remote myfork from Step 3 of fixing issues

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3116]
As the repository is cloned from the contributor's fork, the default remote _origin_ is already the contributor's forked repository. There is no need for the contributor to add his/her own fork as another remote _myfork_.

**Comment by visithamanujaya** [comment]
i can do this

**Comment by kanghj** [comment]
@visithamanujaya, I have already sent you the invitation to join us as a contributor, you need to accept it before I can assign this to you on github.

**Comment by EgbeEugene** [comment]
Please can i work on this ?

**Comment by kanghj** [comment]
I will assign this to @visithamanujaya since he requested for this first. @EgbeEugene, sorry, you need to look for another issue.

**Comment by yj-soh** [comment]
Considering there is no longer any need to be assigned and @visithamanujaya stayed silent for over a week about a change that was effectively deleting a line, I went ahead and worked on it.

In addition, process.md could use some updating. I am not entirely sure, but the newer versions of Git might require these changes.

This command might need to be changed to the one below.
```
git pull upstream
-> git pull upstream master
```
The above command currently gives the following error:
```
You asked to pull from the remote 'upstream', but did not specify a branch.
Because this is not the default configured remote for your current branch, you must specify a branch on the command line.
```

Also, regarding the following segment:
```
git pull upstream 
git merge master
```
As far as I know, the *pull* command should *merge* as well, so was it meant to be *fetch* instead?

**Comment by damithc** [comment]
Update the pull request to fix the extra problems you have mentioned @yj-soh
