### ISSUE TITLE
InstructorHomePage: remind all confirmation, change evaluations to feedback

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3117]
Send e-mails to remind students who have not submitted their evaluations for ...

Change to "evaluations" to "feedback".

**Comment by LowWeiLin** [comment]
Similar to #3077

**Comment by saav** [comment]
Can I take up this issue ?

**Comment by LowWeiLin** [comment]
@saav Sent you an invite. Will assign you after you accept.

**Comment by saav** [comment]
@LowWeiLin Accepted the invitation !!

**Comment by saav** [comment]
starting issue
