### ISSUE TITLE
InstructorHomePage: change delete course confirmation message

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3118]
Are you sure you want to delete the course: .... ?
This operation will delete all students<b>, feedback sessions</b> and evaluations in this course.
All instructors of this course will not be able to access it hereafter as well.

**Comment by damithc** [comment]
'feedback sessions and evaluations'  can be shortened to 'sessions'

**Comment by Chinmay1412** [comment]
I want to work on this issue and want to know how to proceed.

**Comment by kanghj** [comment]
@Chinmay1412, I have sent you the invitation to join as a contributor, you need to accept it first before I can assign you this issue.

**Comment by supunharsha** [comment]
Hi 
Can i start working on this issue?

**Comment by LowWeiLin** [comment]
@supunharsha Look for harder issues. Each person should only do one issue labeled forFirstTImers

**Comment by Chinmay1412** [comment]
@kanghj, I cannot see any invitation. I did not get any notification.

**Comment by kanghj** [comment]
Looks like you have accepted the invitation already

**Comment by Chinmay1412** [comment]
@kanghj, Actually I was searching on github then after found a link of invitation in gmail.

**Comment by Chinmay1412** [comment]
@kanghj, Hello I found file "instructor.js". In that file, confirmation for deletion course message is present. Am I doing right?

**Comment by kanghj** [comment]
Yes, the confirmation message to change is in that file.
