### ISSUE TITLE
StudentHomePageUiTest fails on staging server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3120]
Fails at line `74         loginWithPersistenceProblem();` with "not a valid login page" error. Tried many times.

**Comment by thyageshm** [comment]
sir this test is passing on my devserver, with latest master

**Comment by damithc** [comment]
It passes on my devserver as well, but fails on staging server.

**Comment by damithc** [comment]
Failed a few times, but managed to pass eventually.
