### ISSUE TITLE
settingUp.md: Improve the instructions for getting join link for student login

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3131]
New contributors might get confused and think that they are supposed to search for the student from the instructor's search page. The instructions should make it clear that they should use the admin's search page. Also mention that instead of clicking on the student's name, which goes to  instructorStudentRecordsPage, they should click on the row to display a panel that contains the join link.

**Comment by zulrich91** [comment]
I don't understand what the solution to the issue should be . Please which file is concerned with this issue ?

**Comment by jp111** [comment]
@kanghj Please assign this task to me.

**Comment by kanghj** [comment]
@jp111, I have sent you the invitation to join TEAMMATES as a contributor, you should be able to find it in your email inbox.

**Comment by jp111** [comment]
I am now a contributor to the project. Can I now send a pull request referring to this issue?

**Comment by kanghj** [comment]
Yes, you can do so now.

**Comment by weaveranoop** [comment]
Hi Kanghj,
I have completed the orientation tasks. I am now looking for fixing some issues and contributing to Teammates. Could you please assign me to this issue?

Regards,
Anoop Shukla

**Comment by weaveranoop** [comment]
Hi kanghj,
I have completed the orientation tasks. I was looking for fixing some issues and contributing to Teammates. I have tried to contribute to this issue by improving the instructions. You can review that at the following link under the head 'Setting up the dev server' :
https://github.com/weaveranoop/repo/blob/tinker/devdocs/settingUp.md

**Comment by weaveranoop** [comment]
Hi kanghj,
I have completed the orientation tasks. I was looking for fixing some issues and contributing to Teammates. I have tried to contribute to this issue by improving the instructions. You can review that at the following link under the head 'Setting up the dev server' :
https://github.com/weaveranoop/repo/blob/tinker/devdocs/settingUp.md
Regards,
Anoop

**Comment by weaveranoop** [comment]
Hi kanghj,
I have completed the orientation tasks. I was looking for fixing some issues and contributing to Teammates. I have tried to contribute to this issue by improving the instructions. You can review that at the following link under the head 'Setting up the dev server' :
https://github.com/weaveranoop/repo/blob/tinker/devdocs/settingUp.md
Regards,
Anoop

**Comment by kanghj** [comment]
@weaveranoop, you need choose an issue which hasn't been assigned yet. Use this: https://github.com/TEAMMATES/repo/issues?q=is%3Aopen+is%3Aissue+label%3AforFirstTimers+no%3Aassignee
