### ISSUE TITLE
admin search: open the student record as co-owner

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3144]
When we click on the student name in search results, it opens the student record page. Currently, the page is opened under a randomly picked instructor account. It is better to open it under an instructor with co-owner privileges.

**Comment by tangzijian** [comment]
It seems like it doesn't pick an instructor at random, instead it picks an instructor with co-owner privileges in the method `findAvailableInstructorGoogleIdForCourse()`. below is a code snapshot.
![screen shot 2015-04-12 at 10 46 44 am](https://cloud.githubusercontent.com/assets/4153394/7104196/ceae4ed4-e101-11e4-92ef-63a6174a73f1.png)

**Comment by damithc** [comment]
I see. Can you do some manual testing to confirm?. If it always chooses a co-owner, we can close this issue.

**Comment by tangzijian** [comment]
@damithc It seems that the hash map in InstructorPrivileges does not contains any key such as 'Co-Owner' or 'Tutor'. So `instructor.isAllowedForPrivilege()` will always return false no matter the instructor has 'Co-owner' or 'Tutor' privileges. Am I supposed to fix this bug under this issue or a new issue?

**Comment by damithc** [comment]
You can open a new issue for that. Closing this one. @franklingu may be able to advise you on the new issue.
