### ISSUE TITLE
InstructorFeedbackResults, table to be copied to excel: can be beautified

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3150]
I am referring to this:
![emptyspace3](https://cloud.githubusercontent.com/assets/7261051/6693967/d37fd814-cd11-11e4-8c39-2e2ff4d9c15e.jpg)

While beautifying on the modal window is not that important, when copied to excel, the table will look exactly the same.
Example on how it looked not so good:
![emptyspace1](https://cloud.githubusercontent.com/assets/7261051/6694020/368ea372-cd12-11e4-83f1-301cf17d6f6d.jpg)

And especially here:
![emptyspace2](https://cloud.githubusercontent.com/assets/7261051/6694028/3bad031c-cd12-11e4-8755-c6f9bcd5db91.jpg)

Can I fix this if accepted as an issue?

**Comment by damithc** [comment]
This page is not meant for viewing. It is just for copy pasting into a spreadsheet. So the look and feel is not that important. Still, no harm if it can be done without much effort or risk of regressions.

**Comment by wkurniawan07** [comment]
The problem is not so much on the page itself. The last two screenshots up there are taken from the table *after* being copied to the excel, which really is the reason why I am bringing this up.
Nevertheless, since this is already accepted, I'd like to work on it.

**Comment by damithc** [comment]
OK, have a go at it then. :-)

**Comment by wkurniawan07** [comment]
Submitted pull request: #3163
The changes made are illustrated there.
Looking forward to the review/merge! :D
