### ISSUE TITLE
PageData: Wrong method documentation for "getInstructorFeedbackSessionActions:"

### ISSUE THREAD

**Issue by tangzijian** [TEAMMATES/repo#3154]
![screen shot 2015-03-18 at 5 43 09 pm](https://cloud.githubusercontent.com/assets/4153394/6706214/7b76b04a-cd96-11e4-9c9a-7d211a695552.png)

**Comment by kenhua-l** [comment]
Hi, 
Please let me try this.
Ken :)

**Comment by kenhua-l** [comment]
![screen shot 2015-04-02 at 1 32 25 pm](https://cloud.githubusercontent.com/assets/7554160/6958345/e7dea34e-d93c-11e4-8f14-ee9f0d89097f.png)

Hi!
Is this fine? 
Ken

**Comment by damithc** [comment]
A quick comment: Use 'feedback session' instead of 'Evaluation'

**Comment by kenhua-l** [comment]
![screen shot 2015-04-06 at 1 13 18 pm](https://cloud.githubusercontent.com/assets/7554160/7000773/d5b016e2-dc5e-11e4-9532-a374f1905db2.png)

Hi, 
I hope this is fine. :)
But I am a little confused on how to merge. I'll drop by this Wednesday for the weekly consultation.
Ken
