### ISSUE TITLE
Update the link to HTML style guide 

### ISSUE THREAD

**Issue by weaveranoop** [TEAMMATES/repo#3166]
This is the outdated link to the HTML guide : 
https://github.com/TEAMMATES/repo/blob/master/src/main/webapp/dev/htmlstyleguide.html

It needs updating in README.md and any other document where this link is given.

**Comment by damithc** [comment]
The link should be updated to https://docs.google.com/document/d/12PJYbQoqjK-0LzaUuguQ4kGE--eikCcHfwzZDGwFOJ0/pub?embedded=true
