### ISSUE TITLE
InstructorFeedbackResults, RQG/RGQ view: no response texts are not italicized

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3181]
As seen below, the text for "There are no responses ..." are italicized:
(GRQ/GQR view)
![3176_1](https://cloud.githubusercontent.com/assets/7261051/6763654/77e351f4-cfc1-11e4-817d-947b68a0c434.png)
(Question view)
![3176_2](https://cloud.githubusercontent.com/assets/7261051/6763655/7a3b21a2-cfc1-11e4-8db8-b37e011ca197.png)
However the convention doesn't seem to be followed in RQG/RGQ view...
![3176_3](https://cloud.githubusercontent.com/assets/7261051/6763661/aeebfe62-cfc1-11e4-8d63-ea0c593f3b80.png)

**Comment by wkurniawan07** [comment]
(btw, this should be for first timers)

**Comment by LowWeiLin** [comment]
This involves updating the tests, firstTimer issues usually don't involve updating tests.

**Comment by wkurniawan07** [comment]
ah, I see. true enough, it involves updating the tests :p
