### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing due to timeout

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3188]
![newissue](https://cloud.githubusercontent.com/assets/7261051/6800834/47e5b908-d25d-11e4-89cf-5b311671c6ea.png)
Happens very often, even when that one particular test is run *on its own*.
This is what the screen looks like when it timeout-ed:
![newissue_2](https://cloud.githubusercontent.com/assets/7261051/6800928/28628b1e-d25e-11e4-8f6c-4f3c85a12dc0.png)
One simple way to solve this is to let the thread sleep for longer time after adding a comment.

**Comment by damithc** [comment]
Is this the case where the comment icon appears 'clicked' but the comment
form doesn't appear?

**Comment by wkurniawan07** [comment]
Correct. It was as if the "add comment" button was pressed while the previous comment was still being published. And that's why letting the thread wait for longer actually solved it.

**Comment by damithc** [comment]
Go ahead and create a pull request for the fix :-)

**Comment by wkurniawan07** [comment]
One-liner fix :grin:
