### ISSUE TITLE
Infinite loop when editing NUMSCALE question

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#3193]
e.g. When a large number is entered into maximum value, the javascript in the page goes into infinite loop and the page stops responding.

**Comment by wkurniawan07** [comment]
tried to tweak this in my machine and solved it. it's not an infinite loop/the page stops responding. it's just that the large value took that damn long to process.
should I push the fix or give this to some other contributor? the fix is quite straightforward.

**Comment by LowWeiLin** [comment]
You will need to consider floating point precision in javascript for this issue. I believe that is why the current loop method is being used. A simple solution to this is to limit the maximum number that can be input, which will prevent overflow on the server side as well.

**Comment by wkurniawan07** [comment]
I see. Then I believe that once this issue #3164 is resolved (I'm working on it!), that floating point precision problem can be handled.
The # possible values is (max - min) / step + 1, this fact is fixed. Once we restrict the step size to just 3 dp, we can do the calculation as [1000 * (max - min)] / [1000 * step] + 1. This is an integer / integer division and won't be subjected to floating point error, no?
