### ISSUE TITLE
Comments: possible unauthorized edit

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3199]
The fact that someone else can change the comment I made is... worrying.
![commentbug](https://cloud.githubusercontent.com/assets/7261051/6873214/be8673ca-d4e9-11e4-9c88-25802296badd.png)
1 edit and 1 refresh later:
![commentbug2](https://cloud.githubusercontent.com/assets/7261051/6873216/bff135a6-d4e9-11e4-841f-b4c6d1b68b2e.png)

**Comment by damithc** [comment]
Instructors with co-owner and manager permissions are able to edit comments from others. This is because sometimes lecturers moderate comments from tutors. I believe the ability of instructors to edit other comments can be controlled by the course owner.

**Comment by wkurniawan07** [comment]
Still, something doesn't seem right (at least for me) if the comment giver's name is replaced just like that. Especially if the edit is minor (unlike the screenshot above).

**Comment by damithc** [comment]
Yes, that's true. it's better if we can show names of all who edited the
comment.

**Comment by wkurniawan07** [comment]
It's a different issue now. Should I close this and open a new one or just rename and rewrite the description of this issue?

**Comment by damithc** [comment]
Either way is fine.

**Comment by wkurniawan07** [comment]
I opened #3202 and put a detailed description there. Going to close this one.
