### ISSUE TITLE
When a comment is edited, show the name of the comment's last editor

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3202]
![commentbefore](https://cloud.githubusercontent.com/assets/7261051/6881674/e1a731f8-d5a4-11e4-9d55-545a44f20ba8.png)
So I'm going to edit a comment that I didn't post. This is fine since I'm the course co-owner and it's within my rights to edit other instructor's comment. However after saving and page refresh:
![commentafter](https://cloud.githubusercontent.com/assets/7261051/6881673/e08a62ea-d5a4-11e4-82b6-98d0af90765a.png)
The problem is my name is now written as the OP. Even worse, notice that I didn't edit the comment at all. I simply pressed "save".
![commentwhatitmustbe](https://cloud.githubusercontent.com/assets/7261051/6881675/e33e9db2-d5a4-11e4-94eb-5f4144c7c0d0.png)
I think this should be how it looks like.
(btw, the screenshot above is only from HTML manipulation; I haven't done any work related to this yet)

**Comment by wkurniawan07** [comment]
@damithc I'm going to work on this incrementally. Firstly is by only showing the last editor and edit date (like the last screenshot posted above), then I can open a new issue to extend it to all editors. Will it work better like that?

**Comment by damithc** [comment]
sure. Incremental is preferred. :-)

**Comment by wkurniawan07** [comment]
Renamed the issue to match :smiley:
