### ISSUE TITLE
reduntant code in InstructorCoursesPageActionTest.java

### ISSUE THREAD

**Issue by karan173** [TEAMMATES/repo#3213]
The function [classSetUp()](https://github.com/TEAMMATES/repo/blob/master/src/test/java/teammates/test/cases/ui/InstructorCoursesPageActionTest.java#L29) in InstructorCoursesPageActionTest.java contains multiple invocations of removeAndRestoreTypicalDataInDatastore().

**Comment by damithc** [comment]
@imouto1994 looks like this happened during a merge.
