### ISSUE TITLE
Word 'gray' misspelled as 'grey' in teammatesCommon.css

### ISSUE THREAD

**Issue by weaveranoop** [TEAMMATES/repo#3214]
Few text-editors are highlighting it. So, changing the spelling to 'gray' could be done to comply with the general spelling of the color used in the web.

**Comment by wkurniawan07** [comment]
Hmmm I don't think this is much of an issue...
![greyvsgray](https://cloud.githubusercontent.com/assets/7261051/6886830/ab5a088a-d67d-11e4-8c91-6fe2797e2fde.png)

**Comment by weaveranoop** [comment]
Okay. Few text-editors were highlighting it. So, I thought of correcting it to comply with the general spelling of the color used in the web.

**Comment by wkurniawan07** [comment]
Oh, no, no, don't close it right away. If you think this is fix-worthy, go ahead :+1:

**Comment by weaveranoop** [comment]
Okay. Thanks for your support Sir.Okay. Thanks for your support Sir.

**Comment by wkurniawan07** [comment]
Sir...? I'm a contributor just like you man. Just giving my opinion on the subject :D

**Comment by weaveranoop** [comment]
My bad. Updated. :P
