### ISSUE TITLE
Responses to Giver's Team in studentFeedbackResultsPage cannot be seen

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3228]
Looks like when OWN_TEAM was added as a recipient type, FeedbackResponsesLogic was not updated to display responses to OWN_TEAM in studentFeedbackResultsPage. One reason this was not discovered until now is that StudentFeedbackResultsPageUiTest did not contain questions to OWN_TEAM.

**Comment by damithc** [comment]
Any lapse in testing eventually comes back to bite us :-)
