### ISSUE TITLE
possible HTML injection in studentFeedbackSubmissionEditPage

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#3231]
After students submit their feedback, the result page doesn't handle HTML elements properly. It can result in something like this 

![screenshot_6](https://cloud.githubusercontent.com/assets/8078323/6918878/14f11444-d7ed-11e4-8388-2e20f9573d2b.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/8078323/6918721/d0c807c4-d7eb-11e4-86e2-7c9304a739e7.png)

This is the question about __Other team__. Then if we submit it again, it will show entityNotFoundPage

![screenshot_5](https://cloud.githubusercontent.com/assets/8078323/6918744/f66b707e-d7eb-11e4-8dd4-6e749030a053.png)

**Comment by LowWeiLin** [comment]
What are the steps to reproduce this?

**Comment by bamboo3250** [comment]
1. Have a student having a team name like above __ a"><a class="btn btn-danger">You can put anything here</a><__
2. Submit a feedback session that has a question about the team having that name.
3. Edit the submission again then you will see it.

**Comment by bamboo3250** [comment]
This issue is fixed via #3205 by the line sanitizeForHTML() we talked about yesterday. 

![screenshot_3](https://cloud.githubusercontent.com/assets/8078323/7059790/5ba7cb1a-deb1-11e4-846f-2f8eafff8652.png)

So please close this issue.
