### ISSUE TITLE
Comments: when more than one is expanded, adding/editing is buggy

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3243]
Pardon the reduced screen size, I wanted to make sure everything can fit in one screenshot.
![commentbug3](https://cloud.githubusercontent.com/assets/7261051/6937801/ee7f4d22-d890-11e4-910c-7f62eb4626ce.png)
Basically, I opened more than one session in the comments page. When I clicked the button for the second one...
![commentbug4](https://cloud.githubusercontent.com/assets/7261051/6937848/55d5076e-d891-11e4-9533-40e75a6d9148.png)
Guess which one gets opened.
By the way, this problem also happened when I clicked the 'Add comment' button, but not if 'Delete comment'.

**Comment by tangzijian** [comment]
Can I try this one?

**Comment by wkurniawan07** [comment]
Go ahead, I'm not working on this one. Don't know about other people out there though :p
