### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing on line 221

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3253]
I'm unable to pass it even after several runs. It's failing under the segment <code> ______TS("test view photo for view by questions"); </code> 
on <code>resultsPage.hoverClickAndViewGiverPhotoOnTableCell(0, 0, "studentProfilePic?studentemail={*}&courseid={*}&user=CFResultsUiT.instr");</code> 

It's failing due to 
<code>org.openqa.selenium.WebDriverException: document.getElementsByClassName(...)[0] is undefined</code>

This line was added in #3028.

**Comment by LowWeiLin** [comment]
This is passing for me. Likely due to timing issues.

**Comment by MrFool** [comment]
I'm having the same issue on latest master even after multiple tries as well, commented out and every other tests passes

**Comment by MrFool** [comment]
Closing, duplicate of #3443 which will have it fixed via executing JavaScript
