### ISSUE TITLE
Add comments documenting why previousFormDataMap is declared outside and document following function

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3268]
It is never accessed anywhere else other than the function following it's declaration, can be moved in instead of hanging globally.

![screen shot 2015-04-05 at 6 06 47 pm](https://cloud.githubusercontent.com/assets/6291947/6996512/b4d56968-dbbe-11e4-88bd-04b2187ee35e.png)

**Comment by LowWeiLin** [comment]
Even though it is only used within the function, the data needs to persist through multiple calls to the function. This is used to prevent making the ajax request if it is not required.

**Comment by MrFool** [comment]
Ah, I understand what that means, in that case a comment might be warranted so that developers do not glance through it and think it is placed outside by mistake?

**Comment by LowWeiLin** [comment]
Sure, can add comments to document the function and change the issue title accordingly.
