### ISSUE TITLE
Test cases failing due to courseId and studentEmail hashes

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3273]
Anyone else encountered the following? I haven't been able to pass these from the latest master even after several tries (more than the usual for timing issues).

![screen shot 2015-04-05 at 7 55 59 pm](https://cloud.githubusercontent.com/assets/6291947/6996760/43ba7484-dbce-11e4-8ca5-5ce8b5c2f17f.png)

**Comment by wkurniawan07** [comment]
which commit caused this? for this kind of comparison {*} should be placed instead of the actual courseId and studentEmail as they are pretty random.

**Comment by wkurniawan07** [comment]
oh wait, doesn't help if I asked which commit. which test caused this?

**Comment by MrFool** [comment]
Hmm I'm not sure which commit caused this - maybe someone modified the HTML files that we are testing against and forgot to change the hashes to {*}?

I'm currently away from my machine but one of them is from the rubric page tests.

**Comment by MrFool** [comment]
That's odd as well, I pulled it from master on upstream and it started failing, your latest master is from upstream as well?

**Comment by wkurniawan07** [comment]
yep, upstream. and it's dev green. like I said, this kind of stuff is random, no? :p
and I managed to trace to the commit that caused this. 
SHA: dc8e70e4260c4250f5a3e632f0d51af391c716b9
surprise, surprise, @JosephineKwa . do take note of this next time, okay?
I'll fix this in no time, so you both can relax :smile:

**Comment by damithc** [comment]
@thyageshm look into how a broken test got merged into master :-)

**Comment by damithc** [comment]
@wkurniawan07 fix as a separate issue.

**Comment by wkurniawan07** [comment]
@damithc will do, but what will happen to this issue then? :p

**Comment by damithc** [comment]
Sorry, didn't notice this issue is about that problem. No need for a new
issue :-)

**Comment by wkurniawan07** [comment]
what still puzzles me is how come @MrFool only got this bug now while the guilty commit is merged 4 days ago.

**Comment by LowWeiLin** [comment]
Probably just luck. Me and @kanghj have been running the tests (many times) and it didn't fail either.
@thyageshm @damithc Perhaps we can add a check in verifyHtml to warn us of such hash strings?

**Comment by MrFool** [comment]
Well no, this isn't the first time I got it but you know the mantra of "running it till it passes"? :p

Yesterday, though, it failed so many times that I decided I might perchance pass it today - apparently it failed so many times I got frustrated enough to look more into it and there borns the issue.

**Comment by wkurniawan07** [comment]
If there are tests that fail persistently even when run in isolation, chances are something is inherently wrong with the test themselves.
I'm currently trying to look for and fix such errors, if they're still there.

**Comment by MrFool** [comment]
Perhaps, I'll take note in the future to report earlier :)

**Comment by thyageshm** [comment]
Sorry @damithc sir, I have overlooked it. I should have been more thorough in my checks. 
@LowWeiLin we could consider #3006 as a way to avoid hashstrings breaking the tests across systems with different keys. I can revisit the code in AppPage to ensure all cases (although I believe it already does).

**Comment by wkurniawan07** [comment]
I only fixed the ones in the guilty commit I mentioned above. It's possible that there are still ninja hash values lurking around.

**Comment by JosephineKwa** [comment]
Hey guys, sorry about the massive error! I wasn't aware about having to use {*} in place of the hash values. I guess my inexperience caught up with me big time... Ill be sure to use the appropriate placeholder for hash values in the future, truly sorry about it!

**Comment by damithc** [comment]
Don't worry, this kind of things are learned through mistakes. There are
other gotchas that you'll encounter in due course. It's part of the
learning experience. :-)
