### ISSUE TITLE
Dividing testAll in InstructorFeedbackPageUiTest and InstructorFeedbackResultsPageUiTest to several sub-tests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3280]
Three tests that particularly caught my attention:
`InstructorFeedbackPageUiTest` (~4.5 mins)
`InstructorFeedbackEditPageUiTest` (~3.5 mins)
`InstructorFeedbackResultsPageUiTest` (~3.5 mins)
I concluded the average run time after running each test for about 10 times each, all in isolation.
They almost never fail when run in isolation, but when run in full suite occasional fails still happen. And each time any of them fail, it means around 3.5-4.5 mins are wasted waiting for them to succeed. That's of course if they don't fail the second time (or the third time, or ...)
Why this is an issue: all other UI tests take only around 2 mins each, or even less. 3.5-4.5 mins are too long.
Suggestion: break each of the above test into two or more separate ones, without reducing the effectiveness of the tests.
(edit: `InstructorFeedbackEditPageUiTest` should be fixed as part of #2345, the solution lined out there is viable)

**Comment by LowWeiLin** [comment]
#2345 is one solution

**Comment by wkurniawan07** [comment]
Right, #2345 is a solution for `InstructorFeedbackEditPageUiTest`. The more worrying one is `InstructorFeedbackPageUiTest` though.
Looks like I've found a new issue to work on. Or rather, two.

**Comment by wkurniawan07** [comment]
Starting this now. Like, finally.
