### ISSUE TITLE
Show student name in the 'add comment' form in Comments view

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3309]
Good to see #2432 implemented! Now time to extend it to Comments view.
![2432followup](https://cloud.githubusercontent.com/assets/7261051/7101995/ac7d47d2-e0a4-11e4-847d-f52a37187d8f.png)

**Comment by wkurniawan07** [comment]
@taniach if you don't mind doing it again :smiley:

**Comment by taniach** [comment]
ok :)

**Comment by wkurniawan07** [comment]
Already done as part of standardization. Closing.
