### ISSUE TITLE
Test failing in instructorCoursesPageUiTest

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3315]
![screen shot 2015-04-13 at 1 12 21 pm](https://cloud.githubusercontent.com/assets/6291947/7110146/f5cb0a24-e1de-11e4-9824-2c616df032de.png)

anyone else or just me?

**Comment by wkurniawan07** [comment]
This happened to me a while back. I did a quick fix and it never happened again, so I thought it's just some anomaly. What a strange thing.

**Comment by wkurniawan07** [comment]
Alright, I managed to reproduce it at will and found the cause as well. Fix should be up in about 10 mins.

**Comment by MrFool** [comment]
Thanks :)
