### ISSUE TITLE
Some Ui Tests missing from testng.xml

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3318]

**Comment by damithc** [comment]
It was never added in the first place?

**Comment by kanghj** [comment]
Uh, when I wrote the tests for moderations, the action tests got ran automatically when running all tests, so I thought Ui tests worked the same way.

**Comment by damithc** [comment]
They have to be added manually. I wonder if there are other tests left out.

**Comment by kanghj** [comment]
Oh yes, there are a few other ui tests that I wrote which is left out. Sorry. 

I'll change this issue's title and add them here. There's also an AdminActivityLogPageUiTest which is not added, but is currently failing.

**Comment by damithc** [comment]
May be we should write another test to check if all tests are included :-p
