### ISSUE TITLE
AdminActivityLogPageUiTest failing on line 52

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3320]
<code> assertEquals(expectedPersonInfo,actualPersonInfo); </code>

![testfailure](https://cloud.githubusercontent.com/assets/2216119/7119331/8775c92a-e237-11e4-9a1f-ec3a53c96496.PNG)

**Comment by wkurniawan07** [comment]
Wait what...? This test also fails for me, but not that bad.
![3320_1](https://cloud.githubusercontent.com/assets/7261051/7119483/7a23dc7a-e238-11e4-8335-5ab7cfad5fe0.png)

**Comment by kanghj** [comment]
Actually whenever I run the test, I get something different. Now I'm getting IndexOutOfBoundsException on line 27.

**Comment by wkurniawan07** [comment]
I get it. This test is _dependent on the logs collected before the run_.
Damn, it will be hard to get this one work.

**Comment by wkurniawan07** [comment]
I think this should be excluded from testng.xml for now. Include only when this test is solid.

**Comment by damithc** [comment]
Yes, the test is not solid.  it is ok to exclude it until it is fixed.
