### ISSUE TITLE
Test failing in instructorEditStudentFeedbackPageUITest.java line line 60

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3327]
![screen shot 2015-04-18 at 2 43 24 am](https://cloud.githubusercontent.com/assets/6291947/7208666/05c83476-e575-11e4-9837-6fd8da7c7e61.png)
![screen shot 2015-04-18 at 2 43 35 am](https://cloud.githubusercontent.com/assets/6291947/7208665/05c6b0c4-e575-11e4-9388-f6d1b09e8bc4.png)

**Comment by MrFool** [comment]
Found in #3323, oddly enough the comparator is expecting a </form> element that was never expected in the HTML file

**Comment by damithc** [comment]
Used to pass before but failing now?

**Comment by kanghj** [comment]
This was a test added in #3318. It's passing for me though.

**Comment by damithc** [comment]
Dev green for me as well. BTW, which test exactly is failing?

**Comment by MrFool** [comment]
The extra </form> being expected even though the file explicitly says it doesn't expect one in the screenshots.

This test as mentioned was recently added, I'm only failing that one test, after commenting it out everything else passes.

**Comment by MrFool** [comment]
My bad, edited title to show where the test is failing, hmm since it's 2 pass to 1 fail now, I'll re-run the test suite entirely and see if it passes, perhaps the order / timing or luck could have caused it to fail

**Comment by wkurniawan07** [comment]
strange, this never fails for me. does it happen even in isolation?

**Comment by wkurniawan07** [comment]
bro, I hate to break this, but you're the one who caused it...
![3327](https://cloud.githubusercontent.com/assets/7261051/7214395/22310bd4-e5dd-11e4-87fd-d3cd886659f4.png)

**Comment by MrFool** [comment]
Oh!! Right! Thanks a lot! I'll close this and fix it on the PR then~

**Comment by MrFool** [comment]
No worries Wilson, I was toiling over it for hours and couldn't spot the mistake and you did in like half an hour! I appreciate it. Thanks and feel free to point out my mistakes or bad coding conventions when you spot any!
