### ISSUE TITLE
Eval statement - ability to run any script instructorFeedbackEdit.js

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3334]
![screen shot 2015-04-19 at 4 14 33 pm](https://cloud.githubusercontent.com/assets/6291947/7218698/42fb924e-e6af-11e4-85ba-eec83085b241.png)

Correct me if I'm wrong, a student can run any JavaScript he/she wants if he/she meddles with the onsubmit attribute?

Found in line 737 instructorFeedbackEdit.js, a safer way would be to click the submit button instead of using eval?

**Comment by MrFool** [comment]
![screen shot 2015-04-19 at 10 51 23 pm](https://cloud.githubusercontent.com/assets/6291947/7219868/f49da9d8-e6e6-11e4-9d88-77253bf35a67.png)
![Uploading Screen Shot 2015-04-19 at 10.51.14 pm.png . . .]()
![Uploading Screen Shot 2015-04-19 at 10.50.35 pm.png . . .]()

Of course, alerting 'yo' is not malicious, but virtually anything conceivable can be ran there

**Comment by damithc** [comment]
Can you give an example of a student using this for a malicious intent?

**Comment by MrFool** [comment]
My bad, it's an instructor page, so it's just that anything can be ran there

**Comment by damithc** [comment]
Hmm... can an instructor harm the system using this loop hole? Any example?

**Comment by MrFool** [comment]
Can't be sure when the user can run anything in particular, maybe bypassing some checks? Or doing a POST request to insert something into the DB.

I know there's extensive backend checks and escaping etc. but we can never be too safe right? :D

We could instead do - 

![screen shot 2015-04-19 at 11 31 37 pm](https://cloud.githubusercontent.com/assets/6291947/7220027/3cf43350-e6ec-11e4-8ce5-a37a1090593b.png)

![screen shot 2015-04-19 at 11 32 11 pm](https://cloud.githubusercontent.com/assets/6291947/7220032/55fc8aaa-e6ec-11e4-88ca-8cd2691b4e62.png)

to be safer?

**Comment by damithc** [comment]
I'm not sure if it poses a security threat. But if there is a safer way, no harm switching to it.

**Comment by MrFool** [comment]
Ok, will reword the issue to reflect that, I'm not 100% sure either but most sources online point allowing users to write any script to a potential security risk and I just thought that changing it to non-eval would be safer and we don't have to worry about any potential risks.

**Comment by LowWeiLin** [comment]
I don't think there is any way a user can run his own script, unless he changes the DOM, which only affects himself. 
The eval always runs what is in onsubmit, which is fixed in the jsp to always be tallyCheckboxes. Some instances of it calls tallyCheckboxes('') where there is no question number passed in.
The eval was a quick/dirty way to deal with it, and could be changed, but there is no security risk/script running as far as I can see.

**Comment by MrFool** [comment]
Ah ok, that makes sense - gonna open a pull request to use non-eval but if it's not a good idea to change it then feel free to close both the issue and the PR, learnt something at least :)

**Comment by LowWeiLin** [comment]
You can't just use tallyCheckboxes(qnNumber); in your pull request. It needs to deal with the case: tallyCheckboxes(''), which is for new questions.

**Comment by MrFool** [comment]
Will look into more detail regarding that, thanks for the heads up

**Comment by MrFool** [comment]
Updated
