### ISSUE TITLE
instructor homepage: 'are you sure you want to publish' alert can be more informative.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3338]
![image](https://cloud.githubusercontent.com/assets/1673303/7233081/c50d279a-e7b1-11e4-8898-b10c78077be5.png)

e.g. is should be 'publish responses'. We can also mention that students will receive an email.

**Comment by XianHuiKoh** [comment]
Perhaps we can change it to "Are you sure you want to publish the responses for the session [Name of session]? Students will receive an email upon publication."?
