### ISSUE TITLE
instructorFeedbackResultsPageUiTest line 245-246

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3339]
Anyone else getting timeout exception even after more than 20 tries?

**Comment by wkurniawan07** [comment]
Couldn't replicate this. Try again and see if it still happens?

**Comment by MrFool** [comment]
Hmm, it happened on two different occassions already, but only those 2 lines always get the timeout, the rest of the tests always seem to pass, could it be a mac only issue?

**Comment by wkurniawan07** [comment]
Whoa, if it's cross-OS already I think I'm out of this :runner: 
Anyway, is it still happening?

**Comment by MrFool** [comment]
Not sure, will find out in awhile, able to run the entire test suite soon :)

**Comment by MrFool** [comment]
Welps, still happening :(

![screen shot 2015-04-24 at 12 07 25 am](https://cloud.githubusercontent.com/assets/6291947/7301565/f53359e2-ea15-11e4-8862-c03759eb17a8.png)

**Comment by wkurniawan07** [comment]
Hmmm... will it still fail even in isolation?

**Comment by MrFool** [comment]
By isolation you mean just this one test file without running the entire suite?

**Comment by wkurniawan07** [comment]
Ya. See if it still happens.

**Comment by MrFool** [comment]
Will reopen based on new test line and investigate, been commenting this out for ages since I'm the only one failing it consistently but I guess I shall take a look at it while some of the code convention is being ironed out.
