### ISSUE TITLE
Student cannot see results of the contribution question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3341]
Happened to one student in my module. The result page looks like this.
![image](https://cloud.githubusercontent.com/assets/1673303/7248072/96b566c8-e842-11e4-8d97-b5d718c120f9.png)
She can see the results of other questions.
The data exists (I can view her data using the 'all records' option, also checked using the GAE data viewer)

**Comment by damithc** [comment]
@kanghj @LowWeiLin could you have a look? I know this is not a good time but better to resolve it now rather than to face it later during the exam period.

**Comment by LowWeiLin** [comment]
Can we see the HTML for that page?

**Comment by damithc** [comment]
``` html
            <br />
            
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Question 1: <span class="text-preserve-space">Please rate the estimated contribution of the following recipients.&nbsp;<span style=" white-space: normal;">
    <a href="javascript:;" id="questionAdditionalInfoButton-1-" class="color_gray" onclick="toggleAdditionalQuestionInfo('1-')" data-more="[more]" data-less="[less]">[more]</a>
    <br>
    <span id="questionAdditionalInfo-1-" style="display:none;">Team contribution question</span>
</span></span></h4>
                        
                    
                    </div>
                </div>
                <br />
```

**Comment by kanghj** [comment]
Just to check, are the other students in the same team or the instructor able to view the results correctly?

**Comment by damithc** [comment]
Other three members can see the responses they received. I can see her
responses when I view her 'all records'.

**Comment by damithc** [comment]
I can see the responses she received in the session results page too.
Somehow, the result is missing in her own result page :-p

**Comment by wkurniawan07** [comment]
I managed to replicate it, but under a very extraordinary situation. Did you change this student's e-mail some time during the course?

**Comment by damithc** [comment]
I don't remember changing her email, although the TA might have changed it.
But it is unlikely (I can check) because her current email is normal nus
email that we would have entered from the beginning.
By the way, she can't see her responses in previous sessions too.

**Comment by damithc** [comment]
Anyway, changing the email reproduces this situation reliably?

**Comment by wkurniawan07** [comment]
Yes, if the only type of question she couldn't see is the contribution question.

**Comment by wkurniawan07** [comment]
If the cause is really a change in e-mail address, reverting it to the old one will fix it (although this is a dirty fix). I'm currently trying to find out why it happened.

**Comment by damithc** [comment]
Yes, that's the only question she can't see.

**Comment by damithc** [comment]
It turns out the email in her Account object is different from the one in her Student object. I guess the page in concern uses the email in the Account object when it should be using the email in the Student object?

**Comment by wkurniawan07** [comment]
From the code, yes the e-mail is taken from `AccountAttributes`. However shouldn't both of them be the same at all times...?

**Comment by damithc** [comment]
No they need not be the same. A person has only one Account object but can
have multiple Student objects (one per course). This student registered in
TEAMMATES earlier for a different course using a different email. That's
the email in the Account object.

**Comment by wkurniawan07** [comment]
Ah, right. I'm willing to bet that's why. Let's see if I can find out how to fix it.

**Comment by damithc** [comment]
The email in the Student object should be used as the identifier within the
course. The Account object is used only to identify a user across courses.

**Comment by wkurniawan07** [comment]
Wait, now I'm confused. If the two e-mails are different, how is it that both of them can associate to the same google ID?

**Comment by damithc** [comment]
Assume the student is in two courses and have joined both courses. She has
two Student objects and one Account object.
Each student object has an email that can be different from each other. The
Google ID in the student objects point to the Account object which also
keeps an email address. Usually this email address is the same one used in
the one of the Student objects (that's the one under which student 'joined'
first), but it may be different from the second Student object.

e.g.
Account: googleId1, email1@gmail.com
Student: course1, googleId1, email1@gmail.com
Student: course2, googleId1, email2@gmail.com

**Comment by LowWeiLin** [comment]
The problem is also present for numerical scale questions. Will be pushing a fix soon.

**Comment by wkurniawan07** [comment]
@LowWeiLin the problem actually lies far down to the abstract method `getQuestionResultStatisticsHtml` in class `FeedbackQuestionDetails`. There, `StudentAttributes` should be used instead of `AccountAttributes`.

**Comment by LowWeiLin** [comment]
Yes i'm changing that in the fix

**Comment by LowWeiLin** [comment]
Using PageData instead of StudentAttributes
