### ISSUE TITLE
submission UI for contribution question: No option to select blank

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3345]
The default should be blank and blank should appear as one of the options? Otherwise there is no way to delete a response. If we go this path, we should cater for students submitting blank for some team members and values for other team members.
![image](https://cloud.githubusercontent.com/assets/1673303/7271736/23b39cf4-e918-11e4-9159-ed185ff2a371.png)

**Comment by wkurniawan07** [comment]
This is partially my fault. When I introduced #1811, I changed the default value from Not Sure to Equal share. Since Not Sure can be disallowed now, I guess the only way out is to include an explicit blank response.

**Comment by damithc** [comment]
Let's do that, but no hurry. Let's do it in May.
