### ISSUE TITLE
Change "Given Responses Statistics" to "Statistics for Given Responses"

### ISSUE THREAD

**Issue by weaveranoop** [TEAMMATES/repo#3349]
In the instructor's results page (Session Results), if the View selected is 'Group by- Giver > Question > Recipient', then the text headers shown in different statistics include "Given Responses Statistics". Replacing that with "Statistics for Given Responses" would be a better option.

**Comment by wkurniawan07** [comment]
Copy of #3245...?

**Comment by weaveranoop** [comment]
No. The headings differ.

**Comment by wkurniawan07** [comment]
Ah right. Very similar, but not copies.
