### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3412]

**Comment by MrFool** [comment]
Question:

![screen shot 2015-05-17 at 12 12 19 am](https://cloud.githubusercontent.com/assets/6291947/7666939/d09464f6-fc2a-11e4-89e6-875d5e83a20f.png)
![screen shot 2015-05-17 at 12 11 13 am](https://cloud.githubusercontent.com/assets/6291947/7666940/d0c3b13e-fc2a-11e4-95a2-7826a2f0f43c.png)
![screen shot 2015-05-17 at 12 09 51 am](https://cloud.githubusercontent.com/assets/6291947/7666941/d0e19d8e-fc2a-11e4-892d-f0ecb120602c.png)
![screen shot 2015-05-17 at 12 09 45 am](https://cloud.githubusercontent.com/assets/6291947/7666943/d0e3e3be-fc2a-11e4-993f-0965bbb75e9e.png)
![Uploading Screen Shot 2015-05-17 at 12.09.35 am.png…]()

Are the following unused imports regarding google app engine and javaX / JDO safe to remove or are they there for a reason? If they are we might wanna suppress the warnings instead.

**Comment by kanghj** [comment]
I think they are safe to remove

**Comment by damithc** [comment]
Is this about one specific file? in that case, rename the issue accordingly.

**Comment by MrFool** [comment]
It's for all the files there are over a hundred unused imports. I'll open a PR when I can confirm all the tests still pass on dev.
