### ISSUE TITLE
'&' is not handled properly in the page footer

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3430]
For example, '[for Johnson & Wales University]' is shown as '[for Johnson]'.

**Comment by MrFool** [comment]
Looked into this but haven't been able to pinpoint exactly where it is happening, but I believe it is being saved as Johnson into the DB instead of 'Johnson & Wales University', thought it might be the sanitizer but haven't been able to spot anything wrong with the HTML sanitizing so far

**Comment by MrFool** [comment]
Correct me if I'm wrong, but with some tracing the two sanitizing that the "institute" string goes through are trimming (for space before and after) and sanitizing for HTML which seems fine - at least from my limited knowledge of regex.

I'll look into it again when I can or if someone else wants to, perhaps the sanitizing isn't the right place to look for it.

**Comment by wkurniawan07** [comment]
This is caused by a missing URI sanitization in `instructorCourseJoinConfirmation.jsp`:
![archnemesis](https://cloud.githubusercontent.com/assets/7261051/7919958/33f73262-08ce-11e5-9cde-0ca5f10d3f2f.png)
Just like #3556 and many others. I thought I've seen the last of this kind of bug.

**Comment by MrFool** [comment]
Nice, maybe you can handle this when you are able to, I can look at the PR and learn how to do it if something like this happens again :)

**Comment by wkurniawan07** [comment]
fixing this one is simple. or so it looks. need to ensure it doesn't affect anything else.

**Comment by wkurniawan07** [comment]
Btw, @MrFool rightly pointed out that the institute name will be wrongly saved for such cases. It is too late to salvage them now.

**Comment by MrFool** [comment]
I don't think this has widely affected alot of people yet, so maybe we could email them asking affected parties to 'open a ticket' and we can manually fix it by invoking admin rights after this is fixed? Or is there not even a way for admins to manually change the institute name or such once it has been saved into the DB?

**Comment by damithc** [comment]
We can write a script to go through the database and do any necessary migration. Fixing the existing data is not very urgent anyway. Can be done as a separate issue.

**Comment by MrFool** [comment]
Yes, but we might not know what the affected data is unless the user tells us because it has already been saved in the truncated version, unless we have the original fragment saved somehwere (I don't believe so), we should not be able to regenerate the affected data.

**Comment by damithc** [comment]
We have all account creation requests in a spreadsheet. We can just check
that to identify ones containing special characters.

**Comment by wkurniawan07** [comment]
Actually if we want to fix the database directly we don't need the fix that I have made, because the bug happens very specifically at the point when the instructor joined the course.

**Comment by kanghj** [comment]
We still need the fix for future users right?

**Comment by wkurniawan07** [comment]
Yes, of course. I'll merge it soon.
