### ISSUE TITLE
Refine InstructorFeedbackResults slice

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3433]
Java main side:
InstructorFeedbackResultsDownloadAction
InstructorFeedbackResultsPageAction
InstructorFeedbackResultsPageData
InstructorFeedbackResultsResponseRatePageAction
InstructorFeedbackResultsResponseRatePageData
FeedbackSessionResultsBundle
FeedbackSessionsResponseStatus

Java testing side:
InstructorFeedbackResultsDownloadActionTest
InstructorFeedbackResultsPageActionTest
InstructorFeedbackResultsPageUiTest
InstructorFeedbackResultsPage

JS:
instructorFeedbackResults.js
instructorFeedbackResultsAjaxByGQR.js
instructorFeedbackResultsAjaxByGRQ.js
instructorFeedbackResultsAjaxByQuestion.js
instructorFeedbackResultsAjaxByRGQ.js
instructorFeedbackResultsAjaxByRQG.js
instructorFeedbackResultsAjaxResponseRate.js
InstructorFeedbackResultsPageUiTest.json

JSP and HTML to be done separately because of their ridiculously huge size.

**Comment by wkurniawan07** [comment]
Dr @damithc the number of changes in the jsp/HTML files here are ridiculously large. Can I split this slice into at least two? Else GitHub won't show all diffs.
For this slice I'll just focus on Java and the testing/coverage

**Comment by damithc** [comment]
Split as much as you like. Smaller the PR, better it is.
