### ISSUE TITLE
InstructorFeedbackResultsPageUiTest test failing line 272-273

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3443]
Haven't been able to pass hover and click after removing nav bar for forever, will investigate and see if I can find out anything

**Comment by MrFool** [comment]
preliminary findings suggest that it's a bug compounded by Mac OS, Firefox version and Selenium version, one workaround might be to use jsExecutor to execute it in JS instead of via Java, will update when more concrete findings are made

**Comment by wkurniawan07** [comment]
well like what I said some time back, if it's cross-OS I'm out of here :runner:

**Comment by MrFool** [comment]
hahaha no worries, I'll dwelve further into it, it might be a unix thing cause Ubuntu and other Linux users are reporting the same thing, it's fixed in higher versions of Selenium but I don't see us going down that road any time soon so might have to try other workarounds
