### ISSUE TITLE
InstructorFeedbackResultsPageUiTest test waiting excessively long around line 456-458

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3445]
Sometimes the test just sits there and do nothing for about half a minute between successive changes, more investigation needed

**Comment by wkurniawan07** [comment]
I'm already on the job for this. Part of my slice.

**Comment by MrFool** [comment]
:+1:

**Comment by wkurniawan07** [comment]
Solved. You won't believe how stupid the error is. I'll be pushing this first since my slice is not gonna be done anytime soon.
