### ISSUE TITLE
Inconsistent behavior of getJsonString in test

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3450]
Introduced in commit 1ac2de7601caaa0722bb45941a4438f4ba0d2bc9 as part of #3408 
![strangebug](https://cloud.githubusercontent.com/assets/7261051/7744109/2a3645b4-ffd3-11e4-96fa-3aad0245011e.png)
This doesn't look like a dangerous bug at all, but still one that's worth investigating.

**Comment by kanghj** [comment]
Do you run the tests with -Duser.timezone=UTC? It could be there in All Tests, but not in the test configuration if you run the test alone

**Comment by wkurniawan07** [comment]
Ah right, that is the cause.
