### ISSUE TITLE
Instructors: When adding a new question, scroll to the newly added question

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/repo#3455]
The animation when adding a new question to a session appears to be scrolling to the bottom of the page.
Would it be better to make it scrolling to the top of the new question instead, so that the user can access it right away?

**Comment by damithc** [comment]
Yes, that's a good idea.

**Comment by damithc** [comment]
Renamed to better reflect the suggest enhancement.

**Comment by yj-soh** [comment]
To clarify, I meant "When adding a new question" rather than "After saving a new question".

When adding a new question (i.e. clicking the "Add New Question" button), the user wants to edit that new question immediately, hence, scrolling to that question is beneficial.

On the other hand, after saving a new question (i.e. after clicking the "Save Question" button), the user seems unlikely to want to see the question again after finishing work on it, so scrolling to that question might be disorientating (as it would do that immediately after a page refresh, from the top of the page).

**Comment by damithc** [comment]
I see. Rename accordingly.
