### ISSUE TITLE
AdminHomePageUiTest test fails sometimes on line 148

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3486]
Supposed to detect a new instructor and show help messages but instead detects and load typical course

**Comment by kanghj** [comment]
Can be fixed by adjusting the priority of AllAccessControlUiTest or AdminHomePageUiTest, I think. They might be interfering with each other

**Comment by wkurniawan07** [comment]
I've made a new testng xml config file which put them in sequential. Got me these yesterday:
![devgreeeeeen](https://cloud.githubusercontent.com/assets/7261051/7791901/0ce05bd4-02db-11e5-9dde-209ff7a31fa0.png)
![devgreeeeeen2](https://cloud.githubusercontent.com/assets/7261051/7791902/0e40d3fa-02db-11e5-91fd-489db11f8a29.png)
![devgreeeeeen3](https://cloud.githubusercontent.com/assets/7261051/7791903/11410304-02db-11e5-86cd-3c904d92996d.png)
Of course, they're quite rare (around 1 out of 6 full runs or so) and random errors still happen. Also, I'm still improving it, so maybe not pushing it anytime soon. Or you want? :p

**Comment by MrFool** [comment]
:+1: we're getting closer and closer to all pass on one try, maybe you can open a new PR for the new config and it just might fix some of those pertaining to different instructors having to log in (sometimes I think the different browsers try to do similar things and end up causing one of the other to fail).

Then, perhaps some of the issues will be fixed along with it and we can close them also.

Nice work :D

**Comment by MrFool** [comment]
Doesn't seem to happen in new test file from #3491, will open if it happens again
