### ISSUE TITLE
InstructorFeedbackPageUiTest can sometimes fail as per screenshot

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3494]
![screen shot 2015-05-25 at 2 13 06 pm](https://cloud.githubusercontent.com/assets/6291947/7792640/3b82dc20-02e8-11e5-8c5c-5d08be2f483c.png)

waiting only 200 ms, we could let it wait longer and return early if it found the element to prevent the random failure

**Comment by wkurniawan07** [comment]
You may find this interesting #2293

**Comment by MrFool** [comment]
Interesting, thanks for pointing me to that, I can look into it and fix it, this seems similar to something else I fixed before

**Comment by MrFool** [comment]
It actually passes if I watch it run and doesn't pass if firefox is not in focus, maybe waiting can fix it, maybe executing JavaScript instead might fix it, I'll try using wait to fix it before trying to use JavaScript

**Comment by MrFool** [comment]
Found the issue (ruled out other possibilities), but have not been able to locate the fix, will continue to look at it some other time.

1. Tried to wait - doesn't help
2. Tried using JavaScript - doesn't help

Turns out, when selenium webdriver's Firefox is not in the foreground/focus, jQuery datepicker does not actually appear so trying to click them results in failure.

**Comment by MrFool** [comment]
The final solution that worked is a combination of a different way of input via selenium and a mix of JavaScript - the only way I could consistently make it pass, will PR the fix once I clean up the code.
