### ISSUE TITLE
waitForModalToLoad() can occasionally fail InstructorFeedbacksPage

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3528]
I should've seen this coming, we should increase all the time wait from 1 second to > 1 second, I've changed a few and they've stopped failing but it seems every once in awhile a different page waiting for the modal to load times out after 1 second, we might as well change all to 5 so we won't see all these occasional failures again

**Comment by wkurniawan07** [comment]
Whoever wrote that 1 second must've thought every developer has a supercomputer

**Comment by MrFool** [comment]
I have a wooden PC :D

**Comment by MrFool** [comment]
Turns out there are only 3 happenings of these, I've elongated the wait on two separate occasions so this is the third and hopefully the last one, going to edit the issue name for consistency sake.
