### ISSUE TITLE
InstructorCommentsPageUiTest occasionally fails at line 106

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3546]
Just got this ->

Expected 'Your profile picture has been saved successfully' but got

'"$$short.name" is not acceptable to TEAMMATES as a person name because it starts with a non-alphanumeric character. All a person name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).'

Will look into it with more detail.

**Comment by wkurniawan07** [comment]
I'm pretty sure this is StudentProfilePageUiTest. I lost count how many times I got this already.

**Comment by MrFool** [comment]
That's another one that I get pretty often, the one I got as per issue title is very rare, actually I only seen it once yesterday >.<

I think the StudentProfilePageUiTest that one is expecting ->

'Your profile picture has been saved successfully'

but got

''

(nothing)

But It doesn't really happen in isolation so haven't really been able to pinpoint it as well

**Comment by damithc** [comment]
Outdated. closing.
