### ISSUE TITLE
InstructorSearchPageUiTest fails in line 101

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3560]
Due to 3f88ecfd91b23ba82d277b2e92c4648f952f8ce7 which is done for #2982

**Comment by kanghj** [comment]
@taniach

**Comment by wkurniawan07** [comment]
I'm afraid this has another complication. Wait for some time while I check it out.

**Comment by wkurniawan07** [comment]
No other complication. Anyway, this needs fix. I made two quick ones:
1. Restore needCheckPrivilege
2. Kept needCheckPrivilege and removed the now-invisible comments from the test file
Either one gives dev green and is ready to push/merge right away.

**Comment by kanghj** [comment]
Let's remove the now-invisible comments from the test file for now then? I'll look into this more carefully tomorrow.

**Comment by wkurniawan07** [comment]
Ok I just merge my 2nd fix then
