### ISSUE TITLE
InstructorCommentsPageUiTest occasionally fails at line 106

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3566]
![screen shot 2015-05-29 at 1 04 53 pm](https://cloud.githubusercontent.com/assets/6291947/7876755/55130912-0603-11e5-82aa-52851f1eb39f.png)

**Comment by MrFool** [comment]
Nevermind, noticed that this just got fixed by the recent changes in master (now passes after merging master), closing.

**Comment by wkurniawan07** [comment]
That looks like contamination from InstructorSearchPageUiTest. Nevertheless, good that it's fixed.
