### ISSUE TITLE
InstructorFeedbacks: incorrect timezone

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3585]
![wrongtimezone](https://cloud.githubusercontent.com/assets/2216119/7902693/4b1372c4-07f4-11e5-91af-c2221751567a.PNG)

Our javascript no longers sets the default timezone to be the user's timezone. This is affecting the live server. Caused by commit 24b43197, during the refactoring of the js files.

**Comment by damithc** [comment]
Rolled back to V5.43 on the live server.

**Comment by damithc** [comment]
@yj-soh add a test case to detect the bug before fixing it.
