### ISSUE TITLE
Regenerate all html files in God mode again

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3588]
Extension of #3006 and #3369 
I made a modified version of God mode where the test file will always be updated upon successful verification. Ran it on the whole test suite and the result is shocking:
182 files changed, 66788 insertions, 59388 deletions
Many changes can be unintended (like wrongly discarding important wildcards), which need to be checked manually. :fearful: 
(this is exactly what I have done in #3552, #3553, #3575, and #3587)

**Comment by wkurniawan07** [comment]
Ran it on ICommentsPUiTest...
20699 insertions 18103 deletions
:hocho: :hocho: :hocho:

**Comment by wkurniawan07** [comment]
Run on all the UI tests separately, most are already refined and merge-ready (or already merged) except for the following 6:
IComments: 19 files, 20699 + 18103 -
SFSubmit: 10 files, 5026 + 4231 -
ICourseEdit: 7 files, 6725 + 5994 -
IFSubmit: 10 files, 4889 + 4431 -
IFPage: 10 files, 5054 + 4503 -
IFEditPage: 10 files, 4010 + 3681 -

**Comment by wkurniawan07** [comment]
Ran modified God mode on the whole test suite just now, diffs are only recorded on the above mentioned files, entityNotFoundPage.html, and the spots that need manual adjustment. If God mode is to be used to regenerate test files the diff should be minimum.
Will do the above 6 tests sometime soon.

**Comment by junhaoyap** [comment]
This was done recently after JSTL-Dev was merged in, closing.
