### ISSUE TITLE
Remove references to 'Evaluation'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3589]
Are these redundant or are they using the term 'evaluation' to refer to feedback sessions? By the way, why do we have 'test' in the code?
![image](https://cloud.githubusercontent.com/assets/1673303/7912523/cfb99e3a-089a-11e5-9f73-dadd11f2d1e3.png)

**Comment by kanghj** [comment]
The term 'evaluation' is used to refer to feedback sessions here, missed this and some other references to evaluations that were not directly used in the evaluations code. Will do a more thorough search through the repo for evaluations in this issue and rename/remove them.

The '-for-test' naming seems to have been around for a while and they appear frequently in various places in the code, including instructorHome, instructorSearch and instructorStudentList. Will make a new issue to either remove or rename them.
