### ISSUE TITLE
Extra '<' in instructorCourseEdit.jsp breaking 'View Details' modal

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3606]
![extralt](https://cloud.githubusercontent.com/assets/2216119/7952531/6c607c28-09e9-11e5-9383-9a7bccb24c02.PNG)

There is an additional '<' in the onclick attribute in instructorCourseEdit.jsp that prevents the 'View Details' for the 'Observer' role from working.

**Comment by kanghj** [comment]
This looks like it has been broken for quite a while already

**Comment by MrFool** [comment]
No have ui test for this functionality ?

**Comment by kanghj** [comment]
Yeah, no ui test. @bamboo3250 can add one here.

**Comment by MrFool** [comment]
:+1: less chance of breaking this unintentionally in the future then
