### ISSUE TITLE
StudentCourseJoinConfirmationPageUiTest fails due to invalid login page

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3607]
Was actually doing God mode refinement on this UI test when suddenly this happened:
![scjcbug](https://cloud.githubusercontent.com/assets/7261051/7952798/08e5d5f8-09ee-11e5-9b40-36ae238002f1.png)
Encountered this for a while already but this is the first time I encountered it _in isolation_, which is a good thing since I can now pinpoint the cause exactly.

**Comment by MrFool** [comment]
Finally, this pesky failure that is hard to replicate

**Comment by wkurniawan07** [comment]
This is actually quite easy to replicate, see the explanation in my PR.
