### ISSUE TITLE
Nonexistent JS Method Call on clicking Archive Button in InstructorHome.

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/repo#3631]
The archive button for each course is calling the toggleArchiveCourseConfirmation() JavaScript function on click.
However, this function does not exist.
Is it supposed to be a confirmation prompt like the Delete button?

The call was introduced in fcd37f2929fe611b37fed8fda1f773f10bdadf94, but there was no JS changes in that commit, so I assume the person typed it in and forgot to implement the function.

**Comment by MrFool** [comment]
Seems like it, the commit was "introduced archive feature" so it's most likely that it's meant to be a confirmation for archiving.
