### ISSUE TITLE
FeedbackRubricQuestionUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3640]
Failing at 
`143: submitPage.verifyHtmlMainContent("/studentFeedbackSubmitPageRubricSuccess.html");`

**Comment by damithc** [comment]
Failed after repeated attempts. Not a recent failure. Have been failing for a while.

**Comment by MrFool** [comment]
Can post error trace or what it expects versus what it got the next time this is run? If there's time I can try it on staging next time if live server isn't running any tests in the near future.

**Comment by damithc** [comment]
Try to replicate using staging server (it is inevitable you'll have to run it against the staging server anyway). If cannot replicate, I'll try to get traces from live server.

**Comment by MrFool** [comment]
Ok, cause I almost busted my limit for the previous day, will run when it's resetted :p

**Comment by damithc** [comment]
line 150
        submitPage.verifyHtmlMainContent("/studentFeedbackSubmitPageRubricSuccess.html");
![image](https://cloud.githubusercontent.com/assets/1673303/10037230/d8d0c3aa-61e5-11e5-8463-184af7e41201.png)

**Comment by JosephineKwa** [comment]
Its passing for me too, i tried leaving my mouse hovering and without hovering. Both passed on staging server.

**Comment by damithc** [comment]
I fail it repeatedly though.

**Comment by LowWeiLin** [comment]
@JosephineKwa 
This just failed for me again.

![image](https://cloud.githubusercontent.com/assets/3910365/10631973/f2333186-7813-11e5-8c33-212ba35de618.png)

**Comment by damithc** [comment]
Passed for me this time :-p
