### ISSUE TITLE
Highlighting of updated session in instructorFeedbacks.jsp is broken

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3662]
![wrongcomparison](https://cloud.githubusercontent.com/assets/2216119/8050080/e32f6ed6-0e99-11e5-8de3-bf4f78e2a03c.PNG)

The comparison is now always true and causes all rows to be highlighted. 
Broken when instructorFeedbacks.jsp was refactored. Will fix this before I start converting the page to jstl.

**Comment by damithc** [comment]
Try to write a test first.
