### ISSUE TITLE
StudentProfilePage vulnerable to scripting

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3679]
![newbug](https://cloud.githubusercontent.com/assets/7261051/8099159/835fb2a2-102b-11e5-920c-3d63ae53c2c6.png)
Add: it will also be propagated to AdminActivityLogPage

**Comment by MrFool** [comment]
This is where what we talked about come in useful, <c:out> sanitization when the backend might have missed it, but we have to fix live first

**Comment by wkurniawan07** [comment]
I managed to fix this one, but looking at the cause of the error, this might happen in few other places.

**Comment by wkurniawan07** [comment]
The explanation is quite short, though: back-end actually did a decent job in filtering scripts, but it forgot to filter _status messages_.
