### ISSUE TITLE
HTML naming for newly joined instructor is not consistent

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3686]
![screen shot 2015-06-11 at 4 02 50 pm](https://cloud.githubusercontent.com/assets/6291947/8102532/59e34d08-1053-11e5-9178-4ec5790bd775.png)
![screen shot 2015-06-11 at 4 02 46 pm](https://cloud.githubusercontent.com/assets/6291947/8102531/59e0b836-1053-11e5-8f6b-caa64ae11a1f.png)

Let's choose 1 and make it consistent

**Comment by damithc** [comment]
I prefer the 2nd one because it is self-explanatory.

**Comment by MrFool** [comment]
Always wondered what was NJI when I started on Teammates :p
