### ISSUE TITLE
Check compatibility with SDK 1.9.22

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3691]
These are the changes. see if they affect us. Note that even if we don't upgrade the dev environment, the live environment is upgraded automatically, so we have to ensure compatibility.

- Following a recent update to the JDK version used to run Java apps, 
the method javax.activation.MimetypesFileTypeMap.setDefaultFileTypeMap 
is no longer allowed. This method is almost never needed: if you want to 
update the default file type map, simply modify the map returned by 
FileMap.getDefaultFileTypeMap, like this: 
MimetypesFileTypeMap map = (MimetypesFileTypeMap) 
MimetypesFileTypeMap.getDefaultFileTypeMap(); 
map.addMimeTypes("image/webp webp");

**Comment by kanghj** [comment]
Searched through the project folder and it does not look like we use <code>setDefaultFileTypeMap</code> anywhere.

**Comment by damithc** [comment]
Thanks for checking. Closing.
