### ISSUE TITLE
instructor feedback edit: changing the 'close time' changes the start time automatically

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3692]
If the close time is set to a time earlier than end time (by mistake), the start time is pushed back automatically without warning the user. This is not intuitive.

**Comment by kanghj** [comment]
What should the expected behaviour be? Show an error message using javascript?

**Comment by damithc** [comment]
Even doing nothing should be fine because when the user submits he will get an error message. A better solution is to show an error message immediately, but I don't think we have a good standard mechanism to show in-place error messages at this time.
