### ISSUE TITLE
HTML naming for student is not consistent

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3696]
![screen shot 2015-06-12 at 2 15 32 pm](https://cloud.githubusercontent.com/assets/6291947/8124413/9012d596-110d-11e5-8342-4984fb7a91a2.png)
![screen shot 2015-06-12 at 2 15 26 pm](https://cloud.githubusercontent.com/assets/6291947/8124414/9040abe2-110d-11e5-9e8d-8954b04a563c.png)

Mostly camel but some pascal, can be fixed along with #3686

**Comment by damithc** [comment]
Either style is fine as long as it is consistent. Just use the one that is more commonly used among other html files.
