### ISSUE TITLE
Make sure all UI tests have at least 1x verifyHtml and the rest can be verifyMainHtml

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3709]
This can not only help to speed up testing, tests will be less fragile when they don't need to be and development speed++

**Comment by MrFool** [comment]
Quite a few html tests don't have a single verifyHtml, perhaps we can insert comments for the one that we want to be verifyHtml and let the rest be verifyMainHtml so that we get a good balance of testing

**Comment by MrFool** [comment]
Will take a look at this and handle it when I'm back on Monday

**Comment by MrFool** [comment]
Let's hold this until after JSTL is completed, makes more sense for this to be in master and if this is merged into JSTL-Dev it will increase the amount of HTML changes which we are trying to minimize while working on JSTL-Dev.

**Comment by wkurniawan07** [comment]
Or you can just do it in master and sync in to JSTL-Dev. Makes even more sense.

**Comment by MrFool** [comment]
Yeah, we could do that, but will need to deconflict when syncing to JSTL-Dev, hopefully not too much conflicts then :p
