### ISSUE TITLE
Minor inconsistency in testing file name for instructorFeedbackResultsByAJAX

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3710]
![screen shot 2015-06-13 at 11 05 59 pm](https://cloud.githubusercontent.com/assets/6291947/8144811/daf033ce-1220-11e5-8483-92322b29d85f.png)

Usually, across Teammates whenever there is multiple related html tests, they are appended by 1,2,3 to make it obvious that they are for similar tests, but this particular one is off, I'll do the needed fix.

**Comment by damithc** [comment]
I'm not sure 1,2,3 suffixes are a good idea though. Its hard to insert something in the middle and they don't help to describe the file. Instead use `-explanatoryWord.html` suffix?

**Comment by MrFool** [comment]
I'll take a look at that and see if there's any explanatory tag suitable or they're just two similar tests

**Comment by MrFool** [comment]
In JSTL-Dev, closing
