### ISSUE TITLE
Minor inconsistency in one instructorFeedbackSAll....html file name

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3711]
![screen shot 2015-06-13 at 11 08 57 pm](https://cloud.githubusercontent.com/assets/6291947/8144819/336cf4b0-1221-11e5-82e4-bb9370d0a4dc.png)
![screen shot 2015-06-13 at 11 08 50 pm](https://cloud.githubusercontent.com/assets/6291947/8144820/33707824-1221-11e5-9e4f-f9dc05efda51.png)

Self explanatory, I'll fix this along with the other naming consistency issues

**Comment by wkurniawan07** [comment]
Do you not have break on weekends :astonished:
