### ISSUE TITLE
datepicker.js: variables are not initialised correctly

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3714]
![datepickervariables](https://cloud.githubusercontent.com/assets/2216119/8147899/b480776e-12b4-11e5-8ed2-66fea896171a.PNG)

getDate is a function, and its used here without getting called (missing '()'). So this causes the values of <code>today</code>, <code>yesterday</code>, <code>tomorrow</code> to be incorrectly set.

**Comment by damithc** [comment]
Fix in the master?

**Comment by damithc** [comment]
BTW, what's the impact to the user?

**Comment by kanghj** [comment]
If the variables are initialised correctly, then on the date picker, some dates are disabled:

for example on the end date datepicker:
![current](https://cloud.githubusercontent.com/assets/2216119/8151811/ccf4ecfc-1346-11e5-948a-35abd5efe137.PNG)

If the variable were correctly initialised:
![withcorrectvariable](https://cloud.githubusercontent.com/assets/2216119/8151815/d7b3b182-1346-11e5-976c-b597f32f1e77.PNG)
