### ISSUE TITLE
Change JSTL generic page tag(s) to be in line with standardized format

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3720]

**Comment by kanghj** [comment]
Anyone working on this? We need this before we can correctly update the html tests

**Comment by MrFool** [comment]
Working on it now :)

**Comment by MrFool** [comment]
Will need to merge this along with the other jsp changes, also need to work on #3708 and #3709, once those are done and all these are merged, we will have a lot less manual HTML changes to do when we update the HTML tests
