### ISSUE TITLE
Bug in "Add New Instructor" button in InstructorCourseEdit

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/repo#3741]
The button can be edited as shown below:

![addinstructorbutton](https://cloud.githubusercontent.com/assets/9999077/8179227/eb9ad07a-1447-11e5-8310-1711c4c370b3.PNG)

To reproduce this bug, click and hold on the button and type words in simultaneously.

![code](https://cloud.githubusercontent.com/assets/9999077/8179313/6ad063f0-1448-11e5-8ba4-10ed1e268b12.PNG)

Adding type="button" to the input tag seems to do the trick, but it changes the button width slightly.

**Comment by kanghj** [comment]
Fixed in #3741
