### ISSUE TITLE
Change colour of 'how to interpret' link in student feedback results page

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#3742]
![screen shot 2015-06-16 at 4 56 31 pm](https://cloud.githubusercontent.com/assets/7547452/8179509/abaabe06-1449-11e5-95f7-5840b9ed19d2.png)

For team contribution questions, the link [how to interpret, etc..] cannot be seen clearly

**Comment by junhaoyap** [comment]
@ngzhian This too!
