### ISSUE TITLE
'copy session' feature creates a standard session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3767]
This refers to the 'copy' feature in the home page. It seems to create a standard session instead of copying the intended session.

**Comment by damithc** [comment]
This seems to be a false error report. Check it anyway.

**Comment by kanghj** [comment]
It seems to be working fine for me on the latest master.

**Comment by MrFool** [comment]
I think I did this issue, I can take a look :)

**Comment by MrFool** [comment]
Working fine for me on latest master as well

**Comment by MrFool** [comment]
This seems to be a false error report, but the other one seems to be a real error

**Comment by damithc** [comment]
Also try the other copy button in the sessions page.
>
>

-- 
Sent from a mobile device.

**Comment by MrFool** [comment]
From the sessions page

![screen shot 2015-06-18 at 12 36 23 pm](https://cloud.githubusercontent.com/assets/6291947/8224253/ac8b7e00-15b6-11e5-904b-deab9e4c2d42.png)
![screen shot 2015-06-18 at 12 35 55 pm](https://cloud.githubusercontent.com/assets/6291947/8224255/ac8faf98-15b6-11e5-972c-9a981b0a1460.png)
![screen shot 2015-06-18 at 12 35 33 pm](https://cloud.githubusercontent.com/assets/6291947/8224254/ac8de096-15b6-11e5-96eb-c5c14dc1d8a1.png)
![screen shot 2015-06-18 at 12 35 29 pm](https://cloud.githubusercontent.com/assets/6291947/8224256/ac90c8ec-15b6-11e5-841d-751990cf9f6a.png)
![screen shot 2015-06-18 at 12 35 20 pm](https://cloud.githubusercontent.com/assets/6291947/8224257/ac933e24-15b6-11e5-9795-5bcbddc10759.png)

**Comment by MrFool** [comment]
From home page

![screen shot 2015-06-18 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/6291947/8224263/cf16b3cc-15b6-11e5-8974-07695906f6d0.png)
![screen shot 2015-06-18 at 12 37 16 pm](https://cloud.githubusercontent.com/assets/6291947/8224264/cf177cf8-15b6-11e5-93a4-639bdd4efbbf.png)
![screen shot 2015-06-18 at 12 37 09 pm](https://cloud.githubusercontent.com/assets/6291947/8224262/cf16b2f0-15b6-11e5-90bd-c789187633fe.png)
![screen shot 2015-06-18 at 12 37 04 pm](https://cloud.githubusercontent.com/assets/6291947/8224265/cf192684-15b6-11e5-9a74-70e4c4195f8f.png)
![screen shot 2015-06-18 at 12 36 55 pm](https://cloud.githubusercontent.com/assets/6291947/8224266/cf40a0d8-15b6-11e5-8ff8-159dfb5e4c63.png)

**Comment by kanghj** [comment]
The screenshots are to read from the bottom then going up, right? For a while, I was wondering why a feedback session got deleted after getting copied. 

I've also tested and verified that it works for me too.

**Comment by MrFool** [comment]
Yes from the bottom up, I forgot to reorder them after uploading, my bad :p

**Comment by damithc** [comment]
The user was trying to copy to the same course. Try that too. Said she
tried several times with the same result.
>
>

-- 
Sent from a mobile device.

**Comment by kanghj** [comment]
Copying to the same course seems to work.

**Comment by kanghj** [comment]
Are there any logs or any additional information for this? One possible reason for this is that there are orphaned questions with the same feedback session name as the session the user is trying to create.

**Comment by damithc** [comment]
I looked through the logs. Looks like she tried to copy without giving a
session name, was redirected to sessions page with an error message, and
then went on to create a new session while under the impression that she is
still in the 'copy session' mode.

**Comment by kanghj** [comment]
Ah, perhaps we should load the modal for copying when the user fails to copy, and display the status message on the modal instead. We can probably do this when we make the copy form use ajax for submissions.

**Comment by damithc** [comment]
Yes, that sounds better.

**Comment by MrFool** [comment]
Let's rename the issue to point to doing that. So we just need a better response to user in essence?

**Comment by damithc** [comment]
May be better to close this one and start a new issue? Otherwise future assignee of this issue will be confused by the first few posts.

**Comment by MrFool** [comment]
Sounds like a better idea :)
