### ISSUE TITLE
Cannot select a session in the 'copy session' modal

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3768]
This refers to the modal in the feedback sessions page.

**Comment by MrFool** [comment]
Hmm copy to or copy from? I think we have both modals inside right now.

**Comment by kanghj** [comment]
copy from

**Comment by MrFool** [comment]
I've been able to recreate this bug

**Comment by MrFool** [comment]
Currently, if we click on the circle, it will cause the radio button to become disabled.

![screen shot 2015-06-18 at 12 11 00 pm](https://cloud.githubusercontent.com/assets/6291947/8224047/1eeac3c4-15b3-11e5-86da-b1dfea3f63da.png)
![screen shot 2015-06-18 at 12 10 54 pm](https://cloud.githubusercontent.com/assets/6291947/8224048/1eeca87e-15b3-11e5-870d-16d0367e1c5f.png)
![screen shot 2015-06-18 at 12 10 44 pm](https://cloud.githubusercontent.com/assets/6291947/8224049/1eefba82-15b3-11e5-81b0-4660fd57ceed.png)

**Comment by kanghj** [comment]
![previous](https://cloud.githubusercontent.com/assets/2216119/8224189/6f6fc4f0-15b5-11e5-9e98-c61e89e8ed10.PNG)

This part of the code assumes that the checked input is the previous row that was selected, but in fact if you clicked on the checkbox to choose the row, this code returns you the row that was currently checked.

**Comment by taniach** [comment]
I can do it

**Comment by MrFool** [comment]
On a side note, the on click function is longer than it needs to be

return false calls event.preventDefault() and event.stopPropagation(), we either need to prevent the default and stop the propagation or we only need one, it is confusing to have both preventDefault and return false that does both.

![screen shot 2015-06-18 at 12 33 02 pm](https://cloud.githubusercontent.com/assets/6291947/8224234/47c6b5de-15b6-11e5-9fc9-c3eed76e13b3.png)
