### ISSUE TITLE
Minimize the surprise for master branch when JSTL-Dev is merged in, part 1

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3788]
There are changes in JSTL-Dev that should be merged to master instead. Because of that, when JSTL-Dev is merged to master, we will see more changes than necessary. Master needs to be updated with such changes so that when JSTL-Dev is merged we only see the changes due to migration.
Such changes are:
1. (must do) HTML test file renaming and the clearance of unused JS/CSS
2. (if possible) JSP standardization
3. (also if possible) Header contents (favicon, CSS, JS, ...) standardization
This can be done by cherry-picking the commits in the mentioned changes (and hoping for no to minimal conflicts).

**Comment by wkurniawan07** [comment]
@MrFool cherry-picking preserves the author name so I'm not stealing the credits from you :smile:

**Comment by wkurniawan07** [comment]
Dividing the issue into parts as described above.

**Comment by MrFool** [comment]
No worries, I agree that this is a good move and you're doing a favor for everyone by doing this, credits are less important, thanks again.

**Comment by wkurniawan07** [comment]
Sharing some numbers.
Before minimizing:
Trying to merge 5cb9fa6 (`JSTL-Dev` branch, updated with the latest `master` at the time just before minimization starts) to 25b285c (the latest `master` at that time): 51 new files, 252 modifications, 28 deletions, 20 renames.
After minimizing:
Trying to merge 1eb0ef7 (`JSTL-Dev` branch updated with current latest `master`) to 2ec9215 (current latest `master`): 50 new files, 68 modifications.
Mission accomplished.

**Comment by MrFool** [comment]
:+1:

**Comment by MrFool** [comment]
Oh and when we merge JSTL-Dev in into master eventually, we need to make sure the HTML are ok, I think cause when I did the standardization some pages were already done in JSTL, there are still some remnants of "theme-showcase" moot classes in the current master HTML, should be removed when JSTL-Dev is merged but we can always keep an extra eye looking out for those in case they don't disappear.

But still, less changes is always easier to merge for these long lived branches :D So this was a good initiative!
