### ISSUE TITLE
Upgrade jQuery from v1.11.1 to latest v1.11.3 and use CDN

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3799]
Reduces jQuery size as it drops support for IE 6, 7, 8 that is also not officially supported by TEAMMATES along with some bug fixes.

Need to also investigate whether or not we need to update legacy code for upgrading.

**Comment by MrFool** [comment]
We can hold off on jQuery 2.x until maybe next year when IE8's market share is lower, will open an issue for that

**Comment by MrFool** [comment]
Can do this when JSTL is complete, easier to change it with a template than all the jsp files, can hold this till then.

**Comment by junhaoyap** [comment]
Merging into JSTL-Dev, closing
