### ISSUE TITLE
Name variables in bindCopyEvents in instructorFeedbacks.js in a more readable way

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3804]
for e.g. ->

currentRow can be currentlySelectedRow

selectedRow can be previouslySelectedRow
selectedRadio can be currentlySelectedRadio and previouslySelectedRadio instead of using selectedRadio to mean both of them when they don't mean the same thing

**Comment by taniach** [comment]
Done in #3768

**Comment by MrFool** [comment]
#3768 has been merged so I am going to close this.
