### ISSUE TITLE
InstructorFeedbackPageuUiTest unstable at line 866.

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/repo#3808]
`java.lang.AssertionError: expected:<10> but was:<1>`
This seems to be caused by a laggy / missed dropdown selection from line 858.
May be Selenium's fault; the dropdown opens and the value is selected, but it seems to not commit the result (in human terms, it clicks on the dropdown, hovers over the value, and stops before clicking on it).

Works fine when running it on debug and ensuring the values are filled correctly.

**Comment by MrFool** [comment]
Met this before as well, can attest to it happening every so often
