### ISSUE TITLE
InstructorFeedbackEditPageUiTest line 155 commented out

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3818]
It's currently commented out without any comments explaining why, do we still need this test at all or has it been accidentally commented out?

![screen shot 2015-06-24 at 4 05 28 pm](https://cloud.githubusercontent.com/assets/6291947/8325298/d95ffd1a-1a8a-11e5-8fee-e110d1442967.png)

**Comment by wkurniawan07** [comment]
This commit dd12fc8 commented out the test and this one e1b34e6 deleted the test file. Wow it's been over a year.

**Comment by damithc** [comment]
@thyageshm remember why you commented it out?

**Comment by MrFool** [comment]
I saw @LowWeiLin on the bus this morning, apparently e1b34e6 was done most likely by deleting all HTML files and regenerating the rest so this particular file was removed when that was done as it was already commented out by then.

**Comment by thyageshm** [comment]
I will look at it as soon as possible

**Comment by thyageshm** [comment]
Hi I believe I have commented out a number of tests in that page. This has been quite a while, but looking at the changes I have made, I have substituted the slow html comparison tests with more specific tests that look for the element that has changed / has been expected to change - Something I tried to reduce inter-dependency of tests

**Comment by MrFool** [comment]
Perhaps we should remove the HTML files and remove the tests instead of commenting them out? That might help reduce confusion during maintenance in the coming years.

**Comment by damithc** [comment]
Yes, deleting is preferred to commenting out. @MrFool if you think the test is no longer needed, can go ahead and delete.

**Comment by MrFool** [comment]
I'll take a look at it and PR against this issue, I will try to look through the other commented out stuff in the same page as well.
