### ISSUE TITLE
Migrate StudentHome page actions to its own template file

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3823]
![shpactions](https://cloud.githubusercontent.com/assets/7261051/8347660/306ff014-1b3b-11e5-9005-5da7b729d521.png)
#3787's sibling, but much much shorter.
@yj-soh can I do this on your #3676?

On another note, I hope this is the last migration there is to be done.

**Comment by yj-soh** [comment]
Go ahead, I'll change anything if needed afterwards.
