### ISSUE TITLE
Remove instructorFeedbackStats.jsp and all its reference

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3831]
Not used anywhere.
I realized this when I was reviewing #3819. I actually went on to check that every single .jsp file is used, and this one is surely not. There is a reference for it in Java, but it's an ajax result and doesn't need .jsp template.
In fact, upon probing the file's history, this file is introduced along with that ajax result, which means that it's never even necessary to have the file in the first place.

**Comment by MrFool** [comment]
Hmm I once remember seeing some JavaScript loading this href and grabbing the numbers and displaying it on the home / feedbacks page, is that not the case anymore?

**Comment by wkurniawan07** [comment]
Indeed, there are existing links to `/page/feedbackSessionStatsPage?params`, however this is not what the issue is about.
The action on that page (`FeedbackSessionStatsPageAction`) resulted in ajax result, not show page result. Show page result is the one that takes in .jsp template, populate it, and return it to the browser to be rendered. Ajax result, on the other hand, simply returns data without the need for .jsp template.

**Comment by wkurniawan07** [comment]
Ooooh found a hidden jewel in AjaxResult.java.
![ajaxresult](https://cloud.githubusercontent.com/assets/7261051/8370570/20165f8e-1bfc-11e5-9762-441a40e8e09d.png)

**Comment by MrFool** [comment]
Right, I don't think this page is ever "shown page" (as far as I know) but always pulled via the "ajax results", I understand what you mean now :)
