### ISSUE TITLE
StudentFeedbackPageUiTest line 109 fails occasionally

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3833]
This has been plaguing us recently, used to not happen at all so we need to investigate why.

Basically, Charlie and Danny doesn't get along and likes to switch places and cause the HTML verification to fail.

**Comment by kanghj** [comment]
My guess is that this can be fixed if we sort the responses by Recipient, then by giver if the recipient is the same. Currently we are only sorting by Recipient.
