### ISSUE TITLE
Standardize Comments in InstructorStudentRecords, InstructorComments, and InstructorSearch

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3838]
![comments](https://cloud.githubusercontent.com/assets/7261051/8372663/f5faf70c-1c17-11e5-88f0-4d057ce236c8.png)
Arranged in the order they are mentioned in the issue title.
Apart from some inevitable differences (such as icons and buttons on the side) this really calls for some standardization.

**Comment by wkurniawan07** [comment]
@JosephineKwa There's one more (uninvited) guest: StudentComments page.

**Comment by JosephineKwa** [comment]
Currently FRCs have this header format (based on PR #3852):
From: you \[Fri Jun 26 04:07:02 UTC 2015\] (last edited by jo@email.com at Tue Jun 30 02:52:05 UTC 2015)
While student comments have this format:
From: Instructor jo on 24/06/2015 (last edited by Instructor jo at 24/06/2015)
Would it be better if I stick with using "on" or should I use the square brackets to show the posted date to standardise between FRCs and student comments?

**Comment by wkurniawan07** [comment]
Try to follow FRCs if you can. Anyway, on my side, all FRCs regardless of student/instructor side will have the same header format after standardization.
