### ISSUE TITLE
StudentFeedbackSubmitPageUiTest failing on line 85 on JSTL-Dev

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3844]
The message of the day is causing it to fail

**Comment by junhaoyap** [comment]
Can post the failing screenshot, I can't get it to fail after running it a number of times.

**Comment by kanghj** [comment]
![studentmotd](https://cloud.githubusercontent.com/assets/2216119/8401322/7b32a5ca-1e5f-11e5-8d8b-68338cc4aeab.PNG)

The fix for this will be to include the motd in the build.properties file. We could modify this issue, or make a new one, to add the default value for motd

**Comment by junhaoyap** [comment]
Agreed, new comers may hit this particular bug (it wasn't tested before before #3709).

In fact, current developers who never did the above settings might also meet this "bug" all of a sudden.

Perhaps there is a reason why it was never defaulted in the first place?

**Comment by junhaoyap** [comment]
@damithc any insights on this?

**Comment by damithc** [comment]
MOTD is controlled by changing the build.propertiles file. Not sure how to test it. I don't think any of our tests manipulates the build.properties file.

**Comment by kanghj** [comment]
We can update verifyHtml to ignore the contents of the motd, but check that the student-motd-container is present.

**Comment by kanghj** [comment]
see #3932
