### ISSUE TITLE
Bug when displaying Anonymous for Feedback Response Comments

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/repo#3867]
Instructors who are not allowed to view the giver of a Feedback response comment can still see the giver. Originally, it is supposed to display "Anonymous", however now it displays the giver's name/email. 

This applies to all page where instructors are able to view feedback response comments, namely InstructorFeedbackResults, InstructorStudentRecords, InstructorComments and InstructorSearch

**Comment by wkurniawan07** [comment]
Are you sure this actually happened? I can't seem to replicate it.

**Comment by JosephineKwa** [comment]
My bad :pensive: , I think the Instructor not allowed to view the FRC giver was the FR giver/recipient, so even though he was not allowed to view it as an instructor, he was still able to view it as the giver/recipient of the FR. Somehow most of my FRs with FRCs were like this when I was testing manually, so I kinda missed out considering this possibility. Sorry for the confusion!

**Comment by junhaoyap** [comment]
I see, so we should rename or close the issue?

**Comment by JosephineKwa** [comment]
We could close the issue, its just a false alarm

**Comment by junhaoyap** [comment]
No worries, all in order and we all learned something new!

@damithc you might be interested to know that since this is closed we no longer have any urgent bug to fix before deployment.
