### ISSUE TITLE
Replace jQuery.fn.reverse with an existing jQuery function

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3878]
Instead of adding a function to modify the jQuery object that we definitely do not own, we can abstract it into a helper function (say common.js) and use it there instead.

**Comment by wkurniawan07** [comment]
The function defined is not even necessary. There's a jQuery workaround to make it work. Changing the issue title.

**Comment by junhaoyap** [comment]
@wkurniawan07 Alright! Thanks for digging into some of the issues I opened and fixing them :)
