### ISSUE TITLE
Sort buttons does not render properly on all screen sizes on Instructor Home

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3907]
Does not render properly on some screen sizes, it does on mine but not on @kanghj

**Comment by junhaoyap** [comment]
![screen shot 2015-07-08 at 1 15 58 pm](https://cloud.githubusercontent.com/assets/6291947/8563623/938b149c-2574-11e5-8d64-98d0183a5dbb.png)

**Comment by kanghj** [comment]
![kanghjscreen](https://cloud.githubusercontent.com/assets/2216119/8564941/6029f604-2583-11e5-927b-0cd8a2cc6eda.PNG)

This is how it looks like on my screen

**Comment by kanghj** [comment]
Let's fix this! @bamboo3250

**Comment by bamboo3250** [comment]
How about we change it to this?

![screen shot 2015-08-03 at 4 39 29 pm](https://cloud.githubusercontent.com/assets/8078323/9033927/611fb460-39fe-11e5-8fa9-3f3f3514ca96.png)
