### ISSUE TITLE
"Add New Course" button missing for newly added instructor

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3909]
![noaddnewcoursebutton](https://cloud.githubusercontent.com/assets/2216119/8564357/a76baa22-257d-11e5-9e89-0a34c68fc689.PNG)

For a new instructor added by the admin, the instructor home page does not have the "Add new course" button

The old page had this:

![old](https://cloud.githubusercontent.com/assets/2216119/8564391/03f875c2-257e-11e5-9498-85c4ef4e64e7.PNG)

[Edit] If we cannot get the button back easily, maybe we can update the status message for new instructors and provide a link to add a new course.

**Comment by junhaoyap** [comment]
Yeah I removed it because it didn't fit with the standardized search bar look, I put it into the sort tag so that it could be aligned with the other buttons and not jump around the page due to different screen sizes, I forgot to open an issue to discuss about how we should handle it, thanks!

**Comment by junhaoyap** [comment]
@damithc what do you think?

**Comment by yj-soh** [comment]
As it's in the sort tag somehow, this happens if `unarchivedCoursesCount <= 1` on `instructorHome.jsp`.
Honestly, I don't see much need for the button anyway, as it is merely a link for the courses page which can be found in the navigation bar for every page.

**Comment by damithc** [comment]
I'd rather keep the button because it is a 'primary action' that should be 'in your face' and not hidden away in a menu. I don't mind if you put it close to sort buttons. However, putting it inside sort tag may not be right. Have as a separate tag?

**Comment by junhaoyap** [comment]
Can look into this soon, we need to fix this before we deploy. We can make the page look more neat by changing this

![screen shot 2015-07-10 at 11 27 34 am](https://cloud.githubusercontent.com/assets/6291947/8611627/b5cd2de6-26f6-11e5-95de-2c2146db2025.png)

such that the sort button is always on the left (and if there is nothing to sort, we leave them there but leave them disabled) and the add new course button on the right. This should solve the displaying problems and also make it look more neat and not have things that are sometimes there and are sometimes not there (could confuse users).

**Comment by damithc** [comment]
Our policy is to disable unusable UI elements rather than hide. Seems the old sort buttons don't follow that policy.

**Comment by junhaoyap** [comment]
Indeed, I find it less confusing if elements are disabled rather than hidden, it might be surprising if certain conditions make some elements appear and some not, rather than let users guess we should show it to them and if they can't use it, disable them. I'll handle this after I'm done with the last JSTL thing I'm handling so that the next deployment can be done for JSTL.

**Comment by kanghj** [comment]
I just realised this isn't completed yet. @yj-soh, do you want to fix this? or @bamboo3250, since you just worked on this page yesterday.

**Comment by damithc** [comment]
Yup, I prefer if the sort bar appears for new instructors with the sort buttons disabled.

**Comment by damithc** [comment]
Raising priority. Should be fixed by next release.

**Comment by bamboo3250** [comment]
Why do we have to hide the sort button when `number of courses <= 1` anyway? I think it still makes sense to show the sort button in that case.

**Comment by damithc** [comment]
Yes, should be shown. Should be disabled because it doesn't make sense to sort 0 or 1 items.
