### ISSUE TITLE
Show course instructors on clicking 'View' in Instructor Home Page and Instructor Course Page

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#3912]
The 'View' button shows the students enrolled in the course but does not show instructors. In order to see instructors, the instructor has to click the 'Edit' button.

**Comment by taniach** [comment]
<img width="1162" alt="screen shot 2015-07-08 at 2 55 15 pm" src="https://cloud.githubusercontent.com/assets/7547452/8564917/22e3ae3e-2583-11e5-9917-82e29134d30b.png">

Clicking the 'View' button above should display the instructors and students of the course.

**Comment by bamboo3250** [comment]
I think there is instructor list in Course Details. 

![coursedetails](https://cloud.githubusercontent.com/assets/8078323/8614476/f66ce1f6-2724-11e5-8500-7a49a94450fd.png)
