### ISSUE TITLE
Show a panel body for an empty course in InstructorHome

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3917]
![emptycourse](https://cloud.githubusercontent.com/assets/2216119/8565197/ced7f9a0-2585-11e5-8cf3-15c5bf3b81eb.PNG)

It currently has no panel body, which looks weird.

**Comment by bamboo3250** [comment]
I think we have the same issue here #2346

**Comment by kanghj** [comment]
You are right. Closing this
