### ISSUE TITLE
InstructorFeedbacks: a failure to copy a feedback session should not redirect the user

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3919]
When using the "copy to" button from the instructorFeedbacks page, if the copy fails, currently the user is redirected to the page for editing the copied feedback session. The correct behaviour would be to remain on the instructorFeedbacks page

**Comment by taniach** [comment]
It redirects to InstructorFeedbackEditPage for 'copy' in the InstructorHome also. I will fix it in this issue.
