### ISSUE TITLE
Speed up tests by serving local files when running local dev environment

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3923]
It seems to have slowed down by a huge margin, we could try to investigate the issue.

**Comment by damithc** [comment]
We do have more tests but those should not take much extra time. The previous impression was that JSTL speeds up things. :-p

**Comment by junhaoyap** [comment]
Going to try and see if can load libraries via local for dev server using a PR to this issue

**Comment by junhaoyap** [comment]
Updated issue name, will start.
