### ISSUE TITLE
instructorFeedbackEdit: new question type shows a blank option on Internet Explorer

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3927]
![blankoption](https://cloud.githubusercontent.com/assets/2216119/8573777/fbb9f2d0-25c5-11e5-8e34-3a260ec555e1.png)

Between "Distribute Points (among recipient)", and "team contribution", there is an empty space.

**Comment by damithc** [comment]
@kanghj is this still happening?

**Comment by kanghj** [comment]
The fix for #2954 fixed this. Closing.
