### ISSUE TITLE
Tests failing due to motd

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3932]
These tests are failing. Note that we cannot expect to have a specific value for the motd in `build.properties` during testing because I use the same `build.properties` file for deploying to the live server.
AdminHomePageUiTest
FeedbackRubricQuestionUiTest
StudentFeedbackSubmitPageUiTest

**Comment by junhaoyap** [comment]
We can make the comparison ignore the MOTD div to do this since it isn't "static"
