### ISSUE TITLE
Instructor Course Details Page shows table header with no body if there are no students

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#3933]
Display "No students enrolled" instead of table header when no students are enrolled

<img width="1164" alt="screen shot 2015-07-09 at 1 07 51 pm" src="https://cloud.githubusercontent.com/assets/7547452/8588342/94930468-263b-11e5-8223-4f08f8451b43.png">

**Comment by damithc** [comment]
I prefer to show an empty table with the appropriate status message (as opposed to not showing the table at all). The empty table tells the user 'what you will see here if there were students' which helps the user to learn the behavior of the software.
