### ISSUE TITLE
Control the test timeout values from test.properties

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3934]
Not only does this standardize and get rid of those magic numbers, this also allows us to control the timeout value as we wish according to CPU power/memory availability.

**Comment by damithc** [comment]
I like it. But note that this approach assumes all timeouts are similar. Are there cases where we need to wait longer than usual?

**Comment by wkurniawan07** [comment]
Not that I know of, so far.
Anyway, if such is needed, we can always use one base timeout value (feed from `test.properties`) and tweak from `TestProperties.java`, e.g setting another variable `TEST_TIMEOUT_LONGER` or something like that.

**Comment by wkurniawan07** [comment]
In fact, 15 seconds is already the upper limit of all the timeout values I gathered.

**Comment by ngzhian** [comment]
Can we keep the old method which takes a timeout? Callers can then choose to specify their timeout if needed. In normal cases they wouldn't, and we can just delegate with a default time out, per the test properties.

**Comment by wkurniawan07** [comment]
I appreciate your input, but letting callers specify their own timeout is precisely why all these magic numbers get strewn around.
One alternative way is what I mentioned above and encapsulate them in a Java enum (e.g `TimeoutValue.SHORT` etc.), but I haven't seen the need to do them as of now.

**Comment by ngzhian** [comment]
Interesting viewpoint. My perspective is that not having an easier way to call the test, i.e. have a default timeout, is causing the magic numbers.

```java
waitForElementPresence(By element) {
    waitForElementPresence(element, TestProperties.inst().TEST_TIMEOUT)
}
waitForElementPresence(By element, int timeOutInSeconds) {}
```
If we have 2 ways of calling it, most callers will choose the easier way, whereas a minority can specify the exact timeout they want.

Of course I am much, much less familiar with the code base and have not done any experiments like you have. Thanks for our feedback!

**Comment by damithc** [comment]
Having an alternative where the caller can specify the limit is certainly a useful option. Enumerating some possible values is also a good idea. Going by the [KISS principle](https://people.apache.org/~fhanik/kiss.html) and the [YAGNI principle](http://martinfowler.com/bliki/Yagni.html), let's not go down those paths until we really need them.
