### ISSUE TITLE
Custom role gives all privileges when adding a new instructor

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#3946]
The `tunePermissionsDivForInstructor` is shown for existing instructors but not for new instructor when clicking on Custom radio button.

![existinginstructor](https://cloud.githubusercontent.com/assets/8078323/8613562/5fb6d8d8-271b-11e5-942d-e11ca52ed394.png)
![newinstructor](https://cloud.githubusercontent.com/assets/8078323/8613568/63bbb944-271b-11e5-9d0c-4181d7157610.png)

@damithc is this an expected behavior?

**Comment by damithc** [comment]
It is not ideal, but acceptable, to add the 'custom' level instructor without any permissions and then add permissions later. However, in the live version the instructor is added with all permissions (contrary to what's mentioned under 'custom' option), so there seems to be a bug. We should fix it. For simplicity, we can add without any permissions and immediately direct the user to give the required permissions.
