### ISSUE TITLE
Flawed logic in InstructorStudentRecords comment visibility for recipient's section

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3948]
Currently, if the student comment is not visible to the section, the visibility option will not be rendered.
However, isn't this logic flawed? How can, then, one make the comment visible to the section if s/he wishes to?
In another page, InstructorComments, that visibility option is rendered if the comment is targeted to anyone other than the whole course (i.e one person, one team, or one section). I believe that this is the correct logic.
And since the InstructorStudentRecords only shows comments targeted to one person, that visibility option (to the recipient's section) _should always_ be rendered.

**Comment by wkurniawan07** [comment]
This is the commit that added the logic I mentioned above e781df7
@kai33 can you explain if there are reasons behind it?

**Comment by kai33** [comment]
caused by out of sync. pls help to sync it like InstructorComments. :+1:

**Comment by wkurniawan07** [comment]
Just as I suspected, then. PR is already there, if you wish to review :+1:

**Comment by kai33** [comment]
looks good, go ahead : )
