### ISSUE TITLE
instructorCourseDetailsPage: give a link to enroll students if there are no students 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3966]
![givealinktoenroll](https://cloud.githubusercontent.com/assets/2216119/8645169/8ea80c62-2977-11e5-9f05-235ab5ac6972.PNG)

We can add a link to the enrolment page in the status message

**Comment by unyoungwax** [comment]
Is this okay?

![screenshot](https://cloud.githubusercontent.com/assets/10228385/12016736/aef569ec-ad89-11e5-80f5-d24c167acfdd.jpg)

**Comment by damithc** [comment]
Yes, looks fine.
