### ISSUE TITLE
Title should not be data-original on our HTML template

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3983]
Jumping the gun by doing what bootstrap does, we should just leave it as title="tooltip text" and let the bootstrap .tooltip() function do it's job.

Will upload a screenshot when I can.

**Comment by junhaoyap** [comment]
![screen shot 2015-07-15 at 4 25 38 pm](https://cloud.githubusercontent.com/assets/6291947/8714256/7ab07d18-2ba5-11e5-8f73-ad3b084bd694.png)

**Comment by wkurniawan07** [comment]
Renamed the issue because this violation is also found in few other places.
