### ISSUE TITLE
Non-conformant HTML inline styling in instructorFeedbackResponseCommentsLoad

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3984]
One element cannot have two style attributes, if so the browser gets to decide how to interpret it, leading to results that we won't be able to predict.

Will upload a screenshot when I can.

**Comment by wkurniawan07** [comment]
Aha, is this the black text color and white background? I encountered (and fixed) one of this quite some time ago. Symptoms of copying and pasting without thinking, eh? :smirk:

**Comment by junhaoyap** [comment]
Yeah, something like that, we shouldn't have inline-styling but having double attributes is worst than inline styling :P

**Comment by junhaoyap** [comment]
![screen shot 2015-07-15 at 4 29 31 pm](https://cloud.githubusercontent.com/assets/6291947/8714259/833da636-2ba5-11e5-9c36-729c93c9f24a.png)

**Comment by wkurniawan07** [comment]
This is fixed after JSTL migration, so closing.
