### ISSUE TITLE
Status message for 'Add new course' should say spaces are not allowed in course ID

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#3991]
<img width="1168" alt="screen shot 2015-07-16 at 2 37 18 pm" src="https://cloud.githubusercontent.com/assets/7547452/8716919/56c0735e-2bc8-11e5-83e1-dc83ff0a4bdd.png">

The course ID cannot contain spaces, but an instructor adding a course may not know that he is getting an error because of spaces.

E.g. Please use only alphabets, numbers, dots, hyphens, underscores and dollar signs in course ID. Spaces are not allowed for course ID.

**Comment by damithc** [comment]
This requires changes to test cases, so probably too much for a first timer.

**Comment by junhaoyap** [comment]
Or, we could trim spaces for them, which is a better solution? @damithc

**Comment by damithc** [comment]
Yes, we should trim spaces at the end or at the beginning (I think we already do), but we should not auto-remove spaces in the middle.

**Comment by junhaoyap** [comment]
I see, I'll look into it one of these days then :)

**Comment by junhaoyap** [comment]
@damithc let's have this for v5.55 since it's p.high, have a few others ongoing for v5.54 at the moment.
