### ISSUE TITLE
Investigate cause of timeout(s) during testing

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#4016]
After our JSTL migration, there seems to be more frequent Selenium timeouts, we should find some time to investigate.

At one point, we were facing 0-2 reds per entire test suite runs, but now we can encounter up to 5-7 Selenium timeouts within one run.

We should improve on that and not let it spiral out of control.

**Comment by junhaoyap** [comment]
Sometimes might not be timeout, sometimes may be element not visible exception but it's similar in that the tests may not have been written properly (maybe rushed?) and do not wait at all, we should always have some sort of implicit wait for elements whenever we try to deal with WebElements since implicit waits return early when the element has been found. Better than a red error :)

**Comment by damithc** [comment]
Issue too general. closing.
