### ISSUE TITLE
Bug in the line 843 in AppPage.java

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#4029]
![screen shot 2015-07-28 at 4 53 36 pm](https://cloud.githubusercontent.com/assets/8078323/8927337/51ad5fc8-3549-11e5-85ca-5b0a839afe7e.png)

Here it assumes that the parameter `by` is `By.id` but it can be `By.cssSelector`, which will make it fail, or any other types of By as well.

**Comment by damithc** [comment]
Is it affecting any tests?

**Comment by bamboo3250** [comment]
It hasn't affected any test yet but this is a potential bug due to the absence of input verification. For now, all the test still use it correctly but someone may misuse it, for example using `By.cssSelector` instead of `By.id`.

**Comment by wkurniawan07** [comment]
Closing as this method has been decommissioned.
