### ISSUE TITLE
Change the time formatting for FeedbackResponseComments to follow Comments

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4032]
To make both types of comments more standardized. `Const.SystemParams.COMMENTS_SIMPLE_DATE_FORMATTER` is there and ready to be re-used.

**Comment by kai33** [comment]
SimpleDateFormat is not thread-safe, it will mess the date display when multiple users are viewing the page.
ref: http://stackoverflow.com/a/6840856
pls fix it before apply this formatter

**Comment by JosephineKwa** [comment]
After fixing #4055, use `TimeHelper.formatDateTimeForComments(dateToBeFormatted)` instead of `Const.SystemParams.COMMENTS_SIMPLE_DATE_FORMATTER.format(dateToBeFormatted)`
