### ISSUE TITLE
Standardize verifyHtmlPart() in AppPage.java

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#4035]
The way it is implemented now:
1. Get the target element by web driver => get the HTML representation of the element. (actual)
2. Get the entire page source in HTML output => find the element by its Id => get the HTML representation of the element. (expected)
3. Compare actual result and expected result.

But it could be better (or more consistent) by this way:
1. Get the entire page source by web driver => find the element by its Id => get the HTML representation of the element. (actual)
2. Get the entire page source in HTML output => find the element by its Id => get the HTML representation of the element. (expected)
3. Compare actual result and expected result.

The only difference is the first step to get source code to generate DOM Document.

**Comment by kanghj** [comment]
Maybe one enhancement you can make to improve the handling of our "{*}" values, is to copy the actual value of the wildcard on the actual html into the expected html. Currently, the lines with {*} always appear different in the diff, making it hard to isolate the real differences on the tests with many wildcards, such as the results page. This might cause the comparison to take a longer time though, so maybe its not worth it.

**Comment by damithc** [comment]
Both good suggestions. May be can do as two separate issues?
