### ISSUE TITLE
COMMENTS_SIMPLE_DATE_FORMATTER will mess date display or break down page

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/repo#4055]
a static formatter is defined here:
https://github.com/TEAMMATES/repo/blob/master/src/main/java/teammates/common/util/Const.java#L35

SimpleDateFormat (this formatter) is not thread-safe, it will mess the date display or randomly break down the page when multiple users are viewing pages that use this formatter.
ref: http://stackoverflow.com/a/6840856

**Comment by kai33** [comment]
#4032 linked

**Comment by damithc** [comment]
Replace constant with a factory method that returns a new instance every time?

**Comment by kai33** [comment]
@JosephineKwa
