### ISSUE TITLE
Remove unnecessary console.logs from JS files

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4072]
#3942's sibling. Did a workspace search and found quite a handful of them.
One of the sources of logging is when AJAX request fails. It does tell the user that something is wrong, but only if the user opens developer's console and also not useful for anything else because all it does is logging 'AJAX request failed'. Should this behavior continue or should this be fixed?

**Comment by damithc** [comment]
Should be fixed.

**Comment by wkurniawan07** [comment]
We don't actually handle AJAX request failures. Then only two ways to fix this as of now:
1. Just remove the logging since it's hardly useful
2. Log more informative message. As shown by [this doc](http://api.jquery.com/jquery.ajax/), jQuery's error function can show us a few useful information.

**Comment by damithc** [comment]
Yes, we need a good way to handle ajax failures. In most cases the user need to know. When loading session stats (instructor home page), we show 'failed, try again' link if the stats fail to load.

**Comment by wkurniawan07** [comment]
Ok, then I presume that `console.log` is not the way to go. As far as this issue is concerned, I'll just remove the `console.log` that logs AJAX failures and open a new issue regarding AJAX failure handling.

**Comment by damithc** [comment]
Sure. Link to this issue so that we know from where the logs were removed and need to be replaced by error handlers.
