### ISSUE TITLE
StudentFeedbackSubmitPageUiTest is failing due to MOTD

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4087]
Reproduce by changing the motd property in the build.properties

**Comment by damithc** [comment]
This one too FeedbackRubricQuestionUiTest

**Comment by damithc** [comment]
and this one AdminHomePageUiTest

**Comment by taniach** [comment]
Does it fail after adding `app.student.motd.url = test-student-motd.html` in `build.properties`?

**Comment by kanghj** [comment]
Need to modify HtmlHelper's isMotdComponent to reflect the changes in #4068

**Comment by taniach** [comment]
It fails because HtmlHelper checked for `closeMotd` to verify it is a MotdComponent but this keyword is not there anymore in the script.
