### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing due to profile pic

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4088]
`257:  resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html");`

This is the line that is different in the output
`<div class="middlealign profile-pic-icon-hover inline panel-heading-text" data-link="&#x2f;page&#x2f;studentProfilePic?studentemail=4CCD18ECACD5C02DE3C04C4EB367151E9B0111C7A210827C3483EB1FDF471977&amp;courseid=D93B9367EC9DCCC6492ECD35D45B84493E65D61ADFE7BA9C8051233DF6242AF0&amp;user=CFResultsUiT.instr" data-original-title="" title="">`

**Comment by kanghj** [comment]
Did the html modifications manually this morning, missed that out

**Comment by kanghj** [comment]
Will regenerate all the instructor results page ui test's html
