### ISSUE TITLE
FeedbackRubricQuestionUiTest due to cell-hover

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4093]
`143:         submitPage.verifyHtmlMainContent("/studentFeedbackSubmitPageRubricSuccess.html");`

![image](https://cloud.githubusercontent.com/assets/1673303/9084611/147397c0-3ba8-11e5-8ccd-9c2dbf0b9a0e.png)

**Comment by damithc** [comment]
Got it to pass once, but failed every other time, both on dev server and remote server

**Comment by kanghj** [comment]
Can't seem to replicate this on both dev and staging

**Comment by damithc** [comment]
What can be the cause? Browser quirk? Computer too fast/slow?

**Comment by kanghj** [comment]
The cell-hover class appears if the mouse cursor is above it, so it might be caused if you are hovering your mouse over firefox as the test runs, although I tried that and the test still passed.

**Comment by damithc** [comment]
I tried that. I kept the mouse pointer in my other monitor all the time the test was running. Failed all the same. :-p @taniach @bamboo3250 @yj-soh can you pass this one on your comp?

**Comment by bamboo3250** [comment]
I ran twice and all passed for me.

**Comment by damithc** [comment]
It's just me then.

**Comment by taniach** [comment]
It passes on my computer.

**Comment by junhaoyap** [comment]
Sometimes, these randomness can be whether or not the window is currently in focus, damith you could try once with the window in focus and once without and see if it produces the same result (failures).

**Comment by damithc** [comment]
Closing because duplicate #3640
