### ISSUE TITLE
instructorHome: sort buttons overflow

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4096]
![image](https://cloud.githubusercontent.com/assets/1673303/9086973/7e83cdda-3bba-11e5-9524-ca427ce2518f.png)

**Comment by taniach** [comment]
@bamboo3250 is already working on this

**Comment by damithc** [comment]
Oh? better fix it soon @bamboo3250 It's in the home page and looks damn ugly.

**Comment by junhaoyap** [comment]
Odd, I thought this was fixed by someone before :\

**Comment by bamboo3250** [comment]
I posted the screenshot of the fix here #3907 If it looks okay, I can push the fix now.
