### ISSUE TITLE
Big sessions with low responses cannot load

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4098]
Usually, if the number of responses is big, we abort trying to generate the full report and ask the user to view by sections. But when there are no responses, we try to generate the empty table which hits the time limit. 

The very user who wants to moderate empty responses has 70 students and 15 questions (mostly team questions) and 0 responses. But she can't reach the results page due to the problem mentioned above.

**Comment by kanghj** [comment]
We could keep track of the count of empty response rows getting generated, and terminate early if it exceeds some amount, then setting the remaining question tables to load by ajax.

Alternatively, we can make it an option beside each question table to display the missing response rows. So the default would be to not generate the missing responses, and we reload the question table by ajax (this time with the missing responses) when the user clicks on the option.

**Comment by damithc** [comment]
I prefer the option idea because it will not slow down users who don't need to see the empty responses. How long will it take to implement?

**Comment by kanghj** [comment]
I can try to finish it by tomorrow, I think.

**Comment by damithc** [comment]
Great.

**Comment by damithc** [comment]
An faster solution is to show the 'moderate' button in the list of students who did not submit? The option to show empty rows can be added in the next release. What do you think?

**Comment by kanghj** [comment]
Ok, will revert #4046

**Comment by kanghj** [comment]
![moderateonnoresponsepanel](https://cloud.githubusercontent.com/assets/2216119/9102625/1b3054ac-3c27-11e5-814e-2f733de093ad.PNG)

**Comment by damithc** [comment]
For the button, use the same color as the other moderate buttons. By the way, should we rename this button to 'submit responses'?

**Comment by kanghj** [comment]
![moderateonnoresponsepanel1](https://cloud.githubusercontent.com/assets/2216119/9102773/14b87dfa-3c29-11e5-881c-59e1c0704b15.PNG)

Usually when we show the moderate button on the table rows, we use blue. But we use grey on the missing participant's panels on the other views.

**Comment by damithc** [comment]
We'll use grey here as well, as the whole table is grey.
