### ISSUE TITLE
InstructorHomePageUiTest fails on the remote server due to using cdn

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4109]
The link for jquery js files are different when running on a remote server.
![image](https://cloud.githubusercontent.com/assets/1673303/9105675/724d103e-3c4c-11e5-9b0f-998b63db1f96.png)

**Comment by wkurniawan07** [comment]
@junhaoyap and I already expected this when doing #3938. The links are wild-carded and should't be the cause of the problem. Should be something else on the page.

**Comment by damithc** [comment]
Yes, it was something else, and not reproducible. closing.
