### ISSUE TITLE
JSTL version is slower

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4113]
Compared to jsp version, jstl version seems about 20-30% slower in best case, and 100% or more slower in worst case.
This becomes noticeable when there is more data, not so noticeable in tests. 
Need to be improved before releasing.

**Comment by yj-soh** [comment]
Does this affect only certain pages or is it everywhere?

**Comment by damithc** [comment]
Seems to be everywhere but noticeable most in Results pages.

**Comment by yj-soh** [comment]
Where was this slow down measured?
Could it be due to the file size rather than the objects creation?
JSTL introduces many blank lines into the generated HTML which inflates to a somewhat ridiculous amount when placed in a deeply nested loop.

**Comment by damithc** [comment]
Hong Jin some measurements and found the bulk of the extra time (for results pages) goes into converting results bundle into page data. We may need more systematic profiling to find out exactly what is taking the extra time.

**Comment by wkurniawan07** [comment]
I'm guessing it's because of the template classes. Before, the page data are just bunch of data bundles but now they're converted to templates.

**Comment by damithc** [comment]
templates?

**Comment by taniach** [comment]
The data is converted to classes like `FeedbackResultsTable`, `FeedbackResultsRow`. When there is a large amount of data, parsing can take a lot of time as it goes through for loops. Also, some template classes have a lot of nesting: group of tables -> one table -> rows -> actions -> buttons

**Comment by damithc** [comment]
Oh, those are the template classes? Not sure if that is a good name. Anyway, yes, creating lot of objects is going to slow down things. Still, it is better to find out using a profiler than just guess and do trial and error solutions.

**Comment by damithc** [comment]
Observations after recent optimizations, using my own live data, instructor pages:
Most pages (Courses, CourseView, Serach, Records, Home) are only slightly slower, about 1-2s. It is still a significant slowdown but seems not critical.
Results pages are slightly better than the initial jstl version, but still slower by 2s-10s depending on data size. I guess it is to be expected given the high nesting of data and high amount of data. 
Is it possible to load results incrementally? i.e. load the page structure first and then load each question using ajax? That way, the user might not feel the slow-down.

**Comment by damithc** [comment]
Closing now. Performance is no longer an issue although it can be improved.
