### ISSUE TITLE
Reduce calls to getQuestionDetails and getStudentProfilePictureLink

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4114]
The repeated getQuestionDetails were causing the bulk of the slowdown on the .java side of things. The repeated getStudentProfilePictureLink were slow even on the old pure jsp files. 

On a page that took 6s to load on the old page, the above improvements reduced the page load times from ~25s to about 8s. Now the bulk of the slowdown is caused by the tag files.

**Comment by damithc** [comment]
I can live with 1-2s extra on account of jstl tags, and consider it the price of extra maintainability, at least until we find a way to improve it further :-)

**Comment by kanghj** [comment]
From the profiler, the action now only takes 32% of the time taken. Unfortunately, the profiler's output for the jsp and jstl methods is hard to interpret, so I'm finding it hard to see what's slow there now.

**Comment by wkurniawan07** [comment]
What's this profiler that's used?

**Comment by damithc** [comment]
It will be hard to profile jsp/jstl part. So we'll do the best we can with the rest and then do trial-and-error to optimize the jstl part if we can't find any way to figure out the bottle neck. Meanwhile, may be merge the current fix so that I can try it on live data?

**Comment by kanghj** [comment]
I used YourKit, not sure if it's the best tool, but it's advertised on the frontpage of our repository. Still waiting for it to be reviewed. I won't have access to my computer until tomorrow morning so I'll merge it in if it passed review by then.
