### ISSUE TITLE
"Data Persistence was Checked Twice in This Request" when running AdminHomePageUiTest

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#4116]
This line happens randomly, making the test fail.

![screen shot 2015-08-08 at 7 37 13 pm](https://cloud.githubusercontent.com/assets/8078323/9150307/19bf689e-3e05-11e5-9894-e094127439d6.png)

**Comment by damithc** [comment]
I think it is a built in safety mechanism to counter problems caused by eventual consistency (data takes times to persist). May be put a wildcard?
