### ISSUE TITLE
admin: all recent activities are not loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4137]
When I search for a student and then click the 'view recent activities' button, it loads a few and then the rest continue to show the ajax loader gif. If I use the older jsp version it loads more activities. 
![image](https://cloud.githubusercontent.com/assets/1673303/9346917/26745de4-4655-11e5-8a67-054406470f13.png)

**Comment by bamboo3250** [comment]
@damithc do you see any error or exception in Java side and Javascript side? Even the old jsp version doesn't work for me in dev server.

**Comment by wkurniawan07** [comment]
@bamboo3250 I think you'll run into #4027 if you test in dev server.

**Comment by bamboo3250** [comment]
@damithc Have you tried deploying the latest commit? It works on staging server for me.

![screen shot 2015-08-19 at 8 42 16 pm](https://cloud.githubusercontent.com/assets/8078323/9356402/14740f46-46b3-11e5-89c0-2984ea67a9e0.png)
![screen shot 2015-08-19 at 8 42 21 pm](https://cloud.githubusercontent.com/assets/8078323/9356406/1695ae42-46b3-11e5-914d-8a53cb49abd2.png)

**Comment by damithc** [comment]
Yes, the latest version seems to work. closing.
