### ISSUE TITLE
No filter for response comments in InstructorSearch

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/repo#4139]
Originally there's a filter that filters out the response comment based on its visibility options in jsp,
e.g. https://github.com/TEAMMATES/repo/blob/0be1936562434d35e5841b47ded1f5b73151ed90/src/main/webapp/jsp/instructorSearch.jsp#L160

but when converted to JSTL, this part is removed. This filter should be extracted to InstructorSearchPageAction and add test to guard it.

Visibility Impact:
When instructor unchecked the response comment's visibility option for instructor (other instructor or tutor should not be able to see), other instructor or tutor still can search for it.

@wkurniawan07 @JosephineKwa

**Comment by damithc** [comment]
Raising to `urgent` because this concerns privacy and we can't release unless it is fixed.

**Comment by wkurniawan07** [comment]
The filtering part is not removed, but indeed is changed and becomes wrong.
I wasn't the one working on migrating this before, but I think I'm able to fix this.
