### ISSUE TITLE
InstructorHomePageUiTest failing on dev

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#4162]
Fails on line 375 with:
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"button_fscopy-CHomeUiT.CS2104-First Feedback Session"}

Anyone else getting this?
This may have to do with loading the home page by ajax, need to wait for element to appear.

**Comment by damithc** [comment]
It passed on dev the last time I ran it (yesterday afternoon).

**Comment by wkurniawan07** [comment]
I recalled seeing such exception every now and then (not very often), but not sure if it's from home page. Will check later.

**Comment by LowWeiLin** [comment]
I tried on a few commits, it fails consistently after #4149 (loading home page by ajax) was merged

**Comment by yj-soh** [comment]
I did pass it without any difficulty when I tested before merging.

It may be dependent on lag, though, so maybe we should put some kind of
wait before those?

**Comment by LowWeiLin** [comment]
Yes, my com is probably running the test before the ajax loads. I'll fix this since I can replicate it consistently.
