### ISSUE TITLE
StudentFeedbackQuestionSubmitPageUiTest failing on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4176]
![image](https://cloud.githubusercontent.com/assets/1673303/9510861/ec527124-4ca2-11e5-9405-0b5696dfad9c.png)

**Comment by damithc** [comment]
InstructorFeedbackQuestionSubmitPageUiTest Failing for similar reasons. @taniach related to status message?

**Comment by junhaoyap** [comment]
Might be a JavaScript error, the above comparison error means that bootstrap's JavaScript that turns title="something" -> data-original-title="something" did not get to run on the page.

**Comment by damithc** [comment]
Can it be a timing thing?

**Comment by taniach** [comment]
It is probably a timing error. It failed many times yesterday and passed once.

**Comment by damithc** [comment]
So may be a delay would help?

**Comment by damithc** [comment]
If it is timing issue in the test, a delay should help. But if it is timing issue in the UI (i.e. the UI is rendered differently at different times), then we need to fix it at the root. What's the effect of this anyway? Is it purely cosmetic of does it have functional implications?

**Comment by taniach** [comment]
Changing the timeout in `test.properties` doesn't work

**Comment by junhaoyap** [comment]
Check the console and see if there's any JavaScript error, an error would stop bootstrap's JavaScript from doing it's magic

**Comment by taniach** [comment]
It is the tooltip for the button 'Submit Feedback'

**Comment by taniach** [comment]
I found out why it is occurring. Earlier I used a constant in `statusMessage.js` for the navbar height to calculate the offset. Following the code review suggestions, after refactoring to calculate the navbar height on every page, it fails on particularly on these 2 pages because they don't have a navbar.

**Comment by taniach** [comment]
Shall I change it back to the fixed offset in case the status message is hidden behind the navbar?

**Comment by taniach** [comment]
Or a better way would be to calculate the navbar height only if the navbar exists i.e. not `null`

**Comment by damithc** [comment]
Do a quick fix now and we'll refine (if needed) in the next release.

**Comment by taniach** [comment]
It wasn't a timing issue. The JS was suspended midway because the navbar couldn't be found.
