### ISSUE TITLE
Admin UI tests failing

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4181]
- AdminEmailLogPageUiTest
- AdminEmailPageUiTest
- AdminSearchPageUiTest
- AdminSessionsPageUiTest

These four were added some time back (#4051 #4052 #4047 #4065) but _never_ to `testng.xml`, and now all are failing gracefully. @taniach @bamboo3250 @JosephineKwa any reason why they are not included in the full test suite?

**Comment by taniach** [comment]
The test htmls were created before the JSTL migration so when they were merged, they were passing.
@JosephineKwa @bamboo3250 Let's take the ones each one of us worked on

**Comment by taniach** [comment]
Created #4186 #4187 #4188 #4189

**Comment by wkurniawan07** [comment]
Appreciate it :+1:
Don't forget to include them in `testng.xml` this time.
