### ISSUE TITLE
Write a test case to confirm that all test cases are included in the testng.xml

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4183]
May be scan the test folders and ensure that every test class appears in the testng.xml?

**Comment by taniach** [comment]
Waiting for #4235 to be merged first

**Comment by taniach** [comment]
The following directories are tested in `testng.xml`:
* `teammates.test.cases`
* `teammates.test.cases.testdriver`
* `teammates.test.cases.ui.browsertests`

The following tests are excluded:
* `BaseComponentTestCase`
* `BaseTestCase`
* `BaseUiTestCase`
* `FeedbackQuestionUiTest`
* `GodModeTest`

@wkurniawan07 Are these tests supposed to be excluded?

**Comment by kanghj** [comment]
Fixed in pr #4245
