### ISSUE TITLE
instructor permission fine tuning doesn't work for some tutors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4206]
This link doesn't do anything. It seems to work for the the first tutor I added, but it is not working for other tutors added by my TA. This is a 'custom' setting.
![image](https://cloud.githubusercontent.com/assets/1673303/9578532/5d27e8ac-501d-11e5-9dee-7f688de5e5e4.png)

**Comment by damithc** [comment]
To add: the link toggles, but nothing happens. Sometimes, even the toggling stops.

**Comment by kanghj** [comment]
Looks like when we load the instructor permissions panel body by ajax, it's given the wrong instructor index
