### ISSUE TITLE
student submission page: no spinner for numerical scale questions on IE

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4215]
This is on IE 11. Seems to work fine on Chrome though.
![image](https://cloud.githubusercontent.com/assets/1673303/9606586/dbc1f0ca-50f6-11e5-9b73-ffaf2c79e812.png)

**Comment by yj-soh** [comment]
This appears to be [expected behaviour on IE](https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/).

Should it oppose the browser's default somehow?
I believe it's obvious enough that it is a numeric input with the "Possible values:" text on the side.

**Comment by damithc** [comment]
Doesn't make sense to make it the expected behavior. Why would they do that? More reasons to hate IE. :-p When the spinner is absent, user loses one mode of input and is more likely to try his luck by entering values such as 3.5.

**Comment by yj-soh** [comment]
While it doesn't show a spinner, IE does restrict the input, so it's not possible to type any characters aside from numerals in (including ".").
I believe it's usable enough as it is.

It is possible to use a normal input and use JS to control it, but that seems like over-engineering it.
Another alternative would be to use a range type of input, I guess? (with a slider)

**Comment by damithc** [comment]
We'll keep it as it is. Those who use IE deserves what they get :-p
