### ISSUE TITLE
Full test suite getting stuck and waiting too long

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4220]
Seems to get stuck at the same place for about 10 minutes. It eventually completes, but doubles the running time. I managed to overcome it by commenting out the body of `StudentFeedbackSubmitPageUiTest`.

**Comment by wkurniawan07** [comment]
I never got stuck at that test. I'd say it's likely to be #4221.

**Comment by damithc** [comment]
Yes, could be. The behavior is the same. I'll close for now.
