### ISSUE TITLE
InstructorFeedbackResultsPageUiTest fails and freezes at line 281

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4221]
```
resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsSortSecondSessionQuestion.html");
```
We have two random variants of the page that can be returned during test, the one that makes it pass:
![visibility_pass](https://cloud.githubusercontent.com/assets/7261051/9612413/25637782-5118-11e5-91cb-b23bfdce222f.png)
and the one that fails it:
![visibility_fail](https://cloud.githubusercontent.com/assets/7261051/9612416/2907c58c-5118-11e5-9e41-4d55498a8619.png)
Notice the two swapped names. What makes this random failure so annoying is that each time it fails, the test will just freeze (the test file has 296 wildcards in it). Killing the browser does _not_ immediately stop it. I once took the liberty to wait for it to finish, it took 25 minutes. Whut.
I am inclined to believe that this is because of #4151, because it didn't happen before and it's likely due to the names of the students in the team with no responses not sorted in any particular order (if this is true, funny that it's only those two names that are randomized, though).

**Comment by wkurniawan07** [comment]
@JosephineKwa since you're the one working on that issue, I think you're the best suited to fix this. Please look into this!

**Comment by JosephineKwa** [comment]
Sure, perhaps I'll look into it for the next milestone? Or do you need it fixed urgently?

**Comment by wkurniawan07** [comment]
I have a quick fix, so I don't need it urgently :) but I'm sure this affects other people as well so it'd be great if this can be fixed ASAP.

**Comment by damithc** [comment]
@JosephineKwa let's try to fix this by next milestone.

**Comment by wkurniawan07** [comment]
My quick fix can be cherry-picked from the branch `4221-quickfix` if needed. Of course this doesn't replace the actual fix needed.

**Comment by damithc** [comment]
This one is becoming a real pain :-p

**Comment by JosephineKwa** [comment]
I apologise, I'll look at it later today and push out a fix ASAP
