### ISSUE TITLE
loginAdminAsInstructor in DevServerLoginPage doesn't use adminUsername and adminPassword to login

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#4224]

**Comment by damithc** [comment]
Dev server doesn't need username and password right?

**Comment by bamboo3250** [comment]
Then I think we'd better remove them from the parameter?

```

**Comment by damithc** [comment]
This is an abstract method probably used for both dev server and staging server, so it has to cater for both situations. If that's not the case, can reduce.

**Comment by damithc** [comment]
Closing. @bamboo3250 reopen if necessary.
