### ISSUE TITLE
Tidy up some (rarely touched) tests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4235]
Quite a number of mess in the test package:
- `BaseTestCaseTest` tests nothing but `AssertHelper`, should be renamed.
- `PageDataTest` tests `StringHelper.truncate`, and is never called.
- `test.cases.pageobjects` doesn't exist but is written on `testng.xml`.
- `ActivityLogTest` placed in `test.cases.ui`, but `ActivityLogEntry` is a util.
- `test.automated` contains test cases. All test cases should be placed in `test.cases.*`.

After resolving all, #4183 should be easier.

**Comment by taniach** [comment]
I will wait for you to merge this before doing  #4183
