### ISSUE TITLE
GodMode changes whole file instead of only the lines that have changed

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#4237]
This is caused by spacing differences in the browsers in different computers.

**Comment by damithc** [comment]
Let's try to finish this soon. It slipped one milestone already.

**Comment by thyageshm** [comment]
ok sir

**Comment by damithc** [comment]
If this is fixed, why do I still see massive diffs in test html files in recent PRs?

**Comment by thyageshm** [comment]
sir, there are some situations where this solution will not be of use. Examples are:
1. #4340 where a new tag has been added at a higher level in the html code which changes the indentation for all the code within the tag
2. There is a change in scope of the comparison (from verifyMainContent to verifyHtml)

**Comment by thyageshm** [comment]
Oh I just found out that we can add "?w=1" to the url of the pull request file compare page to ignore white space changes

**Comment by damithc** [comment]
Yeah, that can be useful. May be add it in the dev guide (under instructions for reviewers)

**Comment by thyageshm** [comment]
ok will open an issue for it :-)
