### ISSUE TITLE
InstructorStudentListPageActionTest fails unless run alone

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4253]
When trying to get dev green, this test keeps failing until it is the only failing test. It passes only at that point.

**Comment by wkurniawan07** [comment]
It has something to do with `StudentHomePageActionTest` and `StudentCommentsPageActionTest` getting Priority.
- Those two tests fail when run as a package (without priority), but pass when run individually
- Giving `InstructorStudentListPageActionTest` a priority before those two solves the problem

As for why priority is needed, I traced it back to #2859/#2971. Unfortunately solving the actual cause (all action tests uses `typicalDataBundle.json`) is going to be cumbersome. For a quick fix, adding Priority to `InstructorStudentListPageActionTest` works.
