### ISSUE TITLE
instructorStudentsList: filtering doesn't work for some workflows

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4258]
If I untick 'all sections' and start ticking specific sections, the list of teams show teams that don't belong to the selected sections.
![image](https://cloud.githubusercontent.com/assets/1673303/9751285/5b1f5e46-56d5-11e5-8a0b-64ee27d16da3.png)

**Comment by damithc** [comment]
See my comment about adding tests.

**Comment by imouto1994** [comment]
Ok I will create tests for this issue and create another pull request

**Comment by damithc** [comment]
Can be done as a separate issue.
