### ISSUE TITLE
Remove hardcoded "defaultAdmin"

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#4262]
In BaseUiTestCase "defaultAdmin" is hardcoded. We should change to use TEST_ADMIN_ACCOUNT

**Comment by damithc** [comment]
This is causing lot of test failures in admin tests

**Comment by junhaoyap** [comment]
I vaguely remember there being a way to stub constants into the html file, can anyone help me out here?

**Comment by kanghj** [comment]
<code>${test.admin}</code> ?

**Comment by junhaoyap** [comment]
Exactly right, thanks! Got a PR ready :)
