### ISSUE TITLE
adminCreateAccount: give an option to give all data in one line

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4266]
In addition to the current form, give another form that takes 3 parameters in one box i.e. name, email, institute, separated by tabs

**Comment by damithc** [comment]
@bamboo3250 can you do this for the next milestone?

**Comment by bamboo3250** [comment]
okay, I'll take this issue. Does a checkbox to toggle between these 2 forms okay with you?

**Comment by damithc** [comment]
Actually, no need to toggle. Just put the new form above the old form.

**Comment by bamboo3250** [comment]
Does this look okay?

![screen shot 2015-09-16 at 8 23 19 pm](https://cloud.githubusercontent.com/assets/8078323/9904521/096437a2-5cb1-11e5-86b9-6dbfd3664ba6.png)

**Comment by damithc** [comment]
Yes.
