### ISSUE TITLE
Test fails on InstructorFeedbackEditPageUiTest due to datepicker element

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#4273]
Timed out after waiting 15 seconds for presence of element, it seems to be a Mac issue but I'll see how I can improve it to pass consistently across machines.

**Comment by junhaoyap** [comment]
Update on this, this passes if the test is in the foreground when it's run, it fails when the browser is not in the foreground, think something similar has happened before but it's been awhile since I last used Selenium so I'll have to sit on it and think back >.<

**Comment by junhaoyap** [comment]
This might or might not be a Mac specific issue but nonetheless fixed to consistently pass by using JavaScript executor instead of Selenium waits~

**Comment by junhaoyap** [comment]
Moving to V5.55, focusing on the higher priority issues.

**Comment by damithc** [comment]
Failing for me at line 135. Probably the same issue.

**Comment by junhaoyap** [comment]
For now, make sure the screen is in the foreground and focused and it will definitely pass, it's a little trickier than I initially thought so I'm gonna have to spend more time thinking through this

**Comment by LowWeiLin** [comment]
I think i can fix this, will create a PR for it.
