### ISSUE TITLE
instructorSessionResults: there is no way to recover from failed ajax calls

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4276]
In the per question view (may be applicable to other views too), if there are many ajax calls started automatically (e.g. 20 questions, 80 students), some of the ajax loader gifs will keep on going. I suppose those ajax calls failed for some reason (the logs say 'API failed to complete'). There is no way for the instructor to recover. 
Actually, the instructor can recover by clicking those panels again, but the user will not know that because the ajax loader is still going on.

**Comment by damithc** [comment]
Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/1673303/9840334/f971dbdc-5ac2-11e5-9bab-7cc2feab02d1.png)

**Comment by LowWeiLin** [comment]
Does clicking it again work and should we allow the user to try again?
There is some code (not working) which shows the following on failure:
"There are too many responses for this question. Please view the responses one section at a time."

**Comment by damithc** [comment]
1. Yes clicking again works and we should let users know they can recover that way. But first, we have to detect the situation.
2. I've seen that error message so that code works under certain conditions. The ajax failure in this case may not be because of too many responses. It may be due to too many requests to the server resulting in a slow down of the server. i.e. some requests start but cannot finish in time.
