### ISSUE TITLE
AdminAccountDetailsPageUiTest getting stuck 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4281]
Happened once on dev server (I suspect) and once on live server. I wonder if this is due to regex match taking too much time when the sorting order is different from the expected file (I remember a similar case earlier). Any ideas @wkurniawan07 @JosephineKwa @bamboo3250 ?

**Comment by wkurniawan07** [comment]
The test file has only 408 lines with only 2 wildcards in it. I'm quite sure that test won't get stuck even if it fails. Maybe something else?

**Comment by damithc** [comment]
I'm not sure if that was the one that got stuck in dev server, but it was definitely the one that got stuck in live server because that was the only test that did not complete. Note that the live server admin pages have a lot more data than the dev server, so the regex matcher could be facing a much bigger search space (i.e. bigger 'actual' html files).

**Comment by wkurniawan07** [comment]
I won't be so sure. The test file uses data from a json file so the data size should be the same and the 2 wildcards are the jQuery paths, so it stands to reason that the file content is the same, live or dev testing.
The one that I think has the potential to be lagging live is `AdminActivityLogPageUiTest`.

**Comment by damithc** [comment]
From what I remember, one of the pages that got stuck had live data in it. I think it was the admin->sessions page. But I could be wrong. I'll keep a lookout for a recurrence of this problem.

**Comment by bamboo3250** [comment]
As @wkurniawan07 mentioned, it's unlikely for `AdminAccountDetailsPageUiTest` to get stuck by matching the wildcard since I'm very sure that there is no live data involved in that test and those 2 wildcards belongs to the `<head>` part of the HTML source.

**Comment by damithc** [comment]
Well, something is getting stuck :-)

**Comment by junhaoyap** [comment]
If anyone else seem to get any test stuck, they could report in here and we'll see if that helps to locate the test getting stuck :)

**Comment by LowWeiLin** [comment]
AdminActivityLogPageUiTest is getting stuck for me...

**Comment by LowWeiLin** [comment]
Closing, html comparison removed in #4364, should have nothing to get stuck on now.
