### ISSUE TITLE
instructor courses page: load course list using ajax

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4284]
Similar to session page.
This should speed up the page, especially if there are many courses.

**Comment by LowWeiLin** [comment]
The slow part is having to query all of the students and calculating the number of teams, sections, registered students, total students in the course. We could perform ajax to query those similar to response rate for feedback sessions.

Another way which may be better is to keep track of these counts as we insert/update/delete students. This can be prone to consistency issues though.

**Comment by damithc** [comment]
As the first step, we can load the 'new course' form immediately and load the courses table using ajax. As the second step, we can load stats of courses using ajax requests (similar to sessions page).

**Comment by imouto1994** [comment]
@damithc Should I create another issue for using ajax for course stats ? Or should I do it also in this issue ?

**Comment by damithc** [comment]
Can do separately

-- 
Sent from a mobile device.
