### ISSUE TITLE
InstructorStudentListPageUiTest is broken on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4304]
![image](https://cloud.githubusercontent.com/assets/1673303/9894961/74744488-5c5c-11e5-857a-4001684ddd38.png)

**Comment by damithc** [comment]
Any others having this problem? I can't deploy V5.53 unless this is fixed or at least the cause is known.

**Comment by kanghj** [comment]
Seems like godmode missed out converting these hardcoded course ids to wildcards. @thyageshm

**Comment by LowWeiLin** [comment]
These don't seem like course ids we would use in tests though?

**Comment by kanghj** [comment]
They are the hashed courseIds that we use in profile picture links.

**Comment by junhaoyap** [comment]
@damithc this is the one thing that seems to always be mistakenly replaced by god mode, I think @wkurniawan07 knows about this, we need to be careful when we run godmode for this particular file, I'll let wilson explain the details? I'll open a PR to fix this soon.

**Comment by wkurniawan07** [comment]
Whoa. Saw my name here :p
Anyway, I've managed to isolate the root cause of this and it's all going to be resolved very soon.
