### ISSUE TITLE
BaseTestCase.java code for injecting real account details is inconsistent 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4305]
Unlike other accounts in the `test.properties`, admin account username is actually an email address e.g. abc@gmail.com
This breaks all admin tests.

Furthermore, it seems `BaseTestCase.java` has not been updated to inject the actual admin account 
![image](https://cloud.githubusercontent.com/assets/1673303/9895015/0acde5ba-5c5d-11e5-80d6-b1c14c5f3298.png)

**Comment by junhaoyap** [comment]
@kanghj have you started? If not I can work on it.

**Comment by junhaoyap** [comment]
@damithc,

<img width="679" alt="screen shot 2015-09-15 at 9 07 26 pm" src="https://cloud.githubusercontent.com/assets/6291947/9896220/cb489bde-5bed-11e5-85ed-531f0d9c1ccd.png">

I think @gmail.com is automatically added? The test.properties file does say to omit it.

**Comment by damithc** [comment]
Looks like my `test.properties` is outdated, so `@gmail.com` is no longer an issue. But the `BaseTestCase.java` still needs updating though. If the injecting need not be done in that class anymore because it is done somewhere else, then the code need to be removed. It looks weird that some values are injected here, but not all.

**Comment by junhaoyap** [comment]
@damithc it's now being injected here in HTMLHelper, I don't think BaseTestCase.java does the replacement anymore but I am not 100% sure, I can do a quick patch for this and perhaps we open an issue to investigate this?

<img width="1088" alt="screen shot 2015-09-15 at 9 42 37 pm" src="https://cloud.githubusercontent.com/assets/6291947/9896555/b616c0d8-5bf2-11e5-8099-619f40820178.png">

**Comment by kanghj** [comment]
The BaseTestCase injectRealAccounts is different from the HtmlHelper method. injectRealAccounts is used to replacement values in the test data json files so we still need to update it, although I think none of the tests are using ${test.admin} in their data files now.

**Comment by junhaoyap** [comment]
Ok, @kanghj I was doing the update to the admin, I will help to do a quick patch to this, can you help me do the review and merge it in cause I need to go to bed soon :)

**Comment by kanghj** [comment]
Alright, sure :)
