### ISSUE TITLE
Remove html comparisons from Admin Ui Tests

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4314]
Would it make sense to remove them? @bamboo3250, @JosephineKwa @taniach 

Can we just specifically test for what they are supposed to be testing using selenium webelements?

**Comment by taniach** [comment]
For some pages, we test for the table headers only and not the table content.

**Comment by damithc** [comment]
Raising priority because admin tests fail often.

**Comment by taniach** [comment]
I will take AdminSearch, AdminEmail and AdminEmailLog tests.

**Comment by bamboo3250** [comment]
I will handle AdminActivityLog and AccountManagement. We can leave AdminAccountDetails as it is since it doesn't involve live data.

**Comment by JosephineKwa** [comment]
I'll work on AdminSessions which I worked on previously

**Comment by kanghj** [comment]
Removing milestone since this will be done through multiple issues: #4349, #4348, #4347, #4337 ... @bamboo3250, make issues and link to them for the 2 tests you will handle.

**Comment by wkurniawan07** [comment]
I believe this is done.
