### ISSUE TITLE
Remove html comparisons from AdminSearchPageUiTest

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#4347]

**Comment by wkurniawan07** [comment]
Correct me if I'm wrong, but I think `AdminSearchPageUiTest` has no live data in it? Should be fine even with HTML comparison.

**Comment by damithc** [comment]
I haven't looked at the test, but if it is testing the search function, I don't see how it can prevent existing data from appearing in the search results, unless we are searching for something really weird such that the chance of existing data matching the query is nil.

**Comment by taniach** [comment]
The test searches for an empty string and "student1".

**Comment by damithc** [comment]
Here's the search results for "student1" in live server
![image](https://cloud.githubusercontent.com/assets/1673303/10098426/c56c0bba-63b3-11e5-846b-90ce252e77b2.png)

**Comment by taniach** [comment]
It has some live data so I can remove the HTML comparison.

**Comment by wkurniawan07** [comment]
Ok then, I stand corrected.
