### ISSUE TITLE
Remove html comparisons from AdminEmailPageUiTest

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#4348]

**Comment by damithc** [comment]
This test is failing on live server. Test it against a remote server before merging.

**Comment by taniach** [comment]
Do you mean test the current AdminEmailPageUiTest on the staging server? I did not work on this issue yet.

**Comment by damithc** [comment]
When you do work on it, remember to test against the staging server as well

-- 
Sent from a mobile device.
