### ISSUE TITLE
Test failure diff shows place-holder variables

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4353]
The test AdminAccountManagementPageUiTest eventually passed, but when it failed at first, the diff was like this (still contained a place holder variable):
![image](https://cloud.githubusercontent.com/assets/1673303/10036538/8e80a478-61db-11e5-8d61-71ec31a35ca9.png)

**Comment by thyageshm** [comment]
Sir I believe this is expected. We are converting everything to placeholders and making the comparison. So when the actual html did not have the correct values, they were not changed to the placeholders.

**Comment by damithc** [comment]
But this makes the diff hard to make sense of, especially for new developers?

**Comment by thyageshm** [comment]
I guess it does make it harder to make sense of. We can re-insert the values before the comparison is shown. Would that be sufficient?

**Comment by damithc** [comment]
Yes. Ideally the diff should show the difference that caused the test failure.
