### ISSUE TITLE
admin activity log search: give a way to limit search period

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4370]
If the search period is not limited, it can go on searching which can drive up the bill.

**Comment by thyageshm** [comment]
sir, I believe there are "from:" and "to:" labels to limit the search period, but they are implemented after retrieving all queries fro, GAE. So shall I assume that the period will be specified in those two labels and simply limit the search query made to GAE using those values

**Comment by damithc** [comment]
I prefer if any activity log search reads no more than one day worth of log data at a time, unless I specify a period. If I want to expand the search to one more day, I can click the 'search more' link.

**Comment by thyageshm** [comment]
ok!
