### ISSUE TITLE
Long test account IDs will fail some specific tests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4372]
Some time back there's an issue with overly long `${test.admin}` failing tests. Surprisingly, all these other similar culprits managed to escape our sights:
- Long `${test.instructor}` -> `InstructorCourseJoinConfirmationPageUiTest` fails
- Long `${test.student1}` -> `StudentCourseJoinConfirmationPageUiTest` fails
- Long `${test.unreg}` -> `StudentHomePageUiTest` fails

**Comment by wkurniawan07** [comment]
@junhaoyap all the more reason why `${test.truncatedAdmin}` may not be a feasible solution, else we'll have `${test.truncatedInstructor}` etc as well.

**Comment by thyageshm** [comment]
do they fail because of the "..." at the end?

**Comment by wkurniawan07** [comment]
Yep, the same symptom as long `${test.admin}` breaking some tests.

**Comment by thyageshm** [comment]
Can't we use the same placeholder name for both the long version and the truncated version? Like run two queries in godmode and assign the same placeholder?

**Comment by wkurniawan07** [comment]
That's precisely what I'm thinking of. Don't know if there are drawbacks of this, though.
