### ISSUE TITLE
Remove redundant regex replace in processPageSourceForGodMode() in AppPage.java

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#4378]
this line in AppPage.java (line 791) is no longer needed:
```
.replaceAll(Const.ParamsNames.REGKEY + "%3D([a-zA-Z0-9]){1,}\\%", Const.ParamsNames.REGKEY + "%3D{*}\\%")
```

**Comment by damithc** [comment]
Is this issue still valid? @thyageshm @wkurniawan07 
If yes, can give to first timers?

**Comment by wkurniawan07** [comment]
Still valid, but I'm going to escalate it. There's more unnecessary lines than that one.
