### ISSUE TITLE
Tests fail when the version number has a minor component

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4409]
e.g. if the version number is V5.55.01, many UI tests fail. I suspect it is related to god mode.

**Comment by wkurniawan07** [comment]
I can't confirm until I get back in about 6 hrs, but from what I remember about God mode, it should be the case.

**Comment by thyageshm** [comment]
yes, it is because godmode doesn't support minor versions. The following code should be changed
```java
.replaceAll("V[0-9]\\.[0-9]+", "V\\${version}")
```

to 

```
.replaceAll("V[0-9]+(\\.[0-9]+)+", "V\\${version}")
```
