### ISSUE TITLE
Make the time stamp in emails unambiguous 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4419]
There is a user claiming that the email said 0600 and he wasn't sure it was am or pm. Should we use a  clearer time format in emails?

**Comment by junhaoyap** [comment]
0600 should mean 0000 - 2400, it seems the user is not familiar with the 0000 - 2400 time format, hh:mm:ss TimeZone seems to be the w3 standardized format, we could do a few of the following:

1. Follow w3 format
2. Allow users to choose what format suits them best
3. Use a designated format that most of our current users are familiar with (am / pm)

or maybe there are more possible solutions?

**Comment by damithc** [comment]
I prefer 3.

**Comment by damithc** [comment]
Another case of this. Because we don't show any indication that we are using 24 hour format, 06:00 can be mistaken for 6pm.
