### ISSUE TITLE
instructorHomePage: Show start/end date for sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4426]
This can be useful to instructors.

**Comment by damithc** [comment]
@ashrayjain may be you can take a look at this. It can be connected to usability.

**Comment by ashrayjain** [comment]
Sure.

**Comment by damithc** [comment]
Do some mockups before implementing. We need to figure out where to add it and how to show it.

**Comment by ashrayjain** [comment]
@damithc So i have a couple of ideas.

The obvious way is to just display it as another (maybe 2) column like so,
<img width="1238" alt="screen shot 2015-10-11 at 8 52 09 pm" src="https://cloud.githubusercontent.com/assets/3591327/10417034/a2b6491e-7060-11e5-9a7a-e322ecb9c306.png">

Another, slightly fancier way might be something like this, using a bootstrap progress bar,
<img width="1283" alt="screen shot 2015-10-11 at 9 39 00 pm" src="https://cloud.githubusercontent.com/assets/3591327/10417037/c3b1d638-7060-11e5-8065-63802980816a.png">

What do you think?

**Comment by damithc** [comment]
The dates should be visible without further action. It should not require a hover. So i prefer the first one. For the first one, can we make the columns sortable?
I would also show all sessions on a timeline (one for each course), but that can be a separate issue.
I also like the idea of showing the status in a more visual form (like the 2nd mockup), but not as a substitute for dates. Again, it can be a separate issue.

**Comment by ashrayjain** [comment]
Sure, the columns can be sortable. So should we finalize the 1st one then?

**Comment by damithc** [comment]
OK go ahead.

**Comment by yj-soh** [comment]
Just a random note, but would it be better to use a single column, "Duration"?
That will reduce the amount of horizontal space required.
Another idea would be to remove the year and to show the full date only on hover.

**Comment by damithc** [comment]
Removing year is fine.
I think being able to sort by either date is useful so I'd like to show as two columns.
