### ISSUE TITLE
student feedback submission: cannot see team member names

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4442]
Two students reported this. Cannot be replicated. When I go to the same submission link, I can see the names.
![image](https://cloud.githubusercontent.com/assets/1673303/10327442/e6c0888e-6cd9-11e5-9213-c7ebb98426c1.png)

**Comment by LowWeiLin** [comment]
Does this happen for the other questions as well?

**Comment by damithc** [comment]
I assume it happens to all similar questions, although the user did not specifically say it happens to all question or just a specific question. 
One user could not see names even after repeated attempts, so I assume it is not a temporary problem. Something to do with cache, resolution, browser?

**Comment by kanghj** [comment]
I'm guessing browser. The screen shot looks like Internet Explorer, but I can't replicate this on my computers version of Internet Explorer, do we have the user agent to see which version of ie the user was using?

**Comment by damithc** [comment]
The log says "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)".

**Comment by damithc** [comment]
One more case of this. Also IE10

**Comment by damithc** [comment]
Another case of this, in a rubrics question. User agent Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
![image](https://cloud.githubusercontent.com/assets/1673303/11178187/0cb099e6-8c86-11e5-952f-7c92aa021b99.png)

**Comment by damithc** [comment]
User says he is using IE11

**Comment by LowWeiLin** [comment]
Is it reproducible? Are we able to see if there are any JS errors?

**Comment by damithc** [comment]
It loads fine in my own IE 11. The screenshot was sent by the user.
