### ISSUE TITLE
Many test failures on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4443]
20+ cases fail on dev server
The diff view shows things like this, which I thought should not show up in diff view any more

![image](https://cloud.githubusercontent.com/assets/1673303/10332039/e6772b20-6d0c-11e5-80c1-11d2aa6b5be4.png)

![image](https://cloud.githubusercontent.com/assets/1673303/10332051/fe4d9176-6d0c-11e5-9b51-cf316c020afd.png)

**Comment by wkurniawan07** [comment]
@thyageshm the 2nd pic up there is why I combined the two regexes before. Then again the root cause is the magic numbers 50 and 62, I have no idea where they come from.

**Comment by damithc** [comment]
I don't think the length of the key generated by datastore is fixed. From what i remember, it can vary from instance to instance.

**Comment by thyageshm** [comment]
@wkurniawan07 I see.. I initially left it as {*} in #4402, but later decided to split it up as another questionid replace statement had 62 on it. 

@damithc will try and figure something out for this soon. With respect to your question about diff view, are you asking about why the ${} things are appearing or why the godmode comparison shows up as a diff?

**Comment by damithc** [comment]
Ignore my question. It may be irrelevant once we fix this issue.

**Comment by thyageshm** [comment]
@damithc ok!

I think I might have a solution. The following code should handle the situation where regkey is in a input box:

change
```
// regkey in unreg student page
.replaceAll("value=\"([a-zA-Z0-9-_]){50,}\"","value=\"\\${regkey\\.enc}\"")
```
to
```
// regkey in unreg student page
.replaceAll("name=\""+Const.ParamsNames.REGKEY+"\" type=\"hidden\" value=\"([a-zA-Z0-9-_]){50,}\"","name=\""+Const.ParamsNames.REGKEY+"\" type=\"hidden\" value=\"\\${regkey\\.enc}\"")
```

The above is possible as the regkey thing only happens in two html pages in StudentFeedbackSubmissionPage.

@wkurniawan07 what do you think?

**Comment by wkurniawan07** [comment]
That, and decrease the 62 lower limit for the questionid. It should work.

**Comment by thyageshm** [comment]
ok!

**Comment by damithc** [comment]
@kanghj @LowWeiLin Do another release after this is fixed. I can't release without this.
