### ISSUE TITLE
Admin Activity Log: generate unique id for each request 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4444]
Use the timestamp and user's information to generate an id and display it in the activity log page

**Comment by thyageshm** [comment]
hey @kanghj, what is the use case of this new id? Also, is this just for the display page or needs to be saved in the actual log entry as well?

**Comment by damithc** [comment]
Use case: to trace from an activity shown in admin activity log page back to the original log entry in app engine dash board (to get more info). I guess it need to be saved.

**Comment by kanghj** [comment]
It's to make it easy to cross-reference (between teammates log, google app engine's log, and the log sent to the admin's email when an error occurs) and search for the request which caused an error. It will also probably help in those cases where the request doesn't come with any parameters so we can't identify the user. I guess it should be saved in the actual log entry.

**Comment by thyageshm** [comment]
So this probably means that we have to:
1. figure out a way to store an id in the GAE log. (whether a dedicated field is possible)
2. set a standard in terms of how to generate the unique id and where to place it in the log
3. update all existing log messages to the new standard (could be done in ActivityLogEntry Class?)

Anything else?

**Comment by damithc** [comment]
Also, make sure it fails/recovers gracefully when dealing with log messages in the old format.
For 1, we already store our own fields in the log message using a special format. Something like `value ||| value ||| ...`
