### ISSUE TITLE
StudentProfilePageUiTest failing on line 89

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4450]
Can't get it to pass after repeated tries for me. But passes for @LowWeiLin.

Fails on StudentProfilePage.fillNationality due to a ElementNotVisibleException

**Comment by kanghj** [comment]
@ashrayjain, have a look? The modal for the profile picture in testContent is left open. Might be caused by that. My firefox version is 29.0

**Comment by ashrayjain** [comment]
It's passing for me on 38.0.5. You could try adding
```java
profilePage.click(By.className("close"));
```
at the end of testContent() to close the modal and see if that fixes it.

**Comment by wkurniawan07** [comment]
Happened to me as well, and the fix suggested works.
