### ISSUE TITLE
Strange words in admin activity log

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4454]
What do these words mean? Was seen on the live server.
![image](https://cloud.githubusercontent.com/assets/1673303/10393581/b5483860-6ec3-11e5-8d28-bcba66482ba5.png)

**Comment by wkurniawan07** [comment]
This is what #4417 is about.

**Comment by damithc** [comment]
I see. I couldn't figure out where the 'multiple points' came from.

**Comment by wkurniawan07** [comment]
Multiple points because the function parseDouble expects only one "point" (e.g if the version is 5.56 it is parse-able to Double, but not if 5.56.01).

**Comment by wkurniawan07** [comment]
Merged with #4417 (same cause, same remedy, whatever the remedy is going to be).
