### ISSUE TITLE
Change time stamps to 12H format

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4471]
See #4465. The time stamps in all places should use 12h instead of the current 24h format

**Comment by wkurniawan07** [comment]
Is it possible to escalate this issue into making the time formatting the same in all (or most) places? That way we don't need three separate methods `formatTime`, `formatTime12H`, and `formatDateTimeForComments`.

**Comment by LowWeiLin** [comment]
Will be removing formatTime(this is what the issue is about), will see if its possible to change the one for comments too.
