### ISSUE TITLE
Student profile picture edit: not clear how to crop

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4472]
The new cropping method requires the image to be zoomed and then dragged around, which may not be obvious. May be add arrow buttons to move the photo?
![image](https://cloud.githubusercontent.com/assets/1673303/10475241/b1e8ee40-7273-11e5-81e5-3cc83d625343.png)

**Comment by ashrayjain** [comment]
Currently, when a new image is uploaded, it is zoomed out as much as possible by default. This might be causing some confusion. Would it help if the default behaviour was that image is already zoomed in slightly?

**Comment by yj-soh** [comment]
It's unlikely anyone would realise it's possible to crop because the image is slightly zoomed in.
People would simply assume it got cropped slightly due to some other issue.
If buttons capable of hijacking that cropping functionality cannot be added, how about adding instructions instead?

**Comment by ashrayjain** [comment]
+1 for adding instructions.
Adding arrow buttons might make the interface too cumbersome if we add 4 new buttons (up, down, left, right)

**Comment by damithc** [comment]
Do both. People don't read instructions. They look for visual cues. :-p
Arrows can be added on the four sides to make it more intuitive e.g. up arrow can be above the photo.
