### ISSUE TITLE
student profile pic upload: upload button should only be enabled when there is something to upload

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4473]
The 'upload picture' button should not be enabled if there are no files selected? Another thing: The two buttons look very different.
![image](https://cloud.githubusercontent.com/assets/1673303/10475255/dc4af818-7273-11e5-85ce-22cc7bfd33b2.png)

**Comment by ashrayjain** [comment]
By default, file upload buttons look different with Bootstrap. Still, we can override it to match the other buttons. This post provides a method to do this. http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/

**Comment by thyageshm** [comment]
![with file selected](https://cloud.githubusercontent.com/assets/5160137/10604385/813f567a-7756-11e5-9e24-a29e501f9671.PNG)
![without file selected](https://cloud.githubusercontent.com/assets/5160137/10604386/8163e850-7756-11e5-91e9-0b17f67a3ddb.PNG)

Is this alright?

**Comment by damithc** [comment]
The two buttons look a bit disorganized though.

**Comment by thyageshm** [comment]
is this better?

![aligned](https://cloud.githubusercontent.com/assets/5160137/10604782/67e42374-7759-11e5-94f5-ae3685c40914.PNG)

**Comment by damithc** [comment]
Slightly, but not by much. Not sure how to make it better though. May be study other UI's that has a similar feature? Anyway, it can be done as a separate issue.

**Comment by damithc** [comment]
In fact, it sounds more like something @ashrayjain can do as part of his FYP.
