### ISSUE TITLE
InstructorFeedbackEditPage randomly fails on ajax test

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#4491]
![image](https://cloud.githubusercontent.com/assets/3910365/10570344/47d4dc62-7665-11e5-8882-ff0e828c29b3.png)

The html on the browser looks correct though.
![image](https://cloud.githubusercontent.com/assets/3910365/10570358/5f40863a-7665-11e5-8bff-3600d9406bae.png)

**Comment by damithc** [comment]
Closing because duplicate.
