### ISSUE TITLE
Upgrade to SDK 1.9.27

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4499]
As of now we are 23 SDKs (1.5 years of development time) behind the staging/live server, so I think it's about time we get ourselves updated.
I managed to upgrade without any problem, although with a (small) price to pay: the local database is not compatible and must be replaced with a new one, i.e whatever TEAMMATES data that exists in my PC are wiped out (I made a copy, so I can switch between SDKs freely, but the data between instances of different SDKs are not transferrable).
If agreed, I will come up with the upgrading guide as well, like what I did with Selenium back then.

**Comment by damithc** [comment]
Sure. I guess folks can upgrade at their own convenience. There is no need for a mass upgrade at once right?

**Comment by wkurniawan07** [comment]
Yes, no need for mass upgrade. The change in the repo settings is also very minor.
I'll make the PR now. We can wait for about one week (end of milestone 5.59) before migrating it fully, after which everyone needs to upgrade.

**Comment by damithc** [comment]
I don't think we can do this 'at our convenience'. We have to merge this PR at some point and then everyone has to migrate immediately after that. Might as well merge now? @LowWeiLin @kanghj

**Comment by wkurniawan07** [comment]
We can let everyone have a run at upgrading first and troubleshoot whenever necessary. If everyone's good to go then this is good to merge as well.
