### ISSUE TITLE
Visibility checkboxes does not match preview

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4509]
Here's the problematic question:
![image](https://cloud.githubusercontent.com/assets/1673303/10654394/45174fd0-789c-11e5-9aa5-160d2a65e11e.png)
![image](https://cloud.githubusercontent.com/assets/1673303/10654396/4f0426e4-789c-11e5-8435-54750fe129a0.png)
Here's another question in the same session but seem to work properly:
![image](https://cloud.githubusercontent.com/assets/1673303/10654409/790c3a8a-789c-11e5-9fff-5f12ad36cd31.png)
![image](https://cloud.githubusercontent.com/assets/1673303/10654410/82528f4a-789c-11e5-8924-29006bb62652.png)

**Comment by damithc** [comment]
Here's the datastore view:
![image](https://cloud.githubusercontent.com/assets/1673303/10654433/d618fd9e-789c-11e5-846e-1339c90f98db.png)

**Comment by damithc** [comment]
It happens because we hide the relevant row of checkboxes without unchecking it first.

**Comment by damithc** [comment]
As done in the PR, the better solution is to treat hidden rows as 'unchecked' when saving, not to uncheck them automatically upon hiding.

**Comment by damithc** [comment]
Guys, can you give a script to fix that question? I can't do it using the UI because changing visibility deletes responses. I can't do it using the GAE console because it doesn't allow me to edit TEXT fields.

**Comment by LowWeiLin** [comment]
The irrelevant visibility options being left on the database will not affect the visibility messages, as
V5.58.01 fixes the issue.
Would you still prefer to use a script to correct the question?

**Comment by damithc** [comment]
I see, it will not affects results either? It will be a disaster if the students see something they are not supposed to see.

**Comment by LowWeiLin** [comment]
Seems like it does affect the results currently.
@kanghj suggests removing the irrelevant options whenever feedback questions are read from the database, instead of using a script. That should prevent inconsistencies with what the visibility message says.

**Comment by damithc** [comment]
Ok, let's do that then. Let me know when it is merged to release branch.

**Comment by LowWeiLin** [comment]
@damithc merged to release branch
