### ISSUE TITLE
Student email length is limited to 45 chars

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4518]
This is a very short-sighted design decision. I don't know if there is an upper limit to email address length, but it has to allow more than 45 chars. We need to increase this immediately as one of our users is blocked by it.
Can do a hot fix quickly?

**Comment by kanghj** [comment]
The googleId field is also limited to 45 chars, do we want to change that here too?

**Comment by damithc** [comment]
Sure.

**Comment by kanghj** [comment]
Fixed by #4519
