### ISSUE TITLE
Duplicates of questions in session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4523]
One of the sessions created recently had 2 questions repeated three times, and some of them having the question numbers (there were three questions with question number 1 and there weren't even duplicates of each other).

**Comment by LowWeiLin** [comment]
Are these custom questions or the template feedback sessions?

**Comment by damithc** [comment]
All custom questions

**Comment by kanghj** [comment]
Might happen if the user got impatient, and modified the question number halfway after submitting the form to create a new question, and then re-submitting the form. Is it possible to verify if this happened from the logs?

**Comment by damithc** [comment]
Here's one of the questions he added (from the log). It is a TEXT question but some of the data looks like a rubric question. Is that intended?:
teammates.ui.controller.ControllerServlet doPost: Request received : [POST] https://teammatesv4.appspot.com/page/instructorFeedbackQuestionAdd:{showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::4, rubricNumRows::2, questiontext::What should this team member STOP doing? (not helpful to team), numofrecipientstype::max, rubricChoice-3::Strongly Disagree, mcqOption-1::, rubricDesc-0-3::Rarely or never responds., constSumOption-1::, constSumToRecipients::false, isNotSureAllowedCheck::on, rubricChoice-0::Strongly Agree, showgiverto::INSTRUCTORS, rubricDesc-0-2::Occasionally responds, but never initiates discussions., mcqOption-0::, constSumOption-0::, rubricDesc-0-1::Takes part in discussions and sometimes initiates discussions., rubricChoice-2::Disagree, rubricChoice-1::Agree, rubricDesc-0-0::Initiates discussions frequently, and engages the team., generatedOptions::NONE//NONE//NONE, questionnum::2//2, rubricSubQn-0::This student participates well in online discussions., courseid::MKT372-05410, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2, rubricDesc-1-3::Rarely or never completes tasks., numofrecipients::1, numscalestep::1, rubricDesc-1-0::Tasks are always completed before the deadline., rubricDesc-1-1::Occasionally misses deadlines., rubricDesc-1-2::Often misses deadlines., numscalemin::1, fsname::Team, msqOption-0::, recipienttype::OWN_TEAM_MEMBERS, receiverLeaderCheckbox::RECEIVER, msqOption-1::, questiontype::TEXT, numscalemax::5, givertype::STUDENTS, user::abc}

**Comment by kanghj** [comment]
Yes I think it's intended. The form for creating a new question has all the form inputs for every question, so the possible inputs for creating a rubric question should be present in the form submission. The irrelevant inputs will be ignored in the action when creating the question.

**Comment by damithc** [comment]
I see. 

This is what the user did, based on the log.
1. Create a new 'team peer evaluation' session with standard questions
2. Delete first four questions rapidly (the question id of all the four delete requests was 1)
3. Modified the remaining essay question to fit his requirement
4. Added two more questions
5. Copied session to the same course with a new name
6. Deleted previous session

The new session ended up having 2 copies of the same 3 questions (not 3 copies of the same 2 questions as I reported earlier. that was my mistake).

The question numbers were messed up, and that's how I got alerted.

**Comment by kanghj** [comment]
To double-check, the log for the messed up question numbers only triggered on the new session, and not for the original session? 

The logic for copying sessions looks fine, my guess is that the user clicked the copy button twice, and due to eventual consistency, the check for an existing feedback session failed to stop the copying from happening again, so the questions got copied over 2 times. One thing we could do is to disable the form submission button after the user has already submitted it.

**Comment by damithc** [comment]
It was not triggered on the original session, but that is not conclusive because he didn't load results of that session anyway.
If it was copied twice, shouldn't there be two session objects?

**Comment by kanghj** [comment]
The log.severe for the invalid question numbers should happen when the questions are retrieved from the database, so going to the feedback session's edit page should trigger it if it became invalid then. 

If eventual consistency happened, then the feedback session, that was copied second, would be written to the database with the same key (feedbackSessionName%courseId) as the first copied session and replace it?

**Comment by damithc** [comment]
Doesn't look like it was triggered by the previous session. So the duplication may have been the result of copying.
Yes, I guess the session could have got overwritten while the questions got saved as duplicates.

**Comment by damithc** [comment]
The user says he only noticed the duplicates when he revisited the session the following day. However, the duplicates did not appear when he previewed the session as a student, so he left the duplicates alone.

**Comment by kanghj** [comment]
Are there already responses for the session? The duplicated questions should still be removed, if possible. For each question number, the students will only see one of the 2 possible questions since both questions have the same hashcode and are equal (since they are the same question). However, which of the two question the students see will not be deterministic, and therefore it might result in responses to both questions.

**Comment by damithc** [comment]
I've removed the questions. There were no responses at that time.
Can we make it deterministic?
Can we apply the same hashcode technique on instructor side?

**Comment by kanghj** [comment]
Will make new issues to discuss these points. Making the question order deterministic could be resolved when we introduce the modified and created date attributes on questions.
