### ISSUE TITLE
admin activity log: wrong user time zone reported

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4525]
This user is from UTC-5 timezone
![image](https://cloud.githubusercontent.com/assets/1673303/10719806/6316eb04-7bca-11e5-93b9-f5cde49083ea.png)

**Comment by damithc** [comment]
Also note how there is no option to search further into the history, but that's a separate issue.

**Comment by damithc** [comment]
It's good if we can fix this by next milestone.

**Comment by bamboo3250** [comment]
@damithc: Could you try searching by his google email address instead of his name?

**Comment by damithc** [comment]
This user is not registered. I arrived at this page by clicking on the 'View recent actions' link from the search page

**Comment by bamboo3250** [comment]
if the user hasn't joined any course that has a session, we can't know his timezone. In that case the action will use Admin Time Zone instead.

**Comment by bamboo3250** [comment]
@kanghj is there any function to get the user googleId by his name?

**Comment by damithc** [comment]
We should be able to determine the course of an unregistered user. A request from an unregistered user always contain some information to identify the course.

**Comment by bamboo3250** [comment]
The current version should be able to handle unregistered users. But we have to use google id when searching.

How about I change the 'View recent actions' link to use the google id to search instead of the name? If there are many people having the same name from different places, the reported time zone may not be correct as well.

**Comment by damithc** [comment]
When a user is not registered, we don't know the Google ID, right?

**Comment by bamboo3250** [comment]
That's right. For unregistered users, we will search by the name and the role. The role will contain the information about the course so it's possible to search for the user's activity from that .

**Comment by damithc** [comment]
For registered users, we can use the Google ID to search. For unregistered users, we have to use some other means. Perhaps we can use the recently-added log ID for that? Currently it uses 'Unknown+timestamp' for unregistered users. May be we use 'email+courseid.timestamp' or something like that instead? @kanghj

**Comment by bamboo3250** [comment]
That will work only when there is at least 1 activity log entry from the user. Like the above screenshot, there is no log entry when you search for his name so we have no other information besides his name.

**Comment by damithc** [comment]
That's true. But since I arrived at this page from the search page, we already know which course the user is in. So it is doable, although it may require changing several things.
