### ISSUE TITLE
Change admin activity log's id to use email instead of google id

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4527]
Use 'email%courseid%timestamp', as described in #4525

**Comment by damithc** [comment]
Can we add a special char between email and courseId without interfering with the ability to search for both at the same time? i.e. it should not look like a delimiter to the search API but should look like a delimiter to us e.g. email%courseId

**Comment by damithc** [comment]
I'm not sure about the 2nd %. Sometimes I might want to search for email%courseId only. Not sure if log search can do a partial search like that. Can it?

**Comment by kanghj** [comment]
Yes, app engine's log search handles partial search. I have not implemented searching for log id in our own admin activity log search yet, will make an issue for it.

**Comment by kanghj** [comment]
For some pages, it will not be possible to display the email and courseid (like the instructorHomePage , InstructorFeedbacksPage, studentHomePage). For these pages, do I use the googleId as a fallback? 

Alternatively, we can use email+course only when the googleId cannot identify the user, such as for unregistered students.

**Comment by damithc** [comment]
Yes, let's use email+course when googleId is not available.
