### ISSUE TITLE
Update GodMode to correctly handle profile photo blob keys

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/repo#4546]
Currently, the blob key is extracted to `${regkey.enc}`. However, this is not working correctly as the blob keys contain a `:` in the key.

GodMode needs to be updated to handle this.

For example, assume that the raw blob key on a local env is `encoded_gs_key:L2dzL3RlYW1tYXRlcy1hc2hyYXkuYXBwc3BvdC5jb20vY2hhcmxpZS50bW1zLmFzaHJheQ`

This is currently converted by GodMode to `${regkey.enc}:L2dzL3RlYW1tYXRlcy1hc2hyYXkuYXBwc3BvdC5jb20vY2hhcmxpZS50bW1zLmFzaHJheQ`

However, this is incorrect. It should be converted to just `${regkey.enc}`

Once this is fixed, StudentProfilePageUiTest will need to be updated to check the new buttons added as part of #4472

**Comment by wkurniawan07** [comment]
It's inaccurate. Blob key and regkey are definitely not the same thing. What needs to be done is adding another replacement for blob key. The fact that the replacement even occurs speaks of another problem, though: that means the blob key is accidentally targeted by the replacement part intended for regkeys.

**Comment by ashrayjain** [comment]
@thyageshm thoughts?

**Comment by thyageshm** [comment]
That is true.... blob-key *should* be handled separately. But right now there are no places where we have a blob-key in the html checks. This is a new case. So yes, we have to add a new placeholder for this one
