### ISSUE TITLE
Wrong sorting order in table sort test

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4560]
Noticed this after running the full test suite. Not sure if it is a problem in the test or the sorting algo
![image](https://cloud.githubusercontent.com/assets/1673303/10935632/4b7353b6-8322-11e5-83a7-74d903b37a37.png)

**Comment by wkurniawan07** [comment]
Isn't this sorted by name? It looks correct to me.

**Comment by damithc** [comment]
It's sorted by date. See 2nd circle. I sorted it manually by clicking on the up arrow.

**Comment by wkurniawan07** [comment]
If I understand the picture correctly, the up arrow in the 2nd circle belongs to sorting by name.

**Comment by damithc** [comment]
Ah, that's right. My mistake. You can also see the reason for my mistake. I think it is not a big problem in the actual pages because columns are narrower and there are vertical lines. 
Closing.
