### ISSUE TITLE
Remove some placeholders used in UI tests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4585]
These four can be immediately removed:

1. `${comment.date}`: The date/time format for comments is slightly different (`Thu, 07 May 2015, 19:52:00 UTC`, as compared to `Thu, 07 May 2015, 07:52 PM`), which can be standardized. Also, `${comment.date}` makes little to no sense; the ones being replaced are current date/time, which really should be the same placeholder `${datetime.now}`.
2. `${support.email}`: The placeholder is not in any HTML test files and the only test data using it is `AutomatedSessionRemindersTest`. After looking at the usage, I cannot see the reason why specifically support email is needed. If the intention is to check whether the emails are sent (as explained in the explanatory comment in the Java file), any of the test accounts will do just as well in its place.
3. `${test.unreg}`: No json file is using this (well otherwise the account is not unregistered), there is only one HTML file using this (`studentHomeHTMLEmpty.html`) and that is due to full HTML verification (just our luck!). Moving the full HTML verification to another HTML file removes the said placeholder entirely from existence.
4. `${submissions.number}`: This is found in `login.html`, which is part of `AllAccessControlUiTests`. From what I understand, the intention is to check whether the page is the index page, but doing this via HTML check is an overkill. A simple `containsExpectedPageContents()` as used by other page objects should suffice here. (and here's another thing: see the user testimonial portion which changes every few seconds? had it been changing every half a second or so, this HTML verification will be an epic failure)

**Comment by damithc** [comment]
Standardizing date format sounds like it should be an issue of its own? It affects the app behavior, right?.

**Comment by wkurniawan07** [comment]
Only in terms of display, nothing else.

**Comment by damithc** [comment]
It's a nice little enhancement that deserves to be on its own. Maybe cherrypick the commit to a separate branch?
