### ISSUE TITLE
admin sessions page: show more stats

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4598]
We can show more stats here: e.g. number of institutes, number of open sessions, etc.
![image](https://cloud.githubusercontent.com/assets/1673303/11800015/ad61943c-a313-11e5-9f6f-80362e8971de.png)

**Comment by sundychenD** [comment]
Hi Professor Damith, I just finished my first "forFirstTimers" issues and I'd like to work on this "forContributor" issue. I don't have the privilege to add the "ongoing" label, so I'm commenting here to indicate my current occupation.

**Comment by damithc** [comment]
Sure, go ahead.
