### ISSUE TITLE
Tests are failing because comments dates are wrong

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#4615]
![comment_date](https://cloud.githubusercontent.com/assets/2216119/12060121/7a626ff6-afa3-11e5-97af-9d0ea877816b.PNG)

Today is Dec 31 2015, comments are showing Dec 31 __2016__. Is anyone else having the same problem?

Happening because "YYYY" is used instead of "yyyy". @wkurniawan07, do you want to fix this? I will only have time on the weekends to submit a pr otherwise

**Comment by wkurniawan07** [comment]
Lol why me. Anyway ok I'll do it, shouldn't be anything more than changing 4 characters right.
