### ISSUE TITLE
Include Godmode as part of the mainstream development process (process.md)

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#4623]
We could add it under "Fixing Issues" 
1. either under point 8 at the ```Ensure dev green``` 
2. or as a new point dedicated for testing, i.e., fix any broken tests and/or add new tests

I personally prefer the second option. what do you think? @damithc @LowWeiLin @wkurniawan07

Also, if need be, we can change the name Godmode to something more "professional"...

**Comment by damithc** [comment]
I'm fine with either option. 
I'm fine with keeping 'Godmode' too. The name fits what it does, and easy to remember. :-)

**Comment by wkurniawan07** [comment]
I've no strong opinion either, both look equally good to me. More importantly, we need to caution whoever's using Godmode though, for all we know it's quite capable of generating the wrong result.

**Comment by damithc** [comment]
Yes, dev must check after using God mode. In addition, the reviewer must check through all changes to html files to make sure they are legit. If God mode is working as intended, the reviewer will no longer have to wade through a ton of unrelated white space changes. Any change in html file should be a direct result of the issue being fixed.

**Comment by wkurniawan07** [comment]
What I always do is running the same test again (if not the full test suite) without using Godmode and ensure it passes. Also, white space changes might be necessary if the DOM tree changes, e.g from
```html
<div>
  <span>
    <img>
  </span>
</div>
```
to
```html
<div>
  <div>
    <span>
      <img>
    </span>
  </div>
</div>
```
but of course reviewing with `?w=1` solves that issue.

**Comment by damithc** [comment]
That's a good practice. The process should *require* dev to pass tests without the God mode before submitting the PR.
Side question: can be build that into God mode? i.e. automatically run the test again.
