### ISSUE TITLE
Rank question: ranked values not visible in the csv file

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4634]
Only the first choice is shown in the csv file
![image](https://cloud.githubusercontent.com/assets/1673303/12322518/b846f7b8-baef-11e5-8863-4d3e2d44a4a1.png)

**Comment by damithc** [comment]
Is this format better? It allows users to sort based on each rank.

| rank 1 | rank 2 | rank 3 |
| --------- | --- | --- |
| value x | value y | value z |
| value z | value y | value x |

**Comment by kanghj** [comment]
The values are actually in the csv file, but the cells need to be expanded to show all the details in it. I was trying to keep the format similar to the rank recipients question type, but I have to agree that it wasn't a very useful format.

**Comment by damithc** [comment]
Yep, found the rest of the values when I expanded the cells. Other users may be mislead the way I was. So, are we going to change the format?

**Comment by kanghj** [comment]
Yes, I think I am going to change the format. The current format isn't useful since it is difficult to sort or manipulate the values for further analysis. Also solves the existing issue that it's misleading.
