### ISSUE TITLE
Errors in InstructorCourseDetailsPageUiTest

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4636]
- Line 177:
```java
String alicePassword = TestProperties.inst().TEST_STUDENT2_PASSWORD;
```
but Alice uses student 1 account. (!!!!)
- Try doing this: allow email access for Charlie, but _not_ for Alice. The test will still (falsely) pass.

**Comment by damithc** [comment]
1. We should use the `student1` instead of `alice`. If we did, this would have been noticed much earlier.
2. I guess the test was passing for me earlier because I use the same password for all test accounts. :-p
