### ISSUE TITLE
Fix header and footer zoom issue on student feedback submission page

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/repo#4639]
Follow up to #4595 where the `user-scalable` part was removed.

**Comment by ashrayjain** [comment]
After a lot of testing, it appears that this issue only happens on the native android 4.3 browser. It works ok on chrome mobile and safari mobile as well as newer versions of the android browser. In addition, I have checked the code that is handling this. It is all done by Bootstrap and CSS, so there is nothing much we can do to fix it, short of disabling user zoom altogether. But I don't think we should do that since the problem is not that big.

**Comment by damithc** [comment]
Can close if you think it is not worth fixing.
