### ISSUE TITLE
Move team before giver/recipient for feedback result responses

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#4672]

**Comment by unyoungwax** [comment]
In group by question view, the giver's team is moved to the first column and the recipient's team is moved to the third column.
![screenshot_question](https://cloud.githubusercontent.com/assets/10228385/12668074/20a84cd6-c68e-11e5-9c72-18ae89cfc440.jpg)

In group by recipient>question>giver view, the team is moved to the first column.
![screenshot](https://cloud.githubusercontent.com/assets/10228385/12668101/5aba31aa-c68e-11e5-98b2-13af29ca5a3c.jpg)

In group by giver>question>recipient view, the team is moved to the first column.
![screenshot_recipient](https://cloud.githubusercontent.com/assets/10228385/12668203/01f111f0-c68f-11e5-9dfc-1200fcc57b59.png)

Is this okay?

**Comment by LowWeiLin** [comment]
This issue is about moving the team column for the statistics, not for the feedback responses themselves...

**Comment by unyoungwax** [comment]
I misunderstood the issue. However, I think it is inconsistent if the team column for the statistics and the feedback responses are at different columns.

**Comment by LowWeiLin** [comment]
You can rename this issue or create a separate issue.
As for the screenshots, i'm not sure if the photo column should be between the team and name. Perhaps leaving the photo column in front is better?
@damithc

**Comment by damithc** [comment]
Yes, it's odd to have it in the middle. Let's leave the photo on the left-most column.
