### ISSUE TITLE
Refinements to the workflow

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4714]
I propose following changes to the workflow:

**Issue life cycle:**
* An issue in `s.toMerge` state should be verified by PM (indicated by the `s.mergeApproved` label) before it is merged. If the PM asks for further changes, the issue goes back to `s.ongoing`
Reason: we can't rely on just one peer reviewer to ensure the code quality.  
* Senior developers and above should not take lower priority issues when there are open higher priority issues. Committers are encouraged to do the same.
Reason: we have very limited man power. We should spend it on high priority issues. That's the whole purpose of having priorities.

**Team Lead responsibilities:**
* Ensure the Milestone plan should be ready at the beginning of the milestone.
Reason: Developers need more practice on planning and estimation. 

**Coding style:**
* All public members and non-trivial private members should have header comments.
Reason: Header comments help in ensuring members are well-defined. e.g. conformance to Single Responsibility Principle.

**Comment by damithc** [comment]
Guys, any comments? @thyageshm please update the documentation in due course, preferably before next milestone.

**Comment by damithc** [comment]
Another thing: A PR is supposed to merge within one release cycle, two at the most. The onus is ont the dev to remind reviewer to keep things moving. PRs still open after two weeks will be closed without merging. 
{This needs to go under instructions to contributors as well as team lead}

**Comment by thyageshm** [comment]
@damithc should we consider changing the `s.toMerge` to `s.mergeRequested`?

**Comment by damithc** [comment]
Strictly speaking, it is `s.approvalRequestedToMerge` and because that's too long, we'll keep it as `s.toMerge` :-)

**Comment by thyageshm** [comment]
ok!
