### ISSUE TITLE
Typo in the about page

### ISSUE THREAD

**Issue by jkt001** [TEAMMATES/repo#4760]
This is the live version of TEAMMATES:
http://teammatesv4.appspot.com/about.html

All area leads are misspelt as "Aread lead" (edit: and one of the area lead's name is incorrectly spelt.)

<img width="622" alt="screen shot 2016-02-12 at 19 58 20" src="https://cloud.githubusercontent.com/assets/8586215/13006307/178da4c6-d1c3-11e5-9091-ddc864c30b1d.png">

**Comment by wkurniawan07** [comment]
@JosephineKwa your name... :stuck_out_tongue: :stuck_out_tongue:

**Comment by jkt001** [comment]
oh that means there's another typo... edited the issue so that it can be fixed in the same PR

**Comment by JosephineKwa** [comment]
More first timer issues i guess :stuck_out_tongue_closed_eyes:

**Comment by damithc** [comment]
@jkt001 can you submit a PR for this? I prefer to fix it soon, given that GSoC next round is coming up.

**Comment by jkt001** [comment]
@damithc alright... gonna do it now
