### ISSUE TITLE
Investigate Google Analytics effect on dev server testing and vice versa.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#625]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on February 07, 2013 12:29:53_

Is Google Analytics code slowing down dev server testing?
Is dev server testing skewing the data collected by Google analytics?

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=626_

**Comment by thyageshm** [comment]
@ashrayjain @wkurniawan07 do we have google analytics code in Teammates?

**Comment by wkurniawan07** [comment]
Yes we have. I've actually investigated this some time back and got these findings:

1. Is Google Analytics code slowing down dev server testing? Doesn't look like it, and should be marginal if it is. However if the internet connection dies while some script is loading (e.g scripts from CDN, which includes Google Analytics code), the page (and thus the test) will freeze.
2. Is dev server testing skewing the data collected by Google Analytics? It will, even in staging server testing. Google Analytics track based on the identifier provided in the js file, and that value is the same for all developers.

**Comment by damithc** [comment]
Not so important at the moment. Let's close it.
