### ISSUE TITLE
implement instructor:joinCourse feature

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#661]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on February 25, 2013 15:40:03_

The current way of keying in GoogleID for instructors is prone to errors and malicious flooding.
We would like to have the same 'join course' functions for instructors. When an instructor account is created (by admin or by another instructor), an email is to be sent to the instructor with a URL to click, that will automatically join the instructor to the course.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=662_

**Comment by thyageshm** [comment]
@damithc I believe this one has been fixed

**Comment by damithc** [comment]
Yes. closing.
