### ISSUE TITLE
test pages: extract repeated chunks into separate files

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#681]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 06, 2013 08:53:54_

We can extract repeated text chunks (e.g., footer, <noscript> section) into separate files and dynamically insert them before actual<-->expected comparison. This is similar to how we insert app version number (in the footer) dynamically before comparison. 
It might slow down testing slightly. However, test pages will become easier to manage.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=682_

**Comment by thyageshm** [comment]
@damithc is this issue still relevant?

**Comment by damithc** [comment]
No. closing.
