### ISSUE TITLE
remove mobile.jsp and oldIE.jsp if they are not being used

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#699]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 15, 2013 23:22:36_

As the title says

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=700_

**Comment by damithc** [comment]
Previous patch abandoned. Ready to take over by a new dev.

**Comment by suhas355** [comment]
Hi Sir,

    I am a GSOC aspirant. I have finished A-D steps in Orientation program. Can I be assigned by this bug.

P.S - Google group Thread:  https://groups.google.com/forum/#!searchin/teammates-contributors/suhas/teammates-contributors/7JgP4uNWaYs/9HErkzM94PQJ

Thanks
Suhas K S

**Comment by visithamanujaya** [comment]
can i try this one as a first timer

**Comment by kanghj** [comment]
This issue doesn't seem relevant anymore as the files have already been removed. Do you want to try #1743 instead?
