### ISSUE TITLE
Make it clear that students receive notifications when an instructor publishes an evaluation result

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#737]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 24, 2013 11:43:36_

We can make this fact clear in existing hover text, confirmation dialogs, and status messages.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=738_

**Comment by wkurniawan07** [comment]
We do have something like this now, if it's sufficient:
![image](https://cloud.githubusercontent.com/assets/7261051/10746042/e01d7e12-7c81-11e5-9431-af98a3ddf74e.png)

**Comment by damithc** [comment]
Yes. Closing.
