### ISSUE TITLE
Move HTML style guide to a GoogleDoc

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#738]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 24, 2013 11:46:03_

Other style guides are in GoogleDoc form. We can move this one to a GoogleDoc too, as they are easier to maintain.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=739_

**Comment by EgbeEugene** [comment]
please i need more information on this issue 
                  thanks.

**Comment by weaveranoop** [comment]
Hi Damith,
Is this the document to be shifted 
https://github.com/weaveranoop/repo/blob/master/src/main/webapp/dev/htmlstyleguide.html
Can you please assign me this issue and help me proceed with the same.
Thanks,
Anoop

**Comment by MrFool** [comment]
Do assign me this issue as my first issue.

Introduction can be found at - 

https://groups.google.com/forum/#!topic/teammates-contributors/7lYDEGG6R24

**Comment by kanghj** [comment]
@weaveranoop, I will assign you this issue after you have accepted the invitation to join TEAMMATES as a contributor.

**Comment by weaveranoop** [comment]
Hi kanghj,
I have accepted the invitation. Please do the needful and clarify the doubt in my previous comment.
Thanks,
Anoop

**Comment by kanghj** [comment]
Yes, @weaveranoop that looks like the document to be shifted.

**Comment by weaveranoop** [comment]
Hi Damith and kanghj,
I have resolved all the comments in the doc and opened a new issue(#3166) as required. Please have a look.
Thanks.
