### ISSUE TITLE
Help students who forgot which Google ID they used for TEAMMATES

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#775]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on May 02, 2013 08:00:57_

Some students have multiple Google IDs and cannot remember which one they used for TEAMMATES

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=776_

**Comment by MrFool** [comment]
Duplicate of #1259 and it has more discussion there so let's close this
