### ISSUE TITLE
Remove @author tag from Eclipse javadoc style templates

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#829]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on May 11, 2013 11:11:50_

This is because we don't use it in this project

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=830_

**Comment by wkurniawan07** [comment]
Not sure about this, but I can't find the `@author` tag anywhere.

**Comment by damithc** [comment]
Closing.
